과제2. Restaurant
CodeSoom/react-week4-assignment-2 pull request #1
Opened 2020-06-26 17:04 UTC by kc7851

의식적인 TDD 훈련.. 많이 빡셉니다 ㅋㅋ
그래도 뭔가 재미는 있습니다!
최대한 많이 타이핑하려고 복붙은 많이 자제했는데, 역시 mocking하는 부분이나 많이 안써본 부분들은 기억이 안나서 한참 헤맸네요.
역시 많이 해보는 방법밖에 없을것 같네요.
갈 길이 구만리네요 ㅎㅎ

2020-06-27 03:44 UTC, wholemann requested changes
잘해주셨어요!

다만 test쪽에서 좀 아쉬운 부분이 여러 테스트에서 반복되어 나타나네요.

comment 참고하셔서 고민해보시고 진행하시면 될 듯 합니다.

질문은 언제든 DM으로 환영합니다!

2020-06-27 03:44 UTC, wholemann commented on src/App.test.jsx
> +  context('when start application', () => {
지금은 context가 딱히 필요해 보이진 않네요.

맥락이 갈릴 때 보통 사용합니다.

2020-06-27 03:44 UTC, wholemann commented on src/Input.jsx
> +  { informations: { name, category, address }, onChange, handleClick },
```suggestion
  {
     informations: { name, category, address },
     onChange, handleClick
   },
```

이정도로 길어지면 줄 바꿈을 해주는 게 좋습니다.

information의 의미를 알기 어렵네요. 레스토랑에 관한 내용이니

restaurant은 어떨까요?

2020-06-27 03:44 UTC, wholemann commented on src/Input.test.jsx
> +      expect(addressInput.value).toBe('');
저는 이 테스트가 굳이 필요한진 잘 모르겠습니다.

2020-06-27 03:44 UTC, wholemann commented on src/Input.test.jsx
> +      expect(addressInput.value).toBe(informations.address);
```suggestion
  expect(getByDisplayValue('한식당')).not.toBeNull();
  expect(getByDisplayValue('한식')).not.toBeNull();
  expect(getByDisplayValue('강남구')).not.toBeNull();
```

도 가능하죠. 어떠신지요?

2020-06-27 03:44 UTC, wholemann commented on src/Input.test.jsx
> +      const addressInput = container.querySelector('input[name = address]');
굳이 dom을 직접 다룰 필요가 없다고 봅니다.

다른 편리한 query들이 많기 때문이죠.

2020-06-27 03:44 UTC, wholemann commented on src/InputContainer.jsx
> +    dispatch(updateInformations(target, value));
18, 19 사이에 공백 한 줄 넣어주면 좋겠네요.

2020-06-27 03:44 UTC, wholemann commented on src/InputContainer.jsx
> +    return null;
사실 굳이 return 안 하셔도 좋습니다.

// TODO: ...

로 해놔도 좋습니다.

2020-06-27 03:44 UTC, wholemann commented on src/reducer.js
> +        [action.payload.target]: action.payload.value,
value가 무엇인지 불분명합니다. 정확한 명명을 해주는 게 좋아보여요.

2020-06-27 03:44 UTC, wholemann commented on src/reducer.js
> +  informations: {
restaurant라고 한다면

restaurant.name

restaurant.category

등으로 사용되는 쪽에서 표현되겠죠? 훨씬 직관적일 겁니다.

2020-06-27 03:44 UTC, wholemann commented on src/reducer.test.js
> +      });
같은 테스트가 반복되고 있습니다. 이건 하나로 합칠 수 있을 겁니다.

그리고 테스트의 의미를 문장으로 더 표현해주세요.

2020-06-28 02:57 UTC, kc7851 commented on src/App.test.jsx
> +  context('when start application', () => {
오.. 알겠습니다!

2020-06-28 02:58 UTC, kc7851 commented on src/Input.jsx
> +  { informations: { name, category, address }, onChange, handleClick },
그렇네요 ㅋㅋ restaurant이 좋은거 같아요

2020-06-28 03:04 UTC, kc7851 commented on src/Input.test.jsx
> +      expect(addressInput.value).toBe('');
처음 input 3개를 만들 때 작성했던 테스트였는데, 어떻게 작성해야할지 좀 애매했었어요

2020-06-28 03:05 UTC, kc7851 commented on src/Input.test.jsx
> +      expect(addressInput.value).toBe(informations.address);
읽는 입장에서 expect(getByDisplayValue('한식당')).not.toBeNull(); 이 더 쉽게 읽히는것 같습니다.

2020-06-28 03:07 UTC, kc7851 commented on src/InputContainer.jsx
> +    return null;
아.. 그렇군요 ㅋㅋ 앞으로 TODO로 넣겠습니다.

2020-06-28 03:17 UTC, kc7851 commented on src/reducer.js
> +        [action.payload.target]: action.payload.value,
input value를 의미하는데 inputValue 정도면 맞을까요?

2020-06-28 10:48 UTC, wholemann approved these changes
고생하셨어요. Merge할게요.

나머진 피드백 강의를 보시면 채우실 수 있을 겁니다ㅎㅎ

다음주도 화이팅입니다.

2020-06-28 10:48 UTC, merged