Cho jinmok
CodeSoom/react-week4-assignment-2 pull request #107
Opened 2022-08-27 12:00 UTC by ChoJinmok

2022-08-27 13:15 UTC, daadaadaah requested changes
후다닥🏃‍♂️ 과제2개를 수행하셨군요 잘하셨어요!👍

좀만 다듬어봅시당!!ㅎㅎ

2022-08-27 13:15 UTC, daadaadaah commented on src/App.test.jsx
> +  context('with restaurants list', () => {
레스토랑 목록이 없는 경우도 테스트하고 싶으시면, context를 사용하셔도 되는데, 지금 해당 테스트가 없어요!
context 없애주시거나 해당 테스트를 추가해주십시당!ㅎㅎ

2022-08-27 13:15 UTC, daadaadaah commented on src/App.test.jsx
> +function stubSelector({
과제 1 리뷰 참고해주세요!ㅎㅎ

2022-08-27 13:15 UTC, daadaadaah commented on src/Form.jsx
> +      <input id="address" type="text" placeholder="주소" value={address} onChange={onChange} />
속성이 2~3개 이상인 경우, 세로 정렬을 해주시는 것이 가독성에 더 좋습니당!!ㅎㅎ

2022-08-27 13:15 UTC, daadaadaah commented on src/Form.test.jsx
> +  function setup(information = {
과제 1 리뷰 참고해주세요!ㅎㅎ

2022-08-27 13:15 UTC, daadaadaah commented on src/List.test.jsx
> +  };
과제 1 리뷰에서 말씀 드렸듯이 이런 데이터들은 관리할 수 있는 폴더 하나 만들어서 활용해봅시다!ㅎㅎ

2022-08-27 13:15 UTC, daadaadaah commented on src/reducer.js
> +  information: {
너무 추상적인 단어라서 사용자 정보인지, 레스토랑 정보인지 헷갈릴 것 같아요! 정보라는 단어보다 어떤 정보인지가 중요하니 의도를 잘 드러내봅시당!ㅎㅎ

2022-08-27 13:15 UTC, daadaadaah commented on src/reducer.js
> +    classification: '',
`category` 용어를 사용해보시는건 어떠신가요?ㅎㅎ

2022-08-27 13:15 UTC, daadaadaah commented on src/reducer.js
> +}
과제1 리뷰 참고해주세요!

2022-08-29 05:41 UTC, merged

2022-08-30 14:24 UTC, ChoJinmok commented on src/Form.jsx
> +      <input id="address" type="text" placeholder="주소" value={address} onChange={onChange} />
아하!~ 훨씬 가독성이 좋네요!~ 좋은 리뷰 감사합니다!!🙂

2022-08-30 14:25 UTC, ChoJinmok commented on src/Form.test.jsx
> +  function setup(information = {
given2로 고쳐봤습니다!!🙂

2022-08-30 14:25 UTC, ChoJinmok commented on src/List.test.jsx
> +  };
이렇게 하니까 훨씬 편한 거 같아요!! 좋은 리뷰 감사합니다!

2022-08-30 14:26 UTC, ChoJinmok commented on src/reducer.js
> +}
object literal로 고쳐봤습니다!~

2022-08-30 14:26 UTC, ChoJinmok commented on src/App.test.jsx
> +function stubSelector({
given2로 고쳤습니당!!~

2022-08-30 17:36 UTC, ChoJinmok commented on src/App.test.jsx
> +  context('with restaurants list', () => {
아~ 그렇군용?! 좋은 리뷰 감사합니다!

2022-09-01 10:46 UTC, ChoJinmok commented on src/reducer.js
> +  information: {
레스토랑 정보니까 그냥 restaurant라고 해주는게 좋겠네요!~ㅎㅎ
좋은 리뷰 감사합니다!

2022-09-01 10:46 UTC, ChoJinmok commented on src/reducer.js
> +    classification: '',
카테고리가 더 맞는 표현 같네용 😭 좋은 리뷰 감사합니다!~