4주차 - 레스토랑 정보 확인 및 예약 시스템 구축하기
CodeSoom/react-week4-assignment-2 pull request #112
Opened 2022-11-03 11:12 UTC by yxxnhx

# 목표
레스토랑 정보 확인 및 예약 시스템 구축하기

## 진행사항
App 컴포넌트를 테스트하기 위한 테스트 파일을 셍성하였습니다

2022-11-04 06:59 UTC, daadaadaah requested changes
과제2까지 쭉쭉 진행해나가시고 아주 좋습니다!👍
다음 PR 기다리고 있을게요!ㅎㅎ

2022-11-04 06:59 UTC, daadaadaah commented on src/App.test.jsx
> +  describe('입력한 레스토랑 이름이 랜더링 된다', () => {
남겨주신 질문 관련해서, 이부분을 어떻게 수정해야 하는지 체크해봅시당!ㅎㅎ
jest에서 describe와 it을 어떻게 다르게 처리하는지에 대해 한번 공부해봅시당!

2022-11-04 06:59 UTC, daadaadaah commented on src/store.js
> +  lists: [
그냥 `lists`보다 좀더 의도가 드러나는 표현이면 더 좋을 것 같아요!ㅎㅎ

2022-11-05 10:58 UTC, yxxnhx commented on src/App.test.jsx
> +  describe('입력한 레스토랑 이름이 랜더링 된다', () => {
중첩을 시켜서 테스트를 진행하고 싶었었는데 그 관계를 정확하게 알고 있지 않아 생긴 문제였네요 감사합니다!

2022-11-05 10:58 UTC, yxxnhx commented on src/store.js
> +  lists: [
변경하여 반영하겠습니다!

2022-11-05 11:06 UTC, yxxnhx commented
### 목표
컴포넌트 분리, test 파일 구현

### 구현 사항
- [x] 입력, 목록 관심사에 따른 컴포넌트 분리
- [x] reducer 파일 구현하기
- [x] 입력 테스트 파일 구현하기
- [x] 목록 테스트 파일 구현하기
- [x] 테스트 커버리지 100 달성하기
 
안녕하세요 트레이너님!
테스트를 중첩시켜서 하고 싶은 마음에 describe - context - it 관계를 정확하게 알지 못한 채 일어났던 문제였더라구요😬
해당 부분 수정 후에 관심사 분리를 하여 이름, 분류, 주소를 모두 입력 시, 셋 중 하나라도 입력을 하지 않았을 시, 레스토랑 목록이 없을 시, 있을 시를 구분하여 테스트 파일을 생성하였습니다
아직은 리덕스나 tdd에 익숙치 않아 커밋을 어떻게 쪼개서 해야하는지, 테스트 사이클을 어떻게 해야 하는지를 모르겠습니다ㅠㅠ

### 질문
- 커밋을 할 때는 어떻게 쪼개서 진행하는 것이 좋을까요?
-> 현재는 나름대로 쪼개서 진행을 하려고 의식해서 올리기는 하는데 뭔가 이게 맞는 방식인지를 잘 모르겠습니다😵‍💫
- 테스트 사이클은 어떻게 진행하는 것이 좋을까요?
-> 현재는 먼저 틀만 간단히 잡은 다음에 테스트 파일에서 테스트를 하고 거기에서 필요한 것을 다시 파일로 가서 수정을 하고 수정한 것을 테스트 파일에서 제대로 돌아가는지 확인을 하는 방식으로 하고 있습니다

2022-11-06 05:10 UTC, daadaadaah requested changes
> 커밋을 할 때는 어떻게 쪼개서 진행하는 것이 좋을까요?
-> 현재는 나름대로 쪼개서 진행을 하려고 의식해서 올리기는 하는데 뭔가 이게 맞는 방식인지를 잘 모르겠습니다😵‍💫
- 지금보다 좀더 작게 쪼개서 올려보는 걸 추천드려요! 예를 들어, https://github.com/CodeSoom/react-week4-assignment-2/pull/112/commits/7cf8733b610c068179344d0778d7cb50ba30bd54 이 커밋 같은 경우도, 좀더 잘게 쪼개 수 있겠죠?ㅎㅎ저 같은 경우 최대한 잘게 쪼갠 후 나중에 합쳐져 있으면 좋을 것 같은 것들은 `git rebase -i`를 활용해서 뭉쳐줍니다!

> 테스트 사이클은 어떻게 진행하는 것이 좋을까요?
-> 현재는 먼저 틀만 간단히 잡은 다음에 테스트 파일에서 테스트를 하고 거기에서 필요한 것을 다시 파일로 가서 수정을 하고 수정한 것을 테스트 파일에서 제대로 돌아가는지 확인을 하는 방식으로 하고 있습니다

- 잘 진행하고 계시는 것 같아요!ㅎㅎ저도 작업할 때 테스트 랑 실제 코드라 왔다가 갔다 하면서 작업합니다! (흑역사지만ㅠㅠ제가 코드숨에서 처음 TDD 배웠을 때, 의도적으로 테스트를 먼저 작성해볼려고 노력했어요! 한번 참고해보세요 [PR 링크](https://github.com/CodeSoom/react-week4-assignment-2/pull/2/files#diff-56161beeb9dfcd8d47dc5cc8430b87640f6e5d34a21b9b1a0e2c829fa834f34a)

2022-11-06 05:10 UTC, daadaadaah commented on src/App.test.jsx
> +import restaurantList from '../fixtures/restaurantList';
맥랙 구분을 위해 한줄씩 띄어주는게 좋겠죵?ㅎㅎ

2022-11-06 05:10 UTC, daadaadaah commented on src/Input.test.jsx
> +    // });
주석 정리해주세여~ㅎㅎ

2022-11-06 05:10 UTC, daadaadaah commented on src/Input.test.jsx
> +  context('레스토랑 정보를 입력하면', () => {
context는 대비되는 상황에서 사용되는 것이라, 지금은 그냥 describe 로 "레스토랑 정보 입력"으로 표현해주시던지, 아니면 it문에 표현해 주시는게 적절할 것 같아요!

2022-11-06 05:10 UTC, daadaadaah commented on src/Input.test.jsx
> +      expect(screen.getByDisplayValue('김밥나라')).not.toBeNull();
맥락 구분을 위해 한줄 띄어줍시당ㅎㅎ

2022-11-06 05:10 UTC, daadaadaah commented on src/List.test.jsx
> +  context('입력한 레스토랑이 있을 때', () => {
`입력한 레스토랑` 보다 그냥` 레스토랑 목록이 있을 때와 없을 때`로 구분하는게 좀더 적절하지 않을까 생각해요! 왜냐하면, List의 경우 그냥 props로 상태를 받기 때문이예요!

2022-11-06 05:10 UTC, daadaadaah commented on src/actions.js
> +export function updateRestaurant(keyValue, text) {
`keyValue` 보다 좀더 의도가 드러난 표현은 없을까여?ㅎㅎ

2022-11-06 15:02 UTC, yxxnhx commented on src/App.test.jsx
> +import restaurantList from '../fixtures/restaurantList';
아이구.. 그렇네요ㅠㅠ 넵! 수정하겠습니다

2022-11-06 15:02 UTC, yxxnhx commented on src/Input.test.jsx
> +    // });
아이고.. 코드 정리한다고 빼놨다가 깜빡했네요ㅠㅠ 정리하겠습니다~!

2022-11-06 15:02 UTC, yxxnhx commented on src/List.test.jsx
> +  context('입력한 레스토랑이 있을 때', () => {
아하 그렇네요 수정하겠습니다

2022-11-06 15:03 UTC, yxxnhx commented on src/Input.test.jsx
> +      expect(screen.getByDisplayValue('김밥나라')).not.toBeNull();
넵 맥락 구분 유념하겠습니다

2022-11-06 15:04 UTC, yxxnhx commented on src/actions.js
> +export function updateRestaurant(keyValue, text) {
넵 input의  속성인 name을 받아와서 사용을 해서 inputName으로 변경하였습니다 혹시 더 다른 좋은 이름이 있을까요? 사실 inputName이 완전히 좋은 이름이라고는 생각이 들지 않는데 그 외에는 사실 잘 떠오르지 않습니다🥲

2022-11-06 15:04 UTC, yxxnhx commented on src/Input.test.jsx
> +  context('레스토랑 정보를 입력하면', () => {
넵! 대비되는 상황에만 context로 구분하여 사용하는 것 잊지 않겠습니다 반영하여 수정하였습니다!

2022-11-06 15:07 UTC, yxxnhx commented
안녕하세요 트레이너님!
가장 기본 중에 기본인 주석을 지우지 않고 PR을 올렸다는게 민망하네요😅
맥락 구분을 위해서 띄어준다는걸 매주 피드백을 받으면서도 코드를 정리할 때 자꾸 까먹게 되어서 부끄럽습니다
다음주 과제에는 꼭! 유념해서 정리하도록 하겠습니다
그리고 이전에 트레이너님께서 하셨던 PR 내역도 정말 감사합니다! 참고해서 다음 과제에는 의도적으로 더 잘게 쪼갤 수 있도록 해보겠습니다!
이번 한주도 정말 감사했습니다👍

2022-11-07 04:17 UTC, daadaadaah approved these changes
이번주도 수고 많으셨어요!ㅎㅎ
저는 일하면서 PR 날릴 때, File Changed 클릭해서 셀프 리뷰도 한번 해보기도 해요~ㅎㅎ
새로운 개념 익히랴 과제 하느랴 정신없으실텐대, 내 작업 한번 되돌아보는 셀프 리뷰도 다음번 과제때 한번 해보세요~ㅎㅎ

2022-11-07 13:01 UTC, merged