레스토랑 test
CodeSoom/react-week4-assignment-2 pull request #113
Opened 2022-11-05 10:47 UTC by hyeji07

해설강의를 참고하여 레스토랑 test 작성중입니다..

2022-11-06 04:33 UTC, daadaadaah requested changes
해설 강의 보면서 잘 따라하신 것 같아요!ㅎㅎ
test 대신 describe - context - it으로 표현 한다면, 어떻게 표현해야 할까여?

2022-11-06 04:33 UTC, daadaadaah commented on src/reducer.js
> +  }
이전 과제들에서 if문이 많을 때 무엇을 활용해서 간단히 하였을까여?ㅎㅎ

2022-11-06 09:01 UTC, hyeji07 commented on src/reducer.js
> +  }
객체를 이용해서 다시 작성하였습니다!

2022-11-06 09:14 UTC, hyeji07 commented
describe - context - it 으로 수정하여 다시 커밋하였습니다!

2022-11-07 04:18 UTC, daadaadaah approved these changes
이번주도 수고 많으셨습니다! 이제 코드숨 반이 끝나는데, 남은 기간도 같이 화이팅해봐요👊

2022-11-07 13:01 UTC, merged