4주차 과제 2 - 레스토랑 만들기
CodeSoom/react-week4-assignment-2 pull request #114
Opened 2022-11-05 11:29 UTC by sejineeee

안녕하세요! 4주차 과제 레스토랑 만들기 늦게나마 제출합니다!

## 내용
![스크린샷 2022-11-05 오후 8 27 37](https://user-images.githubusercontent.com/86041335/200117612-bb5aee4f-4521-4ac4-987f-564b146d9f04.png)
현재 이 부분이 테스트가 안된 상태입니다!! 이 부분을 어떻게 테스트 하면 좋을 지 고민해보고 다시 올리도록 하겠습니다!!

2022-11-06 11:48 UTC, daadaadaah requested changes
> 현재 이 부분이 테스트가 안된 상태입니다!! 이 부분을 어떻게 테스트 하면 좋을 지 고민해보고 다시 올리도록 하겠습니다!!
- 이 부분 해결 되셨나요?

> 커밋을 어떤 순서대로 올려야 될 지 잘 모르겠어요ㅠㅠ 다 만들어 놓고 올리다 보니... 흑흑 그러다 보니 App 컴포넌트 파일을 가장 늦게 올리게 되어 버렸어요! (App 컴포넌트를 마지막에 올리면 안되는 것 같은데... 😂)
- 커밋 순서는 곧 작업 순서인데, 순서에 정답은 없습니다! 다만, 지금 TDD 연습하는 과정이므로, 테스트 코드를 먼저 작성하는 것이 좋은데, 올려주신 commit 을 살펴보면, 테스트 먼저 잘 작성해주셨어요! (흑역사지만ㅠㅠ제가 코드숨에서 처음 TDD 배웠을 때, 의도적으로 테스트 먼저 작성 + 작은 작업 단위 이 2가지를 지키려고 노력했어요! 한번 참고해보세요 [PR 링크](https://github.com/CodeSoom/react-week4-assignment-2/pull/2/files#diff-56161beeb9dfcd8d47dc5cc8430b87640f6e5d34a21b9b1a0e2c829fa834f34a)

2022-11-06 11:48 UTC, daadaadaah commented on fixtures/restaurantList.js
> +const restaurantList = [
저는 배열의 경우, 복수형 패턴을 주로 활용합니다!ㅎㅎ참고하세여ㅎㅎ

2022-11-06 11:48 UTC, daadaadaah commented on src/List.test.jsx
> +  });
이 테스트 할 때, fixture에 있는 레스토랑 목록 데이터를 활용해보면 좋을 것 같아요!ㅎㅎ

2022-11-06 11:48 UTC, daadaadaah commented on src/store/actions.js
> +export function changeText(keyValue, text) {
`keyValue` 보다 좀더 의도가 드러나는 단어는 없을까여? 처음 코드를 동료가 이 단어만 보면, 어떤 데이터를 받는지 의문이 들 것 같아요ㅎㅎ

2022-11-06 11:48 UTC, daadaadaah commented on src/store/reducer.test.js
> +    function reducerAddRestaurant(storeName, storeCategory, storeAddress) {
매개변수가 2개 이상인 경우, [RORO 패턴](https://www.freecodecamp.org/news/elegant-patterns-in-modern-javascript-roro-be01e7669cbd/)을 한번 적용시켜보세요!ㅎㅎ

2022-11-06 11:48 UTC, daadaadaah commented on src/Form.test.jsx
> +  });
view를 담당하는 컴포넌트는 handleXX 등이 호출되는 정도만 알 수 있어요! 그에 맞게 테스트 이름을 바꿔줍시당!ㅎㅎ

2022-11-06 18:48 UTC, sejineeee commented
피드백 해주신 부분에 대해서 수정하였습니다!!
배열의 이름을 바꾼 부분을 한번에 커밋했어야 됐는데, 어쩌다 보니 여러번 나뉘어 커밋하게 되었습니다ㅎㅎㅎ
의도가 드러나는 변수명으로 바꾸는 부분은 `nameAttribute`로 해야 되나 아니면 `placeholderName`, `targetName` 등 어떤 변수명으로 할까 고민하다가 name으로 바꾸었습니다. 어떠한 변수명이 가장 적절할지 잘 모르겠어요 ㅎㅎㅎ

이번 두번째 과제는 너무 늦게 내서 많은 피드백을 받지 못해서 너무 아쉬워요 😭
새로 시작하는 주에 있는  과제도 열심히 하도록 해보겠습니다!! 이번 한 주도 감사했습니다! 😁

2022-11-07 04:25 UTC, daadaadaah approved these changes
이번주도 수고 많으셨어요!ㅎㅎ
과제2 많은 핑퐁이 오간건 아니지만, 그래도 이제 제법 테스트 코드 작성하는데에 익숙해지신 것 같아서 기분이 좋네용!ㅎㅎ남은 기간 동안도 같이 화이팅해봐요👊

2022-11-07 04:25 UTC, daadaadaah commented on fixtures/restaurantLists.js
> +const restaurantLists = [
ㅎㅎㅎ저의 의도는 `restaurants` 였어요! 변수명 길어지면 오타 확률이 올라가서 저는 의도는 전달되는 한에서 짧게 지으려고 합니다!ㅎㅎ

2022-11-07 05:27 UTC, sejineeee commented on fixtures/restaurantLists.js
> +const restaurantLists = [
아앗! 맞아요... 변수명에서 오타가 많이 나더라고요ㅠㅠ 감사합니다!! 😆

2022-11-07 13:01 UTC, merged