"레스토랑 정보 확인 및 예약 시스템 구축하기" 제출
CodeSoom/react-week4-assignment-2 pull request #15
Opened 2020-07-02 02:15 UTC by anpaul0615

5주차 과제를 진행하려고보니, 4주차 과제 2번을 기반으로 기능을 추가하는 방식이더군요..ㅠㅠ

많이 늦었지만 그래도 일단은 제출하는게 맞다고 생각해서 PR 드립니다.

2020-07-02 02:18 UTC, anpaul0615 commented
우선은 App 컴포넌트만 구현했습니다.
오늘 저녁까지 하위 컴포넌트/컨테이너 구현해서 커밋 올리겠습니다.

2020-07-02 11:58 UTC, hannut91 requested changes

2020-07-02 11:58 UTC, hannut91 commented on src/App.jsx
> +  }
비슷한 모양이 계속 반복되는 것을 발견하신다면 중복을 제거해야한다는 신호로 받아들이시면 좋습니다.

2020-07-02 11:58 UTC, hannut91 commented on src/App.jsx
>  export default function App() {
`App`이 많은 역할을 하고 있네요 컴포넌트로 관심사를 분리하면 좋을 것 같아요

2020-07-02 11:58 UTC, hannut91 commented on src/App.test.jsx
> +    });
테스트가 복잡해서 이해하기 어려워요. 좀 단순하게 만들수 있을까요? `newRestaurant`에서 `new`가 의미하는바가 무엇인지 잘 모르겠어요

2020-07-02 11:58 UTC, hannut91 commented on src/App.test.jsx
> +      const newRestaurant = RESTAURANTS[0];
중복되어 사용되고 있어요. 중복을 제거하는건 어떨까요?

2020-07-02 11:58 UTC, hannut91 commented on src/App.test.jsx
> +      const [nameInputBox, categoryInputBox, addressInputBox] = inputBoxes;
`inputBoxes`가 코드를 이해하는데 도움이 되지 않는 것 같아요. 오히려 없는게 더 이해하기 좋을 것 같습니다.

```js
const [nameInputBox, categoryInputBox, addressInputBox] = getAllByRole('textbox');
```

See also
  - https://refactoring.com/catalog/inlineVariable.html
  - https://github.com/hannut91/refactoring-practice/blob/master/6.4-inline-variable/answer/app.js

2020-07-02 11:58 UTC, hannut91 commented on src/App.test.jsx
> +      fireEvent.click(button);
여기도 `getByRole('button')`에서 이미 button을 충분히 설명하고 있으므로 inline variable 리팩터링을 해도 괜찮을 것 같아요

```js
fireEvent.click(getByRole('button'));
```

2020-07-02 11:58 UTC, hannut91 commented on src/stores/reducer.test.js
> +  });
테스트가 복잡해보여요. `it`안에는 Given When Then에서 When과 Then만 있어야 해요.

```js
describe('updateRestaurantInfo', () => {
  const previousState = undefined;
  const name = '레스토랑 이름';
  const address = '레스토랑 주소';
  const category = '레스토랑 카테고리';

  it('changes restaurant-name-property', () => {
    const state = reducer(previousState, updateRestaurantName(name));

    expect(state.restaurant.name).toBe(name);
  });
  it('changes restaurant-category-property', () => {
    const state = reducer(previousState, updateRestaurantCategory(category));

    expect(state.restaurant.category).toBe(category);
  });
  it('changes restaurant-address-property', () => {
    const state = reducer(previousState, updateRestaurantAddress(address));
    
    expect(state.restaurant.address).toBe(address);
  });
});
```

2020-07-02 12:20 UTC, anpaul0615 commented on src/App.jsx
> +  }
레스토랑 입력에 대한 액션생성자 함수를 updateRestaurantInfo 로 통합했습니다.

2020-07-02 12:30 UTC, anpaul0615 commented on src/App.test.jsx
> +      const [nameInputBox, categoryInputBox, addressInputBox] = inputBoxes;
입력박스 3개 표출을 확인하기 위한 테스트가 `it('input restaurant-info', () => {});` 에 섞여있었던것같습니다.

`inputBoxes` 를 확인하는 테스트는 `it('display restaurant-info input-boxes ', () => {});` 로 분리하고,
항목 입력 테스트에서의 엘리먼트쿼리를 더 간결하게 수정했습니다.

2020-07-02 12:57 UTC, anpaul0615 commented on src/App.test.jsx
> +      const newRestaurant = RESTAURANTS[0];
각 테스트별로 렌더링을 독립적으로 보장하기위해 `it` 최상단에서 `renderComponent` 를 실행하도록 했습니다.

그리고 개인적으로는 `Given` 은` it` 내부에 있는게 더 쉽게 읽히는것 같은데 어떻게 생각하시는지요?

2020-07-02 12:57 UTC, anpaul0615 commented on src/App.test.jsx
> +      const newRestaurant = RESTAURANTS[0];
그리고 `newRestaurant` 이라는 변수명이 잘 안와닿아서 `restaurantInfo` 로 변경했습니다.

2020-07-02 13:00 UTC, anpaul0615 commented on src/App.test.jsx
> +    });
`getAllByRole('textbox').forEach` 로 입력 관련 테스트를 좀더 간결하게 수정했습니다.

`newRestaurant` 이라는 변수명은 `restaurantInfo` 로 변경했습니다.

2020-07-02 13:00 UTC, anpaul0615 commented on src/App.jsx
>  export default function App() {
관심사대로 컴포넌트를 분리해보겠습니다.

2020-07-02 13:04 UTC, anpaul0615 commented on src/App.test.jsx
> +      fireEvent.click(button);
오 좋습니다.
한번만 참조되는 변수는 inline variable 로 처리하는게 좋을것같습니다.

2020-07-02 13:06 UTC, anpaul0615 commented on src/App.test.jsx
> +      const newRestaurant = RESTAURANTS[0];
> 그리고 개인적으로는 Given 은 it 내부에 있는게 더 쉽게 읽히는것 같은데 어떻게 생각하시는지요?

`it` 안에는 When과 Then만 있어야 하는지 몰랐습니다.
Given 을 `beforeEach`, `beforeAll` 로 빼보겠습니다.

2020-07-02 13:15 UTC, anpaul0615 commented on src/stores/reducer.test.js
> +  });
`it` 안에는 When과 Then만 있어야 하는지 몰랐습니다.
`Given` 을 `it` 바깥으로 빼보겠습니다.

2020-07-03 02:02 UTC, hannut91 requested changes
변수나 함수 이름에 info는 없는게 좋을 것 같아요. 이해하는데 도움이 되지 않습니다.

2020-07-03 02:02 UTC, hannut91 commented on src/App.test.jsx
> +    });
`infoProperty`가 오히려 코드를 읽는데 방해되는 것 같아요. 그리고 `info`는 아무런 의미가 없는 텍스트라서 없어도 무방해요

```js
getAllByRole('textbox').forEach((inputBox) => {
  const value = restaurant[inputBox.name];
  fireEvent.change(inputBox, { target: { value } });

  expect(dispatch).toBeCalledWith(updateRestaurantInfo(inputBox.name, value));
});
```

2020-07-03 02:02 UTC, hannut91 commented on src/stores/reducer.test.js
> +          restaurant: undefined,
이건 없어도 될 것 같아요

2020-07-03 02:02 UTC, hannut91 commented on src/stores/reducer.test.js
> +  });
이렇게 하면 중복을 제거할 수 있습니다.

```js
describe('updateRestaurant', () => {
  const restaurant = {
    name: 'name',
    category: 'category',
    address: 'address',
  };

  it('updates restaurant property', () => {
    Object.entries(restaurant).forEach(([name, value]) => {
      const state = reducer(undefined, updateRestaurantInfo(name, value));
    
      expect(state.restaurant[name]).toBe(value);
    });
  });
});
```

2020-07-04 08:40 UTC, anpaul0615 commented on src/App.test.jsx
> +    });
전반적으로 `info` 를 제거했습니다. 
`infoProperty`, `infoValue` 를 `propertyName`, `propertyValue` 로 변경했습니다.

2020-07-04 08:48 UTC, anpaul0615 commented on src/stores/reducer.test.js
> +          restaurant: undefined,
왜 그렇게 생각하시나요?

위 테스트는 reducer 에서 좀 엄격하게 가딩을 걸어놓은걸 테스트하기위함인데요.

```
    if (!restaurant) {
      return previousState;
    }
    if (!restaurant.name || !restaurant.category || !restaurant.address) {
      return previousState;
    }
```

속성을 객체로 묶어서 파라미터로 전달할때는 묶음객체 자체도 유효한지 검증해야할것같아요.

2020-07-04 08:53 UTC, anpaul0615 commented on src/stores/reducer.test.js
> +  });
`Object.entries` 를 사용해서 중복제거하는 방법에 대해서는 매우 동의합니다.

그런데 테스트는 코드사용방법을 명세하기도 한다는 관점으로 봤을때, 중복이 발생하더라도 개별로 작성해주는게 나중에 읽었을때 더 잘 읽히지 않을까요?

2020-07-04 08:53 UTC, anpaul0615 commented on src/stores/reducer.test.js
> +  });
우선은 중복제거하는 방향으로 수정했습니다.

2020-07-04 09:54 UTC, hannut91 commented on src/stores/reducer.test.js
> +          restaurant: undefined,
없어도 테스트 영향을 주지 않아서 삭제해도 될 것 같은데 삭제안하셔도 됩니다

2020-07-04 09:55 UTC, hannut91 commented on src/stores/reducer.test.js
> +  });
제가 생각하기엔 간결한게 더 이해가 잘 될 것 같아요

2020-07-04 14:15 UTC, anpaul0615 commented on src/stores/reducer.test.js
> +  });
그렇군요~ 잘알겠습니다!

2020-07-13 14:01 UTC, hannut91 commented
고생하셨어요. ㅎㅎㅎ 과제를 놓쳤더라도 다시 따라오셔서 과제를 완수하신 모습이 인상적입니다. 😀

2020-07-13 14:02 UTC, merged

2020-07-14 08:21 UTC, anpaul0615 commented
윤석님이 옆에서 도와주셔서 끝까지 할수있었습니다..! 정말 감사합니다^^