[Week4][Davidyang2149] Add Restaurant info and reservation system - 구현 진행 중
CodeSoom/react-week4-assignment-2 pull request #16
Opened 2020-10-12 13:06 UTC by DavidYang2149

# 4강 리덕스 - 4주 차 과제 2
## 기능 구현
- [ ] TDD로 기능 구현
- [ ] 레스토랑 목록 보기 기능
- [ ] 레스토랑 추가 기능
- [ ] 모든 컴포넌트에 테스트를 작성해주세요. 그리고 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해주세요.

## 제한 조건
- [ ] 모든 기능은 TDD로 구현합니다. 컴포넌트와 reducer에 대한 테스트가 존재해야 합니다. 먼저 테스트를 추가하고 commit 한 뒤 실제 기능을 추가하고 commit합니다. commit 메시지 로그는 아래와 같이 남아야 합니다.
```sh
Restaurant에 대한 테스트를 추가한다
Restaurant을 구현한다
Restaurant를 리팩토링한다
```
- [ ] if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- [ ] switch는 사용하실 수 없습니다.
- [ ] let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- [ ] 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- [ ] indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

## 요구사항
- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- [ ] 테스트 커버리지 100%를 달성해야 합니다.

## 작업내용 및 질의
- [ ] 구현 작업 진행 중

2020-10-17 03:36 UTC, Kihyun92 commented
과제는 잘 진행하고 계신가요?? 혹시 잘 안되는 부분이 있다면 말씀해주세요~☺️

2020-10-17 22:49 UTC, Kihyun92 requested changes
남겨주신 커밋들을 보니 이번 과제의 요구사항에 맞게 잘 해주신 것 같아요! 👍 

나머지 action들도 어떻게 추가하실지 기대가 되네요 :)

2020-10-17 22:49 UTC, Kihyun92 commented on src/ListItem.jsx
> +export default function ListItem({ restaurant: { name, category, address } }) {
컴포넌트 네임이 `Item` `Restaurants`는 어떤가요?

2020-10-17 22:49 UTC, Kihyun92 commented on src/Form.jsx
> +    <p>
`div` 태그로 감싸주는게 더 어울릴 것 같아요!

- p tag https://developer.mozilla.org/ko/docs/Web/HTML/Element/p
- div tag https://developer.mozilla.org/ko/docs/Web/HTML/Element/div

2020-10-17 22:49 UTC, Kihyun92 commented on src/Form.test.jsx
> +    ));
`it` 밖에서 선언해주는게 좋겠네요~

2020-10-17 22:49 UTC, Kihyun92 commented on src/Form.jsx
> +        />
컴포넌트의 재사용성을 고려해보셨네요~ 좋습니다!😁
다만 이 경우에는 `input` 태그를 바로 사용하는 것과 어떤 차이가 있을까요?
재사용 가능한 공통 컴포넌트로 처리하는 경우는 공통적인 비즈니스 로직이나 복잡한 로직을 가지고 있는 경우에 좋을 것 같아요 :)

2020-10-18 05:45 UTC, DavidYang2149 commented on src/ListItem.jsx
> +export default function ListItem({ restaurant: { name, category, address } }) {
사실 `Item`과 `ListTem` 중에서 고민이었습니다. 다시 `Item`으로 수정하겠습니다.

2020-10-18 05:53 UTC, DavidYang2149 commented on src/Form.jsx
> +    <p>
고민되었던 부분인데 정확히 짚어주셔서 감사합니다!

2020-10-18 06:03 UTC, DavidYang2149 commented on src/Form.test.jsx
> +    ));
네 다른 테스트 케이스도 모두 수정하겠습니다!

2020-10-18 14:22 UTC, Kihyun92 approved these changes
고생하셨습니다~ 👍  `Red-Green-Refactoring` 사이클을 지키며 과제를 해보신것 같아요
과제풀이 영상을 통해서 아샬님은 어떤식으로 Redux를 접목해서 TDD를 진행하시는지 봐보시면 좋을 것 같아요~
이번 과제를 통해서 무엇을 배우셨나요? 아쉬웠던 부분이나 더 시도해보고 싶은게 있나요? :)

2020-10-18 14:27 UTC, DavidYang2149 commented
4주 차 주간회고를 작성해 보았습니다.
https://davidyang2149.dev/codesoom/%EC%BD%94%EB%93%9C%EC%88%A8-4%EC%A3%BC-%EC%B0%A8-%EC%A3%BC%EA%B0%84%ED%9A%8C%EA%B3%A0/

2020-10-19 13:30 UTC, merged