과제2 : 레스토랑 정보 확인 및 예약 시스템 구축하기 - ListContainer까지 완료
CodeSoom/react-week4-assignment-2 pull request #17
Opened 2020-10-13 14:05 UTC by bbhye1

### **과제 목표**

- TDD로 기능 구현
- 레스토랑 목록 보기 기능
- 레스토랑 추가 기능

### **제한 조건**

- 모든 기능은 TDD로 구현합니다. 컴포넌트와 reducer에 대한 테스트가 존재해야 합니다. 먼저 테스트를 추가하고 commit 한 뒤 실제 기능을 추가하고 commit합니다. commit 메시지 로그는 아래와 같이 남아야 합니다.
- if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
- switch는 사용하실 수 없습니다.
- let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
- 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
- indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

### **진행 상황 ** 

TDD 사이클에 맞춰서 작성중입니다. 
현재 작은 부분부터 시작하자고 생각해서 App -> List -> ListContainer 순으로 작성했습니다.

2020-10-14 14:12 UTC, bbhye1 commented
차근차근 잘근잘근 코드를 작성중입니다. 진짜 커밋 100개 채울수 있을 것 같아요 ㅎㅎ.
만들고 있는 앱이 전체적으로 어떻게 구현되는지를 고려하며 제일 작은 단위 컴포넌트부터 만들어 가니 과제 1처럼 만들어진 앱을 리팩토링 하는 것과는 다른 어려움들이 느껴지네요.  state에 저장하는 데이터 형식이라던가 함수명, 변수명들이 계속 바뀔거 같습니다.  일단 차근차근 완성시켜보겠습니다.

2020-10-14 17:00 UTC, hannut91 requested changes

2020-10-14 17:00 UTC, hannut91 commented on src/Form.jsx
> +      ))}
`input`이 계속 반복적으로 사용되고 있는데 구조 분해 할당을 사용해서 간략화시킬 수 있을까요?

2020-10-14 17:00 UTC, hannut91 commented on src/ListContainer.test.jsx
> +  });
여기도 스터디 때 배운 구조 분해 할당을 사용하면 간략화 시킬 수 있을거에요

2020-10-14 17:00 UTC, hannut91 commented on src/Form.test.jsx
> +      expect(getByPlaceholderText(input.placehoder)).toHaveDisplayValue(input.value);
`getByPlaceholderText(input.placehoder)`이 부분이 중복되는 것 같아요. 무언가가 반복적으로 보인다면 리팩터링해야 할 신호로 보시면 좋아요

2020-10-15 14:36 UTC, bbhye1 commented
알고리즘과 자료구조에 대한 갈증을 느끼는 하루였습니다 ㅎㅎ...  제가 처음 설정한 inputs의 구조때문에 어떻게 inputs 변경해야하나 다른 데이터 형태로 해야하나 고민을 많이 하다가 처음 선택한 방법으로 계속 진행했습니다. 

FormContainer 컴포넌트까지 App 컴포넌트에 연결한 부분까지 완성했습니다. 이렇게 처음부터 TDD로 짠게 처음이라 코드들이 거친 느낌이 나는게 느껴집니다. 이제 다시 처음부터 천천히 보면서 부족한 테스트도 추가하고 계속 리팩토링 해나갈 예정입니다!

2020-10-16 07:32 UTC, hannut91 requested changes

2020-10-16 07:32 UTC, hannut91 commented on src/Form.test.jsx
> +  ];
`inputs`라는 테스트용 데이터가 테스트 파일들 사이에서 계속 반복되어서 사용되는 것 같아요. 테스트용 데이터를 fixture라고 부르는데 별도로 관리해서 테스트하는데 사용하면 좋을 것 같아요

2020-10-16 07:32 UTC, hannut91 commented on src/Form.test.jsx
> +    fireEvent.click(getByText('등록'));
제가 생각하기에는 등록이 있는지 두 번 확인하는 것 같아서 위의 단정문은 안해도 될 것 같다고 생각하는데 어떻게 생각하시나요?

2020-10-16 07:32 UTC, hannut91 commented on src/FormContainer.test.jsx
> +  ];
이걸 반복적으로 다른곳에서도 사용하는 것 같아요. 무엇인가가 반복된다면 리팩터링의 신호로 보시면 좋습니다

2020-10-16 07:32 UTC, hannut91 commented on src/FormContainer.test.jsx
> +});
beforeEach는 `describe`안에 들어가는게 좋을 것 같아요

2020-10-16 07:32 UTC, hannut91 commented on src/FormContainer.test.jsx
> +    }));
얘도 여깄는게 아니라 위의 beforeEach안에 들어가는게 좋을 것 같아요. 테스트끼리 서로 의존성이 없도록 초기화해주어야 하기 때문이에요

2020-10-16 07:32 UTC, hannut91 commented on src/Input.jsx
> +      onChange={(e) => onChange(placeholderText, e.target.value)}
placeholder 텍스트를 key로 사용하고 계신 것 같아요. 만약에 placeholder가 `레스토랑 이름을 입력해주세요.`가 되면 어떻게 될까요

2020-10-16 07:32 UTC, hannut91 commented on src/ListContainer.test.jsx
> +  ];
테스트에서 계속 반복적으로 사용되는 데이터가 있는 것 같아요. 이 데이터를 정의하고 여러곳에서 재사용하면 어떨까요? 테스트용 데이터를 fixture라고 부릅니다 ㅎㅎ fixtures 폴더아래에 정리하면 좋을 것 같아요

2020-10-16 07:57 UTC, bbhye1 commented on src/Input.jsx
> +      onChange={(e) => onChange(placeholderText, e.target.value)}
placeholder가 아닌 변화가능성이 적은 name으로 key를 설정해주는 것이 더 좋겠네요!

2020-10-16 14:03 UTC, bbhye1 commented
열심히 리팩토링했습니다. 부족한 부분이 있으면 체크 부탁드립니다!

2020-10-17 02:08 UTC, hannut91 approved these changes
사소한 커멘트 말고는 더이상 커멘트 드릴게 없네요 ㅎㅎ 어푸르브 합니다!

2020-10-17 02:08 UTC, hannut91 commented on __fixtuers__/fixture.js
> +  inputInfos: [
`info`라는 것은 아무런 의미를 드러내지 않는 것 같아요. `inputs`는 어떨까요?

2020-10-17 02:08 UTC, hannut91 commented on src/Form.test.jsx
> +const handleClickAddRestaurant = jest.fn();
테스트에 직접적으로 사용되는 변수들은 `describe`안에 있는건 어떨까요?

2020-10-17 02:08 UTC, hannut91 commented on src/FormContainer.test.jsx
> +  }
테스트에 사용되는 변수나 함수들을 위에 선언하고, 테스트 생명주기에 관련된 코드들은 아래에 정렬하는 건 어떨까요? 지금은 섞인 것 같아요.

```js
const { inputInfos } = fixture;

function renderFormContainer() {}

beforeEach(() => {});
```

2020-10-17 02:08 UTC, hannut91 commented on src/reducer.js
> +    };
inputInfos가 배열이다 보니 0, 1, 2가 의미하는 바가 무엇인지 파악하기 어려운 것 같아요.
구조 분해 할당으로 표현해주면 어떨까요?

```js
const [name, category, address] = inputInfos;

{
  name: name.value,
  category: category.value,
  address: address.value,
}
```

2020-10-17 16:28 UTC, hannut91 commented
더 자세한 내용은 과제 풀이 영상을 통해서 복습해보시면 좋을 것 같아요. 특히 코드를 작성할 때 어떤 순서로 어떤 기준으로 코드를 작성하는지 눈여겨 보면 좋을 것 같습니다

이번 과제를 통해서 무엇을 배우셨나요? 다음 과제에서 더 시도해보고 싶으신게 있으신가요?

2020-10-18 13:05 UTC, hannut91 commented
슬랙 채널에 회고를 남겨주셔서 머지합니다!

2020-10-18 13:05 UTC, merged