week4-2 restaurant app
CodeSoom/react-week4-assignment-2 pull request #18
Opened 2020-10-14 08:49 UTC by JamieShin0201

안녕하세요^^

1. red - green - refactor 순서로 App, List, ListContainer를 구현하였습니다.

계속해서 Input 부분도 구현하겠습니다.

감사합니다^^

2020-10-14 15:55 UTC, hannut91 requested changes
테스트를 잘 작성해 주셨네요 ㅎㅎ 테스트를 작성하시고 구현하실 때는 항상 하나의 테스트 하나의 작업에만 집중해야 합니다 ㅎㅎ 이를 생각하면서 과제를 진행해보시면 좋을 것 같아요.

2020-10-14 15:55 UTC, hannut91 commented on src/List.jsx
> +      ))}
`restaurant`이라는 이름이 계속 반복되고 있어서 복잡해지는 것 같아요. 구조 분해 할당(Destructuring) 이용해서 중복을 제거하는건 어떨까요?

See also
  - https://ko.javascript.info/destructuring-assignment
  - https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2020-10-14 15:55 UTC, hannut91 commented on src/List.test.jsx
> +  });
여기도 동일하게 구조 분해 할당(Destructuring)을 이용해서 반복되는 `restaurant`를 없애면 좋을 것 같아요

2020-10-15 08:32 UTC, JamieShin0201 commented
안녕하세요^^

계속해서 구현중인데.. TDD를 지키면서 해야하는데 자꾸 순서가 뒤죽박죽 될때가 있네요..

2020-10-16 06:31 UTC, hannut91 requested changes

2020-10-16 06:31 UTC, hannut91 commented on src/FormContainer.jsx
> +    dispatch(updateRestaurant(event.target.placeholder, event.target.value));
placeholder대신에 `name`이라는 속성을 이용하는건 어떨까요? placeholder는 데이터랑 상관없이 변경될 수 있는 것 같아요. 예를들어 placeholder가 `레스토랑 이름을 입력해주세요?` 라던가 `레스토랑 이름 ex) 하남돼지집`이면 안되겟죠?

2020-10-16 06:31 UTC, hannut91 commented on src/FormContainer.test.jsx
> +  }));
상태를 mocking하는 것은 테스트 케이스마다 달라질 수 있고, 테스트가 실행될 때마다 초기화가 되어야 합니다. 그래야 테스트간의 의존성을 제거할 수 있어요. 따라서 다음과 같이 작성하는게 좋을 것 같아요.

```js
beforeEach(() => {
  useDispatch.mockImplementation(() => dispatch);

  useSelector.mockImplementation((selector) => selector({
    restaurant: {
      name: '마녀주방',
      classification: '한식',
      location: '서울시 강남구',
    },
  }));
});

beforeEach(() => {
  jest.clearAllMocks();
});
```

See also
  - https://jestjs.io/docs/en/setup-teardown
  - https://jestjs.io/docs/en/jest-object#jestclearallmocks

2020-10-16 06:31 UTC, hannut91 commented on src/FormContainer.test.jsx
> +  describe('handleChangeRestaurant', () => {
`handleChangeRestaurant`는 테스트에서 함수 이름인 것 같아요. 그것 보다는 무엇을 테스트하는지 더 명확하게 작성해주는건 어떨까요? 예를들면 `레스토랑 이름을 변경하면`이라는 문맥이 들어가면 어떨까요?

2020-10-16 06:31 UTC, hannut91 commented on src/reducer.js
> +};
실제 placeholder이름을 매핑해주셨군요. placeholder를 키로 쓰기 보다는 `name`같은 걸 추가해서 문제를 해결할 수도 있을거에요.

2020-10-16 06:31 UTC, hannut91 commented on src/reducer.test.js
> +      const key = '';
`valid`, `invalid`보다 empty를 쓰는건 어떨까요?

2020-10-16 09:05 UTC, JamieShin0201 commented
안녕하세요 ㅎ.ㅎ

1. 피드백 주신부분 확인하고 전반적으로 수정하였습니다.

계속 코드 살펴보면서 리팩토링 진행하겠습니다.

감사합니다^^

2020-10-17 04:46 UTC, hannut91 requested changes

2020-10-17 04:46 UTC, hannut91 commented on src/reducer.test.js
> +      });
`returns initial state`는 어떨까요?

2020-10-17 04:46 UTC, hannut91 commented on src/reducer.js
> +    }
모든 값들이 존재해야 레스토랑 목록에 추가하는 것 같아요. 이런식으로 확인하는건 너무 복잡해보일까요?

```js
if (Object.values(restaurant).some((it) => !it)) {
  return state;
}
```

See also
  - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2020-10-17 04:46 UTC, hannut91 commented on src/List.test.jsx
> +});
레스토랑 목록이 온전하게 있을 때 테스트 케이스를 잘 만들어주신 것 같아요. 우리가 원하는 기능이고 아무런 예외가 없이 올바르게 동작하는 경우를 `Happy path`라고 해요. 다른 예외의 경우는 생각하지 않고 모든게 잘 돌아갈 때만 먼저 생각해서 구현을 하는게 좋습니다. 처음부터 너무 많은 것을 생각하다보면 압도되어서 시작도 못하는 경우가 있어요. 지금 잘해주신 것 같아요. 그 다음에 혹시 레스토랑 목록이 없으면 어떻게 되지? 같은 질문을 던지며 테스트를 추가해서 추가적인 구현을 하여 더 의도를 드러낼 수 있어요. 

이 테스트를 읽는 사람은 레스토랑 목록이 있으면 잘 출력된다라는 사실은 알 수 있지만, 비어있을 경우에는 정의가 되어 있지 않아요. 혹시 비어있을 경우에 어떻게 된다는 것을 정의하고 싶으시다면 테스트를 추가적으로 작성해주시면 됩니다.

2020-10-18 04:07 UTC, JamieShin0201 commented
안녕하세요~! ^^

조금 늦었지만 리뷰받은내용 확인하고 수정하여 올립니다.

감사합니다 ㅎ.ㅎ

2020-10-18 04:07 UTC, JamieShin0201 commented on src/reducer.js
> +    }
훨씬 깔끔하네요 ㅎ.ㅎ 감사합니다 ㅎㅎ

2020-10-18 13:15 UTC, hannut91 commented on src/reducer.js
> +    }
더 복잡해보이는 것 같기두 하구요 ㅎㅎ

2020-10-18 13:22 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 과제풀이 영상을 보면서 다시 한 번 복습해보시면 좋을 것 같아요. 특히 코드를 작성하는 과정에 더 눈여겨 보시면 좋을 것 같습니다. 

코멘트 남겨드린 fixture도 강의에서 계속 나오므로 학습해보시면 좋을 것 같아요.

이번 과제를 통해 무엇을 배우셨나요? 다음에 더 시도해보고 싶은 것은 무엇인가요?

2020-10-18 13:22 UTC, hannut91 commented on src/ListContainer.test.jsx
> +    ],
테스트에서 사용되는 데이터들이 반복해서 사용되고 있습니다. 테스트용 데이터를 미리 만들어놓고 사용하여 중복을 줄일 수 있고, 테스트의 복잡성을 낮출 수 있습니다. 또 복잡한 계산같은 경우 믿고 이미 테스트가 된 데이터들을 저장해놓을 수 있습니다. 이러한 테스트용 데이터를 fixture라고 부릅니다. fixtures라는 폴더를 하나 만들고 여기에 테스트용 데이터들을 모아놓고 가져다가 사용하는건 어떨까요?

2020-10-20 13:50 UTC, hannut91 commented
슬랙 채널에 회고를 남겨주셔서 머지합니다!

2020-10-20 13:50 UTC, merged