Create a system for Restaurants
CodeSoom/react-week4-assignment-2 pull request #2
Opened 2020-06-26 21:28 UTC by daadaadaah

일단 작업한 것까지만 올렸어요~

이후 컴포넌트 분리 작업 진행할 예정입니다.

중간에 망한 것 같아서 든 생각이 

미리 컴포넌트 정의 및 분리부터 하고 시작했어야 했나 싶네요....

2020-06-27 09:04 UTC, daadaadaah commented
PR 다시 날릴게요~ㅎㅎ

2020-06-27 21:51 UTC, daadaadaah commented
새로운 작업을 시작하는거보다 기존 작업 리팩토링 하는 방향으로 과제를 진행하는게 더 나을 것 같아서 재오픈했어요

2020-06-28 03:20 UTC, hannut91 requested changes
테스트를 작성하는데 많은 노력을 하신게 보이네요 ㅎㅎ `App`컴포넌트에서 컴포넌트로 관심사를 분리하면 좋을 것 같아요

2020-06-28 03:20 UTC, hannut91 commented on src/reducer.test.js
> +  describe('without parameter', () => {
이전 상태가 없는 것과 액션이 없는 것 따로 테스트를 작성하면 좋을 것 같아요. 그러면 의미가 더 드러날 것 같아요. 파라미터가 없는데 왜 없는지 잘 모르겠어요

2020-06-28 03:20 UTC, hannut91 commented on src/reducer.test.js
> +    const newState = reducer();
테스트의 `when`에 해당하는 것은 여기에 작성되면 안돼요. `it`안으로 넣어주세요.

2020-06-28 03:20 UTC, hannut91 commented on src/reducer.test.js
> +    it('clear New restaurant', () => {
여기서 `New`가 의미하는 바가 무엇인가요?

2020-06-28 03:20 UTC, hannut91 commented on src/reducer.test.js
> +        restaurantAddress: 'New restaurantAddress',
`restaurant`라는 이름이 계속 반복되고 있는 것 같아요. 이름, 종류 그리고 주소를 `restaurant`이라고 봐도 괜찮겠죠?

2020-06-28 12:30 UTC, daadaadaah commented on src/reducer.test.js
> +    it('clear New restaurant', () => {
지워야겠네요ㅎㅎ

2020-06-28 12:51 UTC, daadaadaah commented on src/reducer.test.js
> +    it('clear New restaurant', () => {
수정해야겠네요~

2020-06-28 14:20 UTC, hannut91 approved these changes
TDD에 대한 고민의 흔적이 많이 보이네요 ㅎㅎ 인출연습도 많이 하신 것 같아요. 다음 과제에서는 중복된 것을 어떻게 하면 없앨 수 있을까? 그리고 기능을 점진적으로 단계적으로 푸는 연습을 하면 좋을 것 같아요. ㅎㅎ 고생하셨습니다.

2020-06-28 14:20 UTC, hannut91 commented on src/App.jsx
> +    restaurantAddress: state.restaurantAddress,
`restaurant`가 계속해서 쓰이는 것 같아요. `restaurant`라는 객체로 만들어주면 어떨까요?

2020-06-28 14:20 UTC, hannut91 commented on src/App.jsx
>  export default function App() {
`App`이 너무 많은 일을 하고 있는 것 같아요 컴포넌트로 분리해주세요.

2020-06-28 14:20 UTC, hannut91 commented on src/App.test.jsx
> +  describe('Initial Rendering', () => {
`Initial Rendering`이 없어도 이 테스트를 이해하는데 어려움이 없을 것 같아요

2020-06-28 14:20 UTC, hannut91 commented on src/App.test.jsx
> +        expect(getByText(/주소3/i)).toBeInTheDocument();
무언가 계속 반복되고 있는 모습인 것 같아요. 중복되는 것을 없앨 수 있을까요?

2020-06-28 14:20 UTC, hannut91 commented on src/App.test.jsx
> +        }));
이것들도 계속 반복되서 사용되고 있어요. 중복을 없애주면 더 좋을 것 같아요.

2020-06-28 14:20 UTC, hannut91 commented on src/App.test.jsx
> +      it('shows a new restaurant name in input', () => {
`User Interaction`은 너무 포괄적인 이름 같아요. 

```js
describe('Change restaurant forms', () => {
  it('dispatch change action', () => {
    ...
  });
});

```

2020-06-28 14:20 UTC, hannut91 commented on src/reducer.js
> +  }
비슷한 모양이 계속 반복되는 것 같아요. 어떻게 하면 없앨 수 있을까요? 각각 무엇이 달라지나요?

2020-06-28 14:20 UTC, hannut91 commented on src/reducer.js
> +  }
`if`나 `switch`없이 object를 이용해서 문제를 해결하면 좋을 것 같아요.

2020-06-28 14:22 UTC, hannut91 commented
이번 과제에서는 무엇을 배우셨나요? 다음 과제에서 더 시도해보면 좋을 것은 무엇이 있을까요?

2020-06-29 04:16 UTC, merged