레스토랑 정보 확인 및 예약 시스템 구축하기 - 진행중
CodeSoom/react-week4-assignment-2 pull request #21
Opened 2020-10-15 11:21 UTC by dongakim

2020-10-17 13:04 UTC, wholemann commented on src/App.jsx
> +      <InputContainer />
```suggestion
      <RestaurantsContainer />
      <RestaurantCreateContainer />
```

2020-10-17 13:10 UTC, wholemann commented on src/Input.test.jsx
> +  describe('renders', () => {
상황을 나누고 싶다면 context를 사용하시고

굳이 describe로 나눌 필요는 없어 보입니다.

it('renders placeholer text', ...)

it('listens change event', ...)

정도로 구분할 수 있겠군요.

2020-10-17 13:11 UTC, wholemann commented on src/reducer.js
> +  }
```suggestion
  if (action.type === 'addRestaurant') {
    const { newId, restaurants, restaurant } = state;

    return {
      ...state,
      newId: newId + 1,
      restaurants: [...restaurants, { ...restaurant, id: newId }],
      restaurant: initialRestaurant,
    };
  }
```

2020-10-17 13:12 UTC, wholemann commented on src/reducer.js
> +  }
얘네 셋은 나눌 필요가 없습니다. 중복이에요. changeRestaurantField 죠.

2020-10-17 13:13 UTC, wholemann commented on src/InputContainer.test.jsx
> +    it('3 inputs', () => {
이건 뭘 의미하나요?

describe가 의미하는 게 전혀 없습니다. describe('renders', ...) 는 그냥 문장으로 읽어도 아무 의미가 없습니다.

2020-10-17 13:18 UTC, wholemann commented on src/reducer.test.js
> +  describe(CHANGE_RESTAURANT_INPUT.NAME, () => {
놀랍게도 3개의 테스트는 아래와 같은 하나의 테스트로 통합이 가능합니다.

```javascript
  describe('changeRestaurantField', () => {
    it('changes restaurant form', () => {
      const initailState = {
        restaurant: {
          name: '이름',
          category: '분류',
          address: '주소',
        },
      };

      const state = reducer(initailState, changeRestaurantField({
        name: 'address',
        value: '서울시 강남구 역삼동',
      }));

      expect(state.restaurant.address).toBe('서울시 강남구 역삼동');
    });
  });
```

2020-10-17 13:20 UTC, wholemann requested changes
성급하고 과도한 추상화, 일반화를 경계하고

의미있는 컴포넌트 이름을 부여하는 걸 먼저 고민해보세요.

정말 광범위하게 재활용될 컴포넌트(Button, TextInputField 등...) 가 아니라면

대부분은 일반화된 이름을 갖지 않습니다.

기본적으로 지금은 중복된 테스트가 많습니다.

이는 명세에 대해서 좀 더 고민하면 해결해볼 수 있죠.

하나 하나 확실히 확인해야될 대상과 아닌 대상을 명확히 구분해보세요.

이건 구현 전에 노트에 적든 어딘가에 기록하면서 명확하게 해볼 필요가 있습니다.

구현에 끌려가면 안 됩니다.

2020-10-18 06:06 UTC, dongakim commented on src/InputContainer.test.jsx
> +    it('3 inputs', () => {
`it('renders 3 inputs',  () => { ... })`
`it('renders 등록 button', () => { ... })`

이런식으로 `renders`가 중복이되서
render와 관련된 테스트를 묶는 용도로 describe를 사용했습니다.

이런 식으로 중복되거나 비슷한 의미의 테스트 묶음을 만드는 방법이 있을까요?

2020-10-18 10:11 UTC, wholemann commented on src/RestaurantCreateContainer.jsx
> +import actions from './actions';
```suggestion
import {
  addRestaurant,
  changeRestaurantField,
} from './actions';
```

action은 뽀개서 가져오는 게 편해요~

2020-10-18 10:12 UTC, wholemann commented on src/RestaurantCreateContainer.test.jsx
> +  useSelector.mockImplementation((selector) => selector({
```suggestion
  const dispatch = jest.fn();
  
  useDispatch.mockImplementation(() => dispatch);
  
  useSelector.mockImplementation((selector) => selector({
```

2020-10-18 10:18 UTC, wholemann commented on src/RestaurantsContainer.jsx
> +export default function ListContainer() {
```suggestion
export default function RestaurantsContainer() {
```

의미를 더 드러내주세요!

2020-10-18 10:21 UTC, wholemann commented on src/InputContainer.test.jsx
> +    it('3 inputs', () => {
it('renders input fields and listens click event') 뭐 이런식도 가능할 거 같네요ㅎㅎ

2020-10-18 10:24 UTC, wholemann reviewed
TDD로 진행하는 게 쉽지 않으셨을텐데 잘 따라와주셨고,
생각보다 더 잘하셔서 솔직히 좀 놀랐습니다ㅎㅎ

아샬님 피드백 영상에서 TDD로 쌓아올려 가는 과정이 나올텐데 통으로 외워보시는 걸 추천드려요.

일종의 조깅처럼 아침에 일어나면 바닥부터 끝까지 TDD로 진행하는 걸 반복하는거죠.

TDD 이건 그냥 수련입니다ㅎㅎ 대단히 고풍스러운 지식 같은게 아니라요.

회고까지 잘 마무리 부탁드려요!

2020-10-18 22:57 UTC, dongakim commented
확실히 TDD 방식으로 하는게 안정감이 더 느껴지네요. 그리고 더 재미있습니다.
물론 명확한 명세를 생각해보고 중복을 없애고 읽기 좋은 테스트를 작성하는 방법에 대해서는 많은 고민이 있지만요.
말씀해주신대로 수련이다 생각하고 처음부터 다시 만들어가는 연습을 꾸준히해보겠습니다.

2021-01-17 12:48 UTC, merged