[4주차] 레스토랑 정보 확인 및 예약 시스템 구축하기
CodeSoom/react-week4-assignment-2 pull request #22
Opened 2020-10-15 11:31 UTC by oceanide2

**진행사항**
- 초기 구현 시작

2020-10-16 16:47 UTC, oceanide2 commented
Input 박스에 글자를 넣을 때 아래와 같은 에러가 발생하는데 이유를 잘 모르겠습니다.
![image](https://user-images.githubusercontent.com/48346657/96285984-a813dc00-101a-11eb-8ff6-71f5874c6348.png)

2020-10-16 18:04 UTC, Kihyun92 commented on src/InputContainer.jsx
> +  }
```suggestion
function handleChange(event) {
    const { target: { name, value } } = event;
    dispatch(updateRestaurant(name, value));
  }
```

말씀하신 에러는 이렇게 하면 해결될 것 같아요~

2020-10-17 04:17 UTC, oceanide2 commented on src/InputContainer.jsx
> +  }
에러를 검색해보니 Input 컴포넌트의 초기값이 설정이 되지 않아서 발생하는 문제처럼 설명들을 하던데, 조언해주신 대로 수정을 해도 warning이 없어지지를 않네요.

2020-10-18 00:41 UTC, Kihyun92 requested changes
말씀하신대로 해당 warning은 초기화가 제대로 되지 않아 발생한 것 같아요~ 뭔가 undefined로 초기화가 되어있을 것 같네요. 각각의 input tag들은 어떤 값을 가져와서 사용하고 업데이트하는지 확인해보시면 해결하실 수 있을 것 같습니다~ 
그리고 초기 실행시에 `restaurants`에 데이터를 초기화 해주는 로직을 추가 해주세요. :)

2020-10-18 00:41 UTC, Kihyun92 commented on src/reducer.js
> +    };
```suggestion
    return {
      ...state,
      restaurant: {
        ...state. restaurant,
        [name]: value,
      },
    };
```

리턴 해주는 restaurant 정보가 잘못된것 같아요~ input 태그에서 사용한 name과 restaurant name이 겹치게 사용되고 있어서 주의해서 작업해주세요~

2020-10-18 00:41 UTC, Kihyun92 commented on src/reducer.js
> +  restaurant: {},
```suggestion
  restaurant: initialRestaurant,
```
initialRestaurant 객체를 하나 추가해서 name, category, address를 관리해주면 좋을 것 같아요~

2020-10-18 14:30 UTC, Kihyun92 commented
혹시 아직 이슈가 해결되지 않았을까요? 빠르게 도움을 못드린것 같아 아쉽네요 ㅠㅠ,,

강의 풀이 꼭 봐보시고 해결해보시면 좋을 것 같아요!

2020-10-19 00:43 UTC, oceanide2 commented
> 혹시 아직 이슈가 해결되지 않았을까요? 빠르게 도움을 못드린것 같아 아쉽네요 ㅠㅠ,,
> 
> 강의 풀이 꼭 봐보시고 해결해보시면 좋을 것 같아요!

제가 능력이 부족해서 제대로 진행하지 못한 것 같습니다. 에러가 발생하는 것도 직접 찾아서 고쳤어야 하는데, 직접 문의 드리게 되어서 죄송합니다. 
이번 주 과제는 시간을 많이 들여서 진행했지만 redux 및 테스트 코드에 대한 이해부족으로 제대로 진행하지 못한 것 같아서 저도 많이 아쉽습니다.
시간을 들여서 익숙해지려고 노력하면 나아지지 않을까라고 생각하며 위안을 얻어보려고 합니다. 도움 주셔서 감사합니다.

2020-10-19 13:34 UTC, Kihyun92 commented
fail 나는 부분 수정해주시면 `approve` 후에 머지 하겠습니다~

2021-01-17 12:48 UTC, merged