Restaurant reservation system
CodeSoom/react-week4-assignment-2 pull request #23
Opened 2020-10-15 12:36 UTC by gringrape

2020-10-16 02:50 UTC, gringrape commented
## 고민한 지점
### restaurant field(name, category, address) 추상화
이번에는 과제를 시작하기 전에 꼭 필요해지는 경우만 추상화를 하기로 결정을 했습니다.
그래서 레스토랑 field 를 각각으로 처리할지 field 라는 하나의 속성으로 처리할지 고민을 했습니다.
다음과 같은 이유 때문에 추상화를 하기로 결정했습니다.

- 개발중인 어플리케이션이라면 field 에 항목이 추가되거나 변경될 가능성이 높다
- 반복적인 코드량이 줄어들어서 무엇을 하는지 잘 파악된다.

아래와 같은 경우는 field 하나로 하려면 reduce 를 사용해서 합쳐주고, 순서도 고려해야 되어서,
정말로 field 가 많지 않은 이상 그대로 해도 변경이 쉬울듯 하여, 추상화해주지 않았습니다.

```html     
<li key={id}>
  {`${name} | ${category} | ${address}`}
</li>
```

2020-10-16 04:48 UTC, wholemann commented
와... 이걸 한번에 다 진행하셨군요 짝짝짝!

한번에 오는 경우가 없어서 제가 자세하게 살피는데 시간이 좀 들겠네요 잠시만 기다려주세요!

2020-10-16 04:49 UTC, wholemann commented
올바른 판단입니다. 중복이 발생될 게 자명하거나 복잡도가 올라갈 때가 아니면 굳이 앞서서 추상화를 할 필요가 없습니다.

테스트를 먼저 작성하면서 테스트하기가 힘들다고 느껴진다면 그게 설계를 개선해야된다는 신호죠.

TDD로 진행하면서 오는 다양한 신호들을 잘 느껴보세요.

2020-10-16 04:50 UTC, wholemann commented
> ## 고민한 지점
> ### restaurant field(name, category, address) 추상화
> 이번에는 과제를 시작하기 전에 꼭 필요해지는 경우만 추상화를 하기로 결정을 했습니다.
> 그래서 레스토랑 field 를 각각으로 처리할지 field 라는 하나의 속성으로 처리할지 고민을 했습니다.
> 다음과 같은 이유 때문에 추상화를 하기로 결정했습니다.
> 
> * 개발중인 어플리케이션이라면 field 에 항목이 추가되거나 변경될 가능성이 높다
> * 반복적인 코드량이 줄어들어서 무엇을 하는지 잘 파악된다.
> 
> 아래와 같은 경우는 field 하나로 하려면 reduce 를 사용해서 합쳐주고, 순서도 고려해야 되어서,
> 정말로 field 가 많지 않은 이상 그대로 해도 변경이 쉬울듯 하여, 추상화해주지 않았습니다.
> 
> ```
> <li key={id}>
>   {`${name} | ${category} | ${address}`}
> </li>
> ```

올바른 판단입니다👍 중복이 발생될 게 자명하거나 복잡도가 올라갈 때가 아니면 굳이 앞서서 추상화를 할 필요가 없습니다.

테스트를 먼저 작성하면서 테스트하기가 힘들다고 느껴진다면 그게 설계를 개선해야된다는 신호죠.

TDD로 진행하면서 오는 다양한 신호들을 잘 느껴보세요.

2020-10-17 13:21 UTC, wholemann commented on src/App.jsx
> +      <FormContainer />
```suggestion
      <RestaurantsContainer />
      <RestaurantCreateContainer />
```

2020-10-17 13:21 UTC, wholemann commented on src/App.jsx
> +      <FormContainer />
광범위하게 재사용될 컴포넌트가 아니라면 의미를 더 드러냅시다.

2020-10-17 13:23 UTC, wholemann commented on src/App.test.jsx
> +import { useSelector, useDispatch } from 'react-redux';
```suggestion
import React from 'react';

import { useSelector, useDispatch } from 'react-redux';
```

여긴 구분해주는 게 좋을 것 같아요.

2020-10-17 13:24 UTC, wholemann commented on src/Form.jsx
> +const isBlank = (string) => string.trim().length === 0;
만약 이 함수가 광범위하게 쓰일 가능성이 높다면

src/utils/index.js 로 분리하는 것도 좋습니다.

2020-10-17 13:25 UTC, wholemann commented on src/Form.jsx
> +export default function Form({ restaurant, getChangeHandler, onClick }) {
이미 들어오는 상태가 restaurant를 전제로 하고 있습니다. restaurant를 아는 이상 일반화는 불가능하죠.

궁극적으로 일반화가 필요할까요? 중복이 발생하지 않는 이상 성급한 일반화는 오히려 유연성을 떨어뜨립니다.

RestaurantForm으로 수정하면 될 것 같네요.

2020-10-17 13:25 UTC, wholemann commented on src/Form.jsx
> +  const isAddable = Object.values(restaurant).every((value) => !isBlank(value));
이건 무슨 의미인지 잘 모르겠습니다.

2020-10-17 13:26 UTC, wholemann commented on src/Form.jsx
> +      <button type="button" onClick={onClick} disabled={!isAddable}>등록</button>
RestaurantForm으로 한정한다면 오히려 이 코드는 읽기 어렵습니다.

추상화를 위한 추상화를 경계하세요.

```javascript
      <input
        type="text"
        placeholder="이름"
        name="name"
        value={restaurant.name}
        onChange={handleChange}
      />
      <input
        type="text"
        placeholder="분류"
        name="category"
        value={restaurant.category}
        onChange={handleChange}
      />
      <input
        type="text"
        placeholder="주소"
        name="address"
        value={restaurant.address}
        onChange={handleChange}
      />
      <button
        type="button"
        onClick={onClick}
      >
        등록
      </button>
```

2020-10-17 13:27 UTC, wholemann commented on src/reducer.test.js
> +  const previousState = {
```suggestion
  const initialState = {
```

가 오히려 의미에 맞는 듯 하네요.

2020-10-17 13:30 UTC, wholemann commented on src/reducer.test.js
> +  });
```javascript
  describe('changeRestaurantField', () => {
    it('changes restaurant form', () => {
      const initailState = {
        restaurant: {
          name: '이름',
          category: '분류',
          address: '주소',
        },
      };

      const state = reducer(initailState, changeRestaurantField({
        name: 'address',
        value: '서울시 강남구 역삼동',
      }));

      expect(state.restaurant.address).toBe('서울시 강남구 역삼동');
    });
  });
```

테스트 코드는 무조건 읽기 쉬운 example로 작성되어야 합니다.

현재 코드는 무슨 일이 벌어지는지 알기 어렵습니다. 제가 제시한 코드와 비교해보시면 좋을 듯 합니다.

2020-10-17 13:31 UTC, wholemann commented on src/reducer.js
> +    });
```suggestion
    const { newId, restaurants, restaurant } = state;

    return {
      ...state,
      newId: newId + 1,
      restaurants: [...restaurants, { ...restaurant, id: newId }],
      restaurant: initialRestaurant,
    };
```

2020-10-17 13:31 UTC, wholemann commented on src/reducer.js
> +    });
간단하게 만들 방법을 고민해보세요ㅎㅎ

2020-10-17 13:32 UTC, wholemann commented on src/reducer.js
> +    });
mapValues가 정말 필요한지, 가독성 향상을 돕는지 고민해봐야 합니다.

구현에 끌려가면 안 됩니다.

2020-10-17 13:33 UTC, wholemann commented on src/reducer.js
> +  },
```suggestion
    const { name, value } = action.payload;
    return {
      ...state,
      restaurant: {
        ...state.restaurant,
        [name]: value,
      },
    };
```

보통 field는 좀 더 상위 개념이고

field가 name, value 쌍으로 이루어지죠.

2020-10-17 13:35 UTC, wholemann commented on src/index.jsx
> +import { Provider } from 'react-redux';
```suggestion
import ReactDOM from 'react-dom';

import { Provider } from 'react-redux';
```

2020-10-17 13:36 UTC, wholemann commented on src/reducer.js
> +};
```suggestion
function defaultReducer(state) {
  return state;
}

export default function reducer(state = initialState, action) {
  return (reducers[action.type] || defaultReducer)(state, action);
}
```

어떤가요?

2020-10-17 13:38 UTC, wholemann requested changes
성급한 추상화, 일반화를 경계하세요.

정말 광범위한 중복이 발생할 컴포넌트가 아니라면 (TextInputField, Button, DatePickerField 등등)

대부분은 불필요한 일반화를 하게 됩니다.

재사용 그 자체가 목적이 되면 안 됩니다.

정말 단순한 경우가 아니라면 의미에 집중하는게 좋습니다.

언제나 읽기 좋고, 역할과 의미가 잘 드러나는 명명을 고민해보세요.

2020-10-17 13:48 UTC, gringrape commented on src/reducer.js
> +    });
넵 ㅎ 처음에는 이런식으로 진행했었는데, '  이름   ' 이런 경우에 trim 처리를 reducer 에서 밖에 못하기도 하고,
initialRestaurant 보다 확실히 비워준다는걸 알려주고 싶어서 mapValues 를 쓰게 되었습니다.

2020-10-17 13:51 UTC, gringrape commented on src/Form.jsx
> +      <button type="button" onClick={onClick} disabled={!isAddable}>등록</button>
음 UI 에서 추상화 하는것은 확실히 덜명확해지네요.

2020-10-17 13:54 UTC, gringrape commented on src/Form.jsx
> +  const isAddable = Object.values(restaurant).every((value) => !isBlank(value));
input 값이 모두다 들어있어야 한다는 조건을 검사해주기 위해 넣었습니다.

2020-10-18 07:13 UTC, gringrape commented
피드포워드 받은 내용들을 수정했습니다 :)
추상화의 필요성에 대해서 다시 생각해볼수 있어서 좋았습니다.
읽는 사람을 고려하지 않는 코딩이 다시 스멀스멀 올라오는것 같아서
지난 3주간 바뀐것들을 다시 살펴봐야 할것 같습니다;

기한은 끝나겠지만, 혹시 추가적으로 아쉬운 부분 있으면 알려주시면 감사하겠습니다!
개인적으로 수정해보겠습니다.

2020-10-18 09:50 UTC, wholemann commented on src/RestaurantForm.jsx
> +  const isOneOfValueBlank = Object.values(restaurant).some(isBlank);
```suggestion
  const isValid = name && category, address;
```

2020-10-18 09:50 UTC, wholemann commented on src/RestaurantForm.test.jsx
> +describe('Form', () => {
```suggestion
describe('RestaurantForm', () => {
```

2020-10-18 10:02 UTC, wholemann commented on src/RestaurantForm.test.jsx
> +describe('Form', () => {
테스트 꼼꼼하게 잘 작성하셨네요! 읽기도 좋구요.

2020-10-18 10:09 UTC, wholemann reviewed
TDD로 진행하는 게 쉽지 않았을텐데 잘 따라와주셨습니다.

결국 시간을 많이 쓰는 게 정답입니다ㅎㅎ

이제 아샬님 피드백 강의를 보시면 바닥부터 TDD로 쌓아올려가는 과정을 보실 수 있을텐데

저같은 경우는 이 진행 순서를 통으로 외우는 걸 추천드립니다ㅎㅎ

그냥 외워야 해요ㅎㅎ

회고까지 잘 마무리해주세요!

2021-01-17 12:48 UTC, merged