[Week4] Assignment 2 - 레스토랑 정보 확인 및 예약 시스템 구축하기
CodeSoom/react-week4-assignment-2 pull request #26
Opened 2020-10-15 14:58 UTC by wjy5446

## 목표

- TDD로 기능 구현
- 레스토랑 목록 보기 기능
- 레스토랑 추가 기능

모든 컴포넌트에 테스트를 작성해주세요. 그리고 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해주세요.

## 요구사항

- ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- 모든 인수 테스트를 통과시켜야 합니다.
- 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- 테스트 커비리지 100%를 달성해야 합니다.

## 제한조건

- 모든 기능은 TDD로 구현합니다. 컴포넌트와 reducer에 대한 테스트가 존재해야 합니다. 먼저 테스트를 추가하고 commit 한 뒤 실제 기능을 추가하고 commit합니다. commit 메시지 로그는 아래와 같이 남아야 합니다.

> Restaurant에 대한 테스트를 추가한다
>
> Restaurant을 구현한다
>
> Restaurant를 리팩토링한다
>
> ...

## 진행사항
- [x] 컴포넌트 테스트 코드 작성
- [ ] reducer 테스트 코드 작성
- [ ] 컴포넌트 작성
- [ ] reducer 작성

## 테스트 코드 목록

- App
  - 이름 Input의 값이 입력되면 이름 Input 값이 변화된다.
  - 분류 Input의 값이 입력되면 분류 Input 값이 변화된다.
  - 주소 Input의 값이 입력되면 주소 Input 값이 변화된다.
  - 등록 버튼을 클릭하면 List에 Input 값이 추가된다.
  - 등록 버튼을 클릭하면 Input의 값이 초기화된다.

- Page
  - "Restaurant"가 제목으로 출력된다.

- Form
  - 버튼에 "등록" 문구가 나온다.
  - 버튼이 클릭되면 handleClick이 호출된다.
  - restaurantInfo가 주어지지 않을 때, placeholder에 "이름" 문구가 나온다.
  - restaurantInfo가 주어지지 않을 때, placeholder에 "분류" 문구가 나온다.
  - restaurantInfo가 주어지지 않을 때, placeholder에 "주소" 문구가 나온다.

- Input
  - Input이 변화되면 handelChange가 호출된다.
  - value가 없을 때, 주어진 placeholder가 출력된다.
  - value가 있을 때, 주어진 value가 출력된다.

- List
  - restaurantInfos가 3개 주어졌을 때, restaurantInfo 리스트가 잘 출력된다.

- Item
  - restaurantInfo 있을 때, restaurantInfo "{name} | {type} | {location}" 형태로 출력한다.

2020-10-16 17:24 UTC, Kihyun92 reviewed
전체적인 플로우에따른 테스트 코드를 먼저 작성하셨네요! 좋습니다. 다만 이 경우에는 개발을 시작하기에 진입장벽?이 조금 높아질 것 같아요.

각각의 컴포넌트 단위로 `Red-Green-Refactoring` 방식으로 개발해보는 걸 권장드려요. 이 방식을 사용하면 테스트-개발-리팩토링의 사이클을 매우 빠르게 가져가실 수 있습니다.
과제를 구현하는 방법은 여러가지이기 때문에 작업 중인 방식으로 하셔도 좋고, 바로 적용하기 힘드실 것 같으면 참고만 해보셔도 좋을 것 같아요~

- https://www.codecademy.com/articles/tdd-red-green-refactor

2020-10-17 14:02 UTC, wjy5446 commented
> 전체적인 플로우에따른 테스트 코드를 먼저 작성하셨네요! 좋습니다. 다만 이 경우에는 개발을 시작하기에 진입장벽?이 조금 높아질 것 같아요.
> 
> 각각의 컴포넌트 기능 단위로 `Red-Green-Refactoring` 방식으로 개발해보는 걸 권장드려요. 이 방식을 사용하면 테스트-개발-리팩토링의 사이클을 매우 빠르게 가져가실 수 있습니다.
> 과제를 구현하는 방법은 여러가지이기 때문에 작업 중인 방식으로 하셔도 좋고, 바로 적용하기 힘드실 것 같으면 참고만 해보셔도 좋을 것 같아요~
> 
> * https://www.codecademy.com/articles/tdd-red-green-refactor

맞습니다. 이렇게 작성하니 완벽하게 테스트 코드를 작성하려고 하니 시작도 어렵고 힘드네요..
그래도 온라인 모각코를 통해서 윤석님에게 직접 TDD 작성하는 방법을 보니 제가 잘못 테스트 코드를 작성했더라구요.
그래서 알려주신 방법으로 코드 작성해보려고 하고 있습니다.

2020-10-17 15:00 UTC, wjy5446 commented
# 작업 내용

- Representation Component
  - App, Form, Input, List, Item

- Container Component
  - FormContainer, ListContainer

## 질문사항

- 테스트 코드를 작성하다 보니 ListContainer의 경우에는 useSelector로 state를 받아서 List로 전달하는 역활만 합니다. 그래서 ListContainer에 대한 테스트 코드를 작성하려다 보니, 막상 어떻게 테스트 코드를 작성할 지 모르겠네요. 이런 경우에는 어떻게 테스트 코드를 작성하나요?

- container component에 대해서 테스트 코드를 작성하려고 하니, 클릭했을 때, dispatch가 호출되는지에 대해서만 테스트 코드만 작성했습니다. 실제로 클릭되었을 때, 값이 변화되는 지에 대해서 테스트 코드를 작성해보려고 했지만, redux-react 모듈이 mock 모듈이기 때문에 이벤트가 발생하면 state에 값이 업데이트 되지않네요. 그래서 해당 코드는 제거했습니다. 잘 생각해보니 이미 reducer에서 action를 받아서 state가 잘 업데이트 되는 지 확인하고, presentation component에서 현재 state가 잘 출력되는 지 확인하기 때문에 container component에서는 dispatch가 잘 호출되는 지만 확인했습니다. 보통 이렇게 작성하나요??

2020-10-17 17:08 UTC, Kihyun92 requested changes
테스트 코드를 작성하다 보니 ListContainer의 경우에는 useSelector로 state를 받아서 List로 전달하는 역활만 합니다. 그래서 ListContainer에 대한 테스트 코드를 작성하려다 보니, 막상 어떻게 테스트 코드를 작성할 지 모르겠네요. 이런 경우에는 어떻게 테스트 코드를 작성하나요?
-> 각 역할에 맞는 테스트만 하시면 될 것 같아요~ 다른 동료들에게 해당 기능에 대한 설명을 해주는게 테스트라고 했습니다. 말씀하신대로 state를 받아서 전달해주는 역할만한다면, 잘 전달 되는지만 테스트하면 되겠네요 :)

container component에 대해서 테스트 코드를 작성하려고 하니, 클릭했을 때, dispatch가 호출되는지에 대해서만 테스트 코드만 작성했습니다. 실제로 클릭되었을 때, 값이 변화되는 지에 대해서 테스트 코드를 작성해보려고 했지만, redux-react 모듈이 mock 모듈이기 때문에 이벤트가 발생하면 state에 값이 업데이트 되지않네요. 그래서 해당 코드는 제거했습니다. 잘 생각해보니 이미 reducer에서 action를 받아서 state가 잘 업데이트 되는 지 확인하고, presentation component에서 현재 state가 잘 출력되는 지 확인하기 때문에 container component에서는 dispatch가 잘 호출되는 지만 확인했습니다. 보통 이렇게 작성하나요??
-> FormContainer.test.jsx에서 말씀하시는 거라면, dispatch가 호출 되는지만 확인하셔도 될 것 같습니다 :)

2020-10-17 17:08 UTC, Kihyun92 commented on src/FormContainer.jsx
> +    dispatch(updateRestaurantLocation(event.target.value));
이 함수들은 하나로 합칠 수 있을 것 같아요~

2020-10-17 17:08 UTC, Kihyun92 commented on src/Form.test.jsx
> +  });
change 에 대한 테스트도 추가되면 좋겠네요~

2020-10-17 17:08 UTC, Kihyun92 commented on src/Form.jsx
> +        onChange={handleChangeRestaurantLocation}
컴포넌트의 재사용성을 고려해보셨네요~ 좋습니다!😁
다만 이 경우에는 input 태그를 바로 사용하는 것과 어떤 차이가 있을까요? 
재사용 가능한 공통 컴포넌트로 처리하는 경우는 공통적인 비즈니스 로직이나 복잡한 로직을 가지고 있는 경우에 좋을 것 같아요 :)

2020-10-17 17:08 UTC, Kihyun92 commented on src/Item.jsx
> +  const { name, type, location } = restaurantInfo;
`List.jsx`에서 props를 destructuring해서 넘겨주면 좋을 것 같아요~

```suggestion
export default function Item({ name, type, location }) {
```

2020-10-17 17:08 UTC, Kihyun92 commented on src/actions.js
> +}
이 `action`들은 비슷한 역할을 하고 있는 것 같아요,  합칠 순 없을까요~?
`payload`에 다른 정보들을 추가해보면 어떨까요?

2020-10-17 17:08 UTC, Kihyun92 commented on src/reducer.js
> +  listRestaurantInfo: [],
네이밍이 조금 어색한 것 같아요~ `restaurantInfoList`나 `restaurantInfos` 혹은 그냥 `restaurants`는 어떤가요?

2020-10-17 17:08 UTC, Kihyun92 commented on src/reducer.js
> +    },
이 부분도 비슷한 역할을 하는 `reducer`들이 `name, type, location`이라는 키값으로 구분되어있네요! 마찬가지로 action.payload에서 값을 가져와서 처리해주면 중복 코드가 제거될 것 같아요!

```
const { name, value } = action.payload;
    updateRestaurant: {
      ...state,
      restaurant: {
        ...state.restaurant,
        [name]: value,
      },
    },
```

2020-10-18 04:21 UTC, wjy5446 commented on src/Form.jsx
> +        onChange={handleChangeRestaurantLocation}
그러네요. Input 컴포넌트를 보면 단순히 prop들을 input태그에 전달하는 역활만 하네요. Input 컴포넌트를 없애는 쪽이 맞을 것 같습니다. 감사합니다.

2020-10-18 04:26 UTC, wjy5446 commented on src/Form.jsx
> +        onChange={handleChangeRestaurantLocation}
하지만 생각보니 Input 컴포넌트 대신에 input 태그를 바로 사용하게 되면서 생긱는 문제점이 있는 것 같습니다.
Input에 대한 테스트 코드도 당연히 Form에 대한 테스트에 추가되면서 Form 에 대한 테스트가 늘어나는 것 같습니다.

2020-10-18 04:53 UTC, wjy5446 commented on src/Item.jsx
> +  const { name, type, location } = restaurantInfo;
이렇게 작성하는 게 더 좋을 것 같네요. 감사합니다.
근데 궁금한게 이렇게 작성할 경우, name, type, location이 어떤 이름인지, 타입인지 모르지 않을 까요?
이에 대해서 어떻게 생각하시나요?

2020-10-18 05:29 UTC, wjy5446 commented on src/actions.js
> +}
payload에 { type, value }에 정보를 추가해서 보내는 코드로 변경했습니다. (type은 input의 종류고 value는 업데이트할 값입니다.)
해당 코드로 변경하니 좀 더 코드가 깔끔해졌네요.

2020-10-18 05:43 UTC, wjy5446 commented on src/reducer.js
> +  listRestaurantInfo: [],
제안해주신 네이밍이 좀 더 자연스럽네요. 감사합니다.!!

2020-10-18 05:48 UTC, Kihyun92 commented on src/Form.jsx
> +        onChange={handleChangeRestaurantLocation}
테스트가 늘어나는 부분은 어쩔수가 없는 것 같아요 :) 개인적으로는 테스트가 많아서 테스트를 나누기 위해 의미없는 컴포넌트 분리를 하는건 주객전도 되는 느낌이라 맞지 않아보여요.

중복되는 테스트가 없는지 꼭 필요한 테스트인지도 가늠해보시면 좋을 것 같습니다~

2020-10-18 05:55 UTC, Kihyun92 requested changes

2020-10-18 05:55 UTC, Kihyun92 commented on src/Item.jsx
> +  const { name, type, location } = restaurantInfo;
맞아요. 제가 잘못 생각했던 것 같습니다.😅 
제가 말씀드린 경우가 더 좋은 케이스는 `restaurantInfo`에 Item에서 쓰는 `name, type, location`외에 다른 정보들이 있는 경우에 유용할 것 같고, 지금과 같은 케이스에서는 `restaurantInfo`를 넘겨주는게 괜찮을 것 같네요~

2020-10-18 05:56 UTC, wjy5446 commented on src/Form.jsx
> +        onChange={handleChangeRestaurantLocation}
조언 감사드립니다. 하다보니 placeholder 중복으로 체크하고 있더라구요 ㅎㅎ

2020-10-18 06:11 UTC, wjy5446 commented on src/reducer.js
> +    },
이것도 action 하나로 합치면서 수정했습니다. 
하지만 수정하면서 action마다 payload가 달라지니 object literal lookup으로 수정하니 오류가 발생합니다.
그래서 일단 테스트 코드 통과하기 위해서 임시로 코드 수정을 했는 데, 뭔가 코드가 더 지저분해지네요.
어떻게 하면 좀 더 깔끔하게 작성할 수 있을 까요? 그냥 if문으로 작성하는 게 나을 까요?

```jsx
export default function reducer(state = initialState, action) {
  const router = {
    updateRestaurantInfo: () => ({
      ...state,
      restaurantInfo: {
        ...state.restaurantInfo,
        [action.payload.type]: action.payload.value,
      },
    }),
    addRestaurantInfo: () => ({
      ...state,
      restaurantInfo: {
        name: '',
        type: '',
        location: '',
      },
      restaurantInfoList: [
        ...state.restaurantInfoList,
        action.payload,
      ],
    }),
  };

  return (router[action.type] || (() => state))();
}

```

2020-10-18 06:19 UTC, wjy5446 commented on src/FormContainer.jsx
> +    dispatch(updateRestaurantLocation(event.target.value));
action을 하나로 합치면서 핸들러 코드도 하나로 합쳤습니다. !!

2020-10-18 06:40 UTC, wjy5446 commented on src/Form.test.jsx
> +  });
Change 테스트를 Input에 작성했었네요. Input 컴포넌트 없애면서 Form에 해당 테스트 코드 작성했습니다.

2020-10-18 14:27 UTC, Kihyun92 approved these changes
고생하셨습니다~ 👍  과제풀이 영상을 통해서 아샬님은 `Red-Green-Refactoring` 사이클을 어떤식으로 가져가는지를 집중해서 봐보시면 좋을 것 같아요~
이번 과제를 통해서 무엇을 배우셨나요? 아쉬웠던 부분이나 더 시도해보고 싶은게 있나요? :)

2020-10-19 13:33 UTC, Kihyun92 commented
4주차 회고 작성해주시면 머지 하겠습니다~

2020-10-19 14:18 UTC, wjy5446 commented
# 3주차 회고
## 1. 한 일
- redux 공부
- TDD 실습

## 2. 배운점

- redux 구조 파악
  - view -> action -> dispatcher -> store
  - reducer : state와 action을 입력받아서 새로운 state를 반환하는 함수
  - action : type, payload로 이루어진 객체
  - action creator : action을 생성하는 함수
  - dispatch : action을 store에 보내는 함수
  - store : 상태값이 갖는 객체

- TDD 작성 방법 이해 : TDD는 Red - Green - Refactoring을 한번만 진행하는 것이 아니라, Red - Green - Refactoring 을 계속해서 진행해 나가는 방법
  - 이를 통해서 큰 구조의 모델도 안전성이 높은 코드 구현이 가능해진다.

- redux의 사용 의미 : redux가 존재하지 않을 때에는 이벤트 핸들러나 state를 최상단의 컴포넌트에 정의를 했어야 했다. 하지만 redux로 state를 따로 관리하다보니 Container Component를 이용해서 각 컴포넌트에 필요한 요소들만 분리해서 관리가 가능해 졌다.


3. 느낀 점 & 자기 선언
 
코드숨 과제를 TDD로 진행하면서 느낀 점이지만 Red - Green - Refactoring을 반복하면서 코드를 작성하는 것은 배웠는 데, 테스트 코드 작성에 미숙하다 보니 잘못된 테스트 코드를 작성하게 된다. Red을 해결하기 위해서 Green을 작성해야 되는 데, Red 자체가 테스트 코드가 이상해서 생기는 문제이다 보니 TDD가 잘 진행되지 않는 다는 느낌이 들었다. 그래서 jest 문법에 대해서 좀 더 알아야 겠다라는 생각이 들었다.

2020-10-19 15:12 UTC, merged