🎨 Implements Restaurant Lists ( 진행중...)
CodeSoom/react-week4-assignment-2 pull request #27
Opened 2020-10-15 15:25 UTC by Knoa0405

구현 중입니다. 틈틈히 PR 보내겠습니다~!

2020-10-16 01:06 UTC, hannut91 requested changes

2020-10-16 01:06 UTC, hannut91 commented on src/App.jsx
> +import Input from './Input';
위에 빈 줄 하나로 임포트를 구분해주면 좋을 것 같아요

2020-10-16 01:06 UTC, hannut91 commented on src/App.test.jsx
> +  it('should visible all component', () => {
위에 빈 줄 을 추가해서 구분해주면 좋을 것 같아요

2020-10-16 01:06 UTC, hannut91 commented on src/App.test.jsx
> +    getByText('등록');
`getBy*`는 찾지 못하면 에러가 발생해서 테스트가 가능하긴 하지만 단정문을 사용해서 더 명확하게 표현해주는게 더 좋을 것 같아요

```js
const { container } = rednerApp();

expect(container).toHaveTextContent('Restaurants');
```

See also
  - https://github.com/testing-library/jest-dom#tohavetextcontent

2020-10-16 01:06 UTC, hannut91 commented on src/Input.jsx
> +  inputState: { nameTitle, classification, location },
`input`이라는 것은 `Input` 때문에 사용하신 것 같아요

이름, 종류, 위치는 사실 `레스토랑`을 의미하는 거죠?

2020-10-16 01:06 UTC, hannut91 commented on src/List.jsx
> +export default function List({ restaurantLists }) {
`List`라는 이름은 목록을 나타내므로 이미 여러개를 나타내고 있고, `List`라는 자료형을 나타내는 것 같아서 사용하는걸 권장하지 않습니다. 
`restaurants`라고 하면 이미 복수형을 나타내서 여러개라는 걸 충분히 드러내고 있을 것 같아요

2020-10-17 04:09 UTC, hannut91 requested changes

2020-10-17 04:09 UTC, hannut91 commented on src/App.test.jsx
> +      },
`info`와 `value`는 아무런 의미를 드러내지 않는 것 같아요. 이름은 사실 레스토랑 이름이고, category는 레스토랑의 분류이고 address는 레스토랑의 주소를 나타내니까 `restaurant`로 하는건 어떨까요?

혹은 이 정보를 가지고 레스토랑을 등록하는 거니까 `restaurantForm`은 어떨까요?

2020-10-17 04:09 UTC, hannut91 commented on src/Input.jsx
> +}
레스토랑을 등록하는 컴포넌트이니까 `RestaurantForm`은 어떨까요?

2020-10-17 04:09 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  beforeEach(() => jest.clearAllMocks());
arrow함수는 함수 내용이 한 줄일 경우 그 결과를 반환합니다. 그래서 여기만 보면 `beforeEach` 콜백 함수가 아무런 파라미터가 없고, `jest.clearAllMocks`의 결과를 반환하는 것 같이 생겼습니다. 하지만 사실은 반환값을 어디에서도 사용하지 않습니다. 따라서

```js
beforeEach(() => {
  jest.clearAllMocks();
});
```

처럼 명시적으로 사용하는게 좋을 것 같습니다.

2020-10-17 04:09 UTC, hannut91 commented on src/List.jsx
> +
여기 빈 줄이 들어가 있네요

2020-10-17 04:09 UTC, hannut91 commented on src/List.jsx
> +        ;
이건 없어도 될 것 같아요

2020-10-17 04:09 UTC, hannut91 commented on src/actions.js
> +}
`Information`이 무엇을 의미하는지 파악하기 어려운 것 같아요. 레스토랑 폼에 있는 것을 비워주고 싶으셨던거죠?

2020-10-17 04:09 UTC, hannut91 commented on src/reducer.js
> +  return state;
if나 switch문 없이 이 문제를 해결할 수 있을까요?

2020-10-17 04:09 UTC, hannut91 commented on src/reducer.test.js
> +  });
올바르게 동작하지 않는다는게 무슨 의미인지 파악하기 어려운 것 같아요. initial 상태를 반환하고 있는거죠?

2020-10-17 04:09 UTC, hannut91 commented on src/reducer.test.js
> +  });
`appending`이라는 의미를 이 테스트에서는 찾아볼 수 없는 것 같아요.

2020-10-17 09:22 UTC, Knoa0405 commented on src/reducer.test.js
> +  });
그렇군요 맞습니다. 수정하겠습니다~!

2020-10-17 09:23 UTC, Knoa0405 commented on src/reducer.test.js
> +  });
네 reducer 가 동작하지 않으면 초기 상태를 반환하기 때문에
reducer 가 동작하지 않는다 라고 써줬는데 생각해보니 결과에 초점을 맞추면 더 의미가 명확해지겠네요ㅎㅎ

2020-10-17 09:24 UTC, Knoa0405 commented on src/reducer.js
> +  return state;
4-1 과제에서와 같은 이슈네요 이건 일단 보내고 수정해두려고 남겨뒀습니다. 오늘 중으로 수정해서 PR 보내겠습니다~!

2020-10-17 15:17 UTC, Knoa0405 commented
## 이번 과제하다 느낀 문제점!
생각해보니 테스트 코드 작성을 하고 실제 코드를 작성을 했어야 했는데
습관이 아직 덜 되어서 뒤죽박죽 섞인 것 같습니다...!
다음 과제부터는 제대로 표기해서 commit 을 잘 정리해보겠습니다~!

2020-10-17 16:26 UTC, hannut91 approved these changes

2020-10-17 16:26 UTC, hannut91 commented on src/List.test.jsx
> +});
list가 비어있을 때와 있을 때를 테스트할려고 하신 것 같아요. 이럴 경우에 `context`를 이용해서 더 의도를 드러낼 수 있습니다.

```js
describe('List', () => {
  const renderList = (restaurants = []) => render((
    <List restaurants={restaurants} />
  ));

  beforeEach(() => {
    jest.clearAllMocks();
  });

  context('with restaurants', () => {
    const restaurants = [
      { id: 1, name: '고봉민 김밥', category: '한식', address: '서울' },
      { id: 2, name: '도미노피자', category: '양식', address: '부산' },
    ];

    it('shows restaurants', () => {
      const { } = renderList(restaurants);

      restaurants.forEach(({ name, category, address }) => {
        expect(container).toHaveTextContent(`${name}|${category}|${address}`);
      });
    });
  });

  context('with empty', () => {
    const restaurants = [];

    it('Empty Lists', () => {
      const { container } = renderList(restaurants);

      expect(container).toHaveTextContent('Restaurants');
    });
  });
});
```

2020-10-17 16:26 UTC, hannut91 commented on src/ListContainer.test.jsx
> +      ],
테스트에서 사용되는 데이터들이 반복해서 사용되고 있습니다. 테스트용 데이터를 미리 만들어놓고 사용하여 중복을 줄일 수 있고, 테스트의 복잡성을 낮출 수 있습니다. 이러한 테스트용 데이터를 fixture라고 부릅니다. fixtures라는 폴더를 하나 만들고 여기에 테스트용 데이터들을 모아놓고 가져다가 사용하는건 어떨까요?

2020-10-17 16:28 UTC, hannut91 commented
테스트를 잘 작성해주신 것 같습니다 ㅎㅎ 더 자세한 내용은 과제 풀이 영상을 통해서 복습해보시면 좋을 것 같아요. 특히 코드를 작성할 때 어떤 순서로 어떤 기준으로 코드를 작성하는지 눈여겨 보면 좋을 것 같습니다

 이번 과제를 통해서 무엇을 배우셨나요? 다음 과제에서 더 시도해보고 싶으신게 있으신가요?

2020-10-18 12:49 UTC, Knoa0405 commented
회고록 작성완료했습니다~!

https://www.notion.so/4-511e8ceb5e67441c9dbb73f9b641e3b0

2020-10-18 13:44 UTC, merged