Week4_2 Restaurant TDD
CodeSoom/react-week4-assignment-2 pull request #28
Opened 2020-10-15 15:26 UTC by saseungmin

## 🚀 레스토랑 정보 확인 및 예약 시스템 구축하기

- 시간이 부족하여 여기부분에 작성을 못했습니다
- 내일 다시 작성하겠습니다.🙏
- 작성하다보니 `App` 컴포넌트에 `changeHandle` 함수를 먼저 작성하게되었습니다...

2020-10-16 06:53 UTC, hannut91 requested changes

2020-10-16 06:53 UTC, hannut91 commented on src/Input.test.jsx
> +import Input from './Input';
위에 빈 줄 하나를 추가해서 라이브러리 임포트와 로컬 파일 임포트를 구분해주면 좋을 것 같아요

2020-10-16 06:53 UTC, hannut91 commented on src/Input.test.jsx
> +  it('"input"이 존재하는지 확인한다.', () => {
`확인한다` 보다는 실제로 어떤 일이 일어나는지, 어떤 변화가 일어나는지 기술해주면 더 좋을 것 같아요. 예를들면 input을 렌더링 한다 혹은 보인다 정도로 해도 될것 같아요

2020-10-17 14:07 UTC, saseungmin commented
- 너무 늦게 해서 죄송합니다.. 🙏😢
- 코드리뷰 부탁드리겠습니다..

2020-10-17 16:42 UTC, hannut91 requested changes

2020-10-17 16:42 UTC, hannut91 commented on src/Button.test.jsx
> +  it('버튼 클릭시 호출되는지 확인한다.', () => {
테스트는 실제로 어떤 일이 일어나는지 명시해주는게 더 좋을 것 같아요. 버튼을 클릭하면 onClick 핸들러가 실행된다는 어떨까요?

2020-10-17 16:42 UTC, hannut91 commented on src/Input.jsx
> +);
`Form`이라는 이름은 어떨까요?

2020-10-17 16:42 UTC, hannut91 commented on src/Input.test.jsx
> +  ];
여러개를 나타내니 `inputTypes`가 더 적절할 것 같아요.
나타내는 데이터는 배열이라서 여러개를 담고 있는데 변수의 이름을 보면 단수를 사용하고 있어서 마치 배열이 아닌 객체나 다른 타입인 것 처럼 보입니다. 변수이름에 복수를 사용하면 변수 이름만 봐도 여러개를 나타낸다는 것을 알 수 있어서 더 쉽게 의도를 드러낼 수 있습니다.

2020-10-17 16:42 UTC, hannut91 commented on src/List.test.jsx
> +  });
레스토랑이 없을 때는 아무것도 출력하고 싶지 않으셨군요. 아에 레스토랑이 비어있으면 null을 반환하게 하고 비어있는지 확인하는 테스트를 작성하면 좋을 것 같아요.

```js
const { container } = listRender(restaurants);

expect(container).toBeEmptyDOMElement();
```

See also
  - https://github.com/testing-library/jest-dom#tobeemptydomelement

2020-10-17 16:42 UTC, hannut91 commented on src/ListContainer.test.jsx
> +  ];
테스트에서 사용되는 데이터들이 반복해서 사용되고 있습니다. 테스트용 데이터를 미리 만들어놓고 사용하여 중복을 줄일 수 있고, 테스트의 복잡성을 낮출 수 있습니다. 또 복잡한 계산같은 경우 믿고 이미 테스트가 된 데이터들을 저장해놓을 수 있습니다. 이러한 테스트용 데이터를 fixture라고 부릅니다. fixtures라는 폴더를 하나 만들고 여기에 테스트용 데이터들을 모아놓고 가져다가 사용하는건 어떨까요?

2020-10-17 16:42 UTC, hannut91 commented on src/reducer.test.js
> +    });
`returns intialState`는 어떨까요?

2020-10-18 05:51 UTC, saseungmin commented on src/ListContainer.test.jsx
> +  ];
- 적용해보니 훨씬 좋아보입니다!!

2020-10-18 13:36 UTC, hannut91 approved these changes
고생하셨어요 ㅎㅎ 테스트를 읽기 좋게 만들기 위해서 많은 노력을 한 흔적들이 보이네요. 과제풀이 영상을 통해서 문제를 풀이하는 과정에 집중해서 복습해보시면 좋을 것 같아요 

이번 과제를 통해서 무엇을 배우셨나요? 다음에 더 시도해보고 싶은 것은 무엇인가요?

2020-10-18 13:36 UTC, hannut91 commented on src/Form.test.jsx
> +    });
`inputType`는 테스트용 데이터라기보다 테스트를 검증하는데 사용되는 것 같아요. 검증하는 데 필요한 것들이 눈에 보이지 않으니 이해하기 어려운 것 같아요.

```js
['이름', '분류', '주소'].forEach((placeholder) => {
  expect(getByPlaceholderText(placeholder)).not.toBeNull();
});
```

2020-10-18 13:36 UTC, hannut91 commented on src/Form.test.jsx
> +    });
과도한 추상화로 어떤 테스트를 하는지 조금 이해가 어려운 것 같아요. 

```js
fireEvent.change(getByPlaceholderText('이름'), { 
  target: { value: '시카고 피자' }
});

expect(handleChange).toBeCalled();
```

2020-10-18 13:36 UTC, hannut91 commented on src/FormContainer.test.jsx
> +    });
restaurant[1]에서 `1`이 무엇을 나타내는지 이해하기 어려워요. 

```js
Object.values(restaurantInfo).forEach((value) => {
  expect(getByDisplayValue(value)).not.toBeNull();
});
```

2020-10-18 13:36 UTC, hannut91 commented on src/FormContainer.test.jsx
> +      restaurant: restaurantInfo,
`restaurantInfo`에서 `info`는 아무런 의미를 드러내지 않아요. 테스트용 데이터에서 가져왔다는 의미를 드러내기 위해서 mockRestaurant 혹은 restaurantFixture는 어떨까요?

2020-10-18 13:36 UTC, hannut91 commented on src/FormContainer.test.jsx
> +    });
fixture에 테스트용 `데이터`를 담는 것과 테스트를 위해 사용하는 데이터를 담는 것은 다른 일인 것 같아요. 테스트 자체를 위한 데이터는 숨기면 오히려 이해하기 어려운 것 같아요

2020-10-18 13:36 UTC, hannut91 commented on src/Item.jsx
> +    {address}
```js
{`${name} | ${category} | ${address}`}
```

이렇게 작성하는건 어떨까요?

2020-10-18 14:34 UTC, saseungmin commented on src/Form.test.jsx
> +    });
- 과도한 추상화는 이해하기 어렵다. 참고하겠습니다!

2020-10-19 14:43 UTC, hannut91 commented
슬랙 채널에 회고 남겨주셔서 머지합니다~!

2020-10-19 14:43 UTC, merged