[Week04-assignment02] 레스토랑 정보 확인 및 예약 시스템 구축하기
CodeSoom/react-week4-assignment-2 pull request #29
Opened 2020-10-15 20:13 UTC by comejtome508

**해야 하는 것**

- [ ] TDD로 기능 구현
- [ ] 레스토랑 목록 보기 기능
- [ ] 레스토랑 추가 기능

**현재 진행 상태**
- React 구조로 먼저 작성 중

**고민점**
- 강의에서 테스트 코드를 짜기 전에 먼저 형태부터 잡은 뒤 테스트로 기능을 테스트 한다고 해서 그런 식으로 진행해보고 있습니다. 그런데 컴포넌트 단위를 먼저 다 구상을 해놓고 시작을 하는지 테스트를 하다가 컴포넌트를 나눌 필요가 있으면 나누고 하는지 모르겠습니다.

2020-10-16 13:31 UTC, comejtome508 commented
**현재 진행 상태**

- React 구조로 먼저 작성 중
     - Input test 및 원 코드 작성 완료
     - Page 수정 작업 중

2020-10-17 13:16 UTC, wholemann commented on src/Input.jsx
> +export default function Input({
Input 안에 button 까지 있으면 의미가 모호해지죠.

얘는 RestaurantForm이란 이름이 역할을 잘 드러낼 거 같네요.

2020-10-17 13:16 UTC, wholemann commented on src/Input.test.jsx
> +test('Input', () => {
Input이라 하면 입력인데

button 역할까지 테스트하고 있어서 읽는 입장에서 이건 무슨 일이 벌어지는 건가 고민하게 됩니다.

2020-10-17 13:17 UTC, wholemann requested changes
성급하고 과도한 추상화, 일반화를 경계하고

의미있는 컴포넌트 이름을 부여하는 걸 먼저 고민해보세요.

정말 광범위하게 재활용될 컴포넌트(Button, TextInputField 등...) 가 아니라면

대부분은 일반화된 이름을 갖지 않습니다.

2021-01-17 12:48 UTC, closed without merging