4-2 레스토랑 정보 확인 및 예약 시스템 with TDD
CodeSoom/react-week4-assignment-2 pull request #3
Opened 2020-06-26 23:09 UTC by SeaFalcon

TDD에 조금은 익숙해져 가는 것 같습니다. 
localhost를 띄워 수 작업으로 테스트하지 않아도 기능이 완성되니 신기하네요.

밤을 새면서 했는데.. 너무 큰걸 간과했네요
과제 가이드에 useEffect를 사용하라는 걸 이제야 봤습니다...

이번 과제는 4-1 과제와 거의 동일한 구성과 내용으로 진행을 했는데
4-2는 좀 다른 것을 의도한 것이겠죠? ㅠㅠ

그래도 피드백 부탁드리겠습니다.

2020-06-27 05:17 UTC, SeaFalcon commented
이렇게 의도하신게 맞는지는 모르겠지만 ㅎㅎ
과제 힌트 조건에 있는 useEffect를 적용해봤습니다.

2020-06-27 10:41 UTC, hannut91 requested changes

2020-06-27 10:41 UTC, hannut91 commented on __mocks__/restaurants.js
> +export default [
테스트용 데이터 인가요? `fixture`폴더에 정리하는게 좋을 것 같아요 ㅎㅎ

2020-06-27 10:41 UTC, hannut91 commented on src/App.jsx
> +    dispatch(setRestaurants(restaurants));
실제 코드에서 테스트용 데이터를 사용하면 안될 것 같아요

2020-06-27 10:41 UTC, hannut91 commented on src/Component/Input.test.jsx
> +      expect(getByTestId(/name/)).not.toBeNull();
`toBeInTheDocument` matcher를 사용하시면 더 표현력이 좋을거에요

See also
  - https://github.com/testing-library/jest-dom#tobeinthedocument

2020-06-27 10:41 UTC, hannut91 commented on src/Component/InputContainer.jsx
> +  };
handler가 굉장히 많이 쓰이네요. 전부 비슷한 일을 하고 있는데요. 어떻게하면 복잡성을 줄일 수 있을까요? 다음을 참고해보세요

See also
  - https://reactjs.org/docs/forms.html#handling-multiple-inputs

2020-06-27 10:41 UTC, hannut91 commented on src/Component/InputContainer.test.jsx
> +    useSelector.mockImplementation((selector) => selector(information));
여기에는 로직이 들어가면 안됩니다.

```js
const dispatch = jest.fn();
const information = {
  name: '',
  category: '',
  address: '',
};

beforeEach(() => {
  useDispatch.mockImplementation(() => dispatch);
  useSelector.mockImplementation((selector) => selector(information));
});


```

2020-06-27 10:41 UTC, hannut91 commented on src/reducer.test.js
> +      ];
자주 사용하는 데이터는 `fixture`로 분리하면 더 깔끔하게 테스트를 작성하실 수 있을거에요

2020-06-27 10:41 UTC, hannut91 commented on src/reducer.test.js
> +        const previousState = {
`previousState`가 계속해서 반복적으로 사용되고 있어요. 중복을 제거하는게 좋을 것 같아요

2020-06-28 02:14 UTC, SeaFalcon commented on src/App.jsx
> +    dispatch(setRestaurants(restaurants));
과제의 Hint를 보고 참고했는데
그러면 useEffect는 어디에서 사용하는게 좋을까요?

2020-06-28 02:14 UTC, SeaFalcon commented on __mocks__/restaurants.js
> +export default [
넵 fixture폴더를 생성해서 옮겨보겠습니다 ㅎㅎ

2020-06-28 02:15 UTC, SeaFalcon commented on src/Component/Input.test.jsx
> +      expect(getByTestId(/name/)).not.toBeNull();
not 보다는 확실히, 있는 그대로 표현하는게 더 좋아보이네요
전체적으로 적용하겠습니다

2020-06-28 02:15 UTC, SeaFalcon commented on src/Component/InputContainer.jsx
> +  };
오.. 좋은 참고자료 감사합니다. 간단하게 구현되네요

2020-06-28 02:32 UTC, SeaFalcon commented on src/Component/InputContainer.test.jsx
> +    useSelector.mockImplementation((selector) => selector(information));
그럼 context 부분에서는
변수 선언 및 할당만 가능하고 beforeEach로 로직을 감싸서 테스트에 대한 세팅을 하게끔 하는건가요?

2020-06-28 02:41 UTC, SeaFalcon commented on src/reducer.test.js
> +        const previousState = {
중복을 제거하기 위해 로직을 변경했습니다

2020-06-28 14:25 UTC, hannut91 commented on src/App.jsx
> +    dispatch(setRestaurants(restaurants));
지금은 사용하지 않아도 괜찮습니다 ㅎㅎ 아마 다음과제에서는 꼭 필요할거에요

2020-06-28 14:25 UTC, hannut91 commented on src/Component/InputContainer.test.jsx
> +    useSelector.mockImplementation((selector) => selector(information));
네 테스트에 필요한 Given만 정의하는 곳이에요

2020-06-28 15:16 UTC, hannut91 approved these changes
고생하셨습니다! 노력하신 흔적이 많이 보이네요. 이름이나 카테고리 주소를 등록하지 않았을 때 처리되지 않도록 예외처리도 꼼꼼하게 해주셨군요!

2020-06-28 15:16 UTC, hannut91 commented on src/Component/Input.jsx
> +  const { name, category, address } = information;
이름 카테고리 주소를 객체로 만들으신 것 같아요. 하지만 `information`은 아무런 의미를 드러내지 않는 것 같아요. `restaurant`라는 이름으로 하면 어떨까요?

2020-06-28 15:16 UTC, hannut91 commented on src/Component/InputContainer.test.jsx
> +      useDispatch.mockImplementation(() => dispatch);
`dispatch`가 실행됐을 때를 테스트 할 때 만약 다른 곳에서 이미 실행된 상태에서 테스트한다면 의도치 않게 동작할 수 있어요. 그래서 `dispatch.mockClear()`를 해주시면 이런 문제가 발생하지 않을거에요.

2020-06-28 15:16 UTC, hannut91 commented on src/Component/List.jsx
> +export default function List({ informations }) {
여기도 informations라는 너무 포괄적인 이름보다는 restaurants라는 이름을 사용하면 좋을 것 같아요.

2020-06-28 15:16 UTC, hannut91 commented on src/Component/List.test.jsx
> +      expect(getByText(/강서/)).toBeInTheDocument();
모든 `informations`의 내용들이 렌더되는 것을 테스트하고 싶으시다면 이렇게 테스트를 작성하면 더 좋을거에요.

```js
informations.forEach((name, category, address) => {
  expect(getByText(name)).toBeInTheDocument();
  expect(getByText(category)).toBeInTheDocument();
  expect(getByText(address)).toBeInTheDocument();
});
```

2020-06-28 15:16 UTC, hannut91 commented
추가로 이번 과제를 진행하면서 무엇을 배우셨나요? 다음 과제에서 더 집중하거나 시도해보고 싶으신게 있으신가요?

2020-06-28 17:18 UTC, SeaFalcon commented on src/Component/List.test.jsx
> +      expect(getByText(/강서/)).toBeInTheDocument();
중복제거! 명심하겠습니다..
다만, getByText로 하니 정규표현식이 아니라 조금 더 수정해야하는군요.

2020-06-28 17:19 UTC, SeaFalcon commented on src/Component/InputContainer.test.jsx
> +      useDispatch.mockImplementation(() => dispatch);
beforeEach를 통해 각 테스트마다 dispatch와 상태를 내려주고
테스트가 끝나면 mockClear를 통해 상태를 초기화 시켜주는거죠?

2020-06-28 17:20 UTC, SeaFalcon commented on src/Component/Input.jsx
> +  const { name, category, address } = information;
변수명은 항상 어렵네요 ㅎㅎ 의도를 드러내는 것 항상 생각하겠습니다.

2020-06-29 04:16 UTC, merged