Add the test for App component
CodeSoom/react-week4-assignment-2 pull request #32
Opened 2020-10-17 12:47 UTC by hyejineee

## 과제 목표

- [ ] TDD로 기능 구현
- [ ] 레스토랑 목록 보기 기능
- [ ] 레스토랑 추가 기능
- [ ] 모든 컴포넌트에 테스트를 작성해주세요. 그리고 모두 테스트 했는지 확인하기 위해 커버리지를 100% 달성해주세요.

## 요구사항 

- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.
- [ ] 테스트 커버리지 100%를 달성해야 합니다.

2020-10-17 16:53 UTC, hannut91 requested changes

2020-10-17 16:53 UTC, hannut91 commented on src/App.test.jsx
> +  describe('first loaded', () => {
`first loaded`는 없어도 괜찮을 것 같아요. 
`describe-it`을 읽어보면 

App show Restaurant title
App show input that add Restaurant into list

등등 자연스럽게 읽히는 것 같아요

2020-10-17 16:53 UTC, hannut91 commented on src/App.test.jsx
> +      expect(getByText(/마녀주방 | 한식 | 서울시 강남구/)).not.toBeNull();
이렇게 하는건 어떨까요?

```js
const { container } = renderApp();

expect(container).toHaveTextContent('마녀주방 | 한식 | 서울시 강남구`);
```

2020-10-17 16:53 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  useDispatch.mockImplementation(() => dispatch);
각 테스트는 다른 테스트에 영향을 줘서도 안되고, 다른 테스트에 의존해서도 안됩니다. 그러면 테스트를 유지보수하기 굉장히 어려워지고 테스트가 의도치 않게 동작할 수 있습니다.  예를들어서

```js
describe('Component', () => {
  const handleClick = jest.fn();
  
  const renderComponent = () => render((
    <Component onClick={handleClick} />
  ));
  
  test('click test', () => {
    const { getByText } = renderComponent();
    
    fireEvent.click(getByText('클릭'));
    
    // 통과
    expect(handleClick).toBeCalled();
  });
  
  text('non click test', () => {
    const { getByText } = renderComponent();
    
    // 실패!
    expect(handleClick).not.toBeCalled();
  });
});
```

테스트 코드가 위에서부터 순서대로 실행이 되는데 위의 테스트에서 이미 클릭을 해서 handleClick은 호출이 된 상태가 되었습니다. 그래서 클릭이 안되어있어야 할 테스트에서 실패하게 됩니다. 이 것은 우리가 의도한게 아니라 테스트 환경을 적절히 초기화 시키지 않아서 생긴 문제입니다. 따라서 위의 문제는 아래와 같이 초기화를 해주어야 합니다.

```js
describe('Component', () => {
  const handleClick = jest.fn();
  
  // 테스트가 실행되기 전에 실행  
  beforeEach(() => {
    // mocking 함수들을 초기화
    jest.clearAllMocks();
  });
  
  const renderComponent = () => render((
    <Component onClick={handleClick} />
  ));
  
  test('click test', () => {
    const { getByText } = renderComponent();
    
    fireEvent.click(getByText('클릭'));
    
    // 통과
    expect(handleClick).toBeCalled();
  });
  
  text('non click test', () => {
    const { getByText } = renderComponent();
    
    // 실패!
    expect(handleClick).not.toBeCalled();
  });
});
```

mocking한 함수 뿐만 아니라 테스트끼리 상태가 공유되는 것들은 모두 초기화해주는게 좋습니다

See also
  - https://jestjs.io/docs/en/jest-object#jestclearallmocks
  - https://jestjs.io/docs/en/setup-teardown

2020-10-17 16:53 UTC, hannut91 commented on src/InputContainer.test.jsx
> +  describe('first loaded', () => {
여기도 `first loaded`가 없어도 괜찮을 것 같아요

2020-10-17 16:53 UTC, hannut91 commented on src/Item.jsx
> +}
`info`는 아무런 의미를 드러내지 않는 것 같아요. name은 레스토랑의 이름이고 category는 레스토랑의 분류고, location은 레스토랑의 주소를 나타내는거죠?

2020-10-17 16:53 UTC, hannut91 commented on src/ListContainer.test.jsx
> +        }));
테스트에 필요한 준비를 하는 `Given`이 복잡할 경우에는 `context`와 `it`사이에 써주는게 좋을 것 같아요.

```js
context('with restaurants', () => {
  useSelector.mockImplementation((selector) => selector({
    restaurants: [
      { name: '마녀주방', category: '한식', location: '서울시 강남구' },
    ],
  }));

  it('shows restaurants', () => {
    ...
  });
});
```

2020-10-17 16:53 UTC, hannut91 commented on src/ListContainer.test.jsx
> +    });
동작하지 않는다는 건 무엇이 동작하지 않는지 이해하기 어려운 것 같아요. 아무것도 보여지지 않는걸 표현한다면 아래와 같이 할 수 있어요.

```js
expect(container).toBeEmptyDOMElement();
```

See also
  - https://github.com/testing-library/jest-dom#tobeemptydomelement

2020-10-18 13:04 UTC, hyejineee commented
급하게 구현하느라 엉망인 부분이 있네요,,,😅  이부분들은 월요일에 리팩토링해서 커밋하도록 하겠습니다.!!

2020-10-18 13:47 UTC, hannut91 requested changes

2020-10-18 13:47 UTC, hannut91 commented on src/App.test.jsx
> +    ],
테스트에서 사용되는 데이터들이 반복해서 사용되고 있습니다. 테스트용 데이터를 미리 만들어놓고 사용하여 중복을 줄일 수 있고, 테스트의 복잡성을 낮출 수 있습니다. 또 복잡한 계산같은 경우 믿고 이미 테스트가 된 데이터들을 저장해놓을 수 있습니다. 이러한 테스트용 데이터를 fixture라고 부릅니다. fixtures라는 폴더를 하나 만들고 여기에 테스트용 데이터들을 모아놓고 가져다가 사용하는건 어떨까요?

2020-10-18 13:47 UTC, hannut91 commented on src/InputContainer.jsx
> +  }
세 함수 모두 비슷한 일을 하고 있는 것 같아요. 무언가가 반복된다면 중복을 제거해야겠다는 신호로 받아들이면 좋습니다. 어떻게 하면 중복을 없앨 수 있을까요?

2020-10-18 14:19 UTC, hyejineee commented on src/App.test.jsx
> +  describe('first loaded', () => {
넵넵!!

2020-10-18 14:21 UTC, hyejineee commented on src/App.test.jsx
> +      expect(getByText(/마녀주방 | 한식 | 서울시 강남구/)).not.toBeNull();
화면에서 텍스트 찾는 거는 굳이 getByText를 사용하여 element를 얻을 필요가 없겠네요ㅎㅎㅅㅎ 수정하겠습니다!

2020-10-18 14:22 UTC, hyejineee commented on src/InputContainer.test.jsx
> +  useDispatch.mockImplementation(() => dispatch);
넵 알겠습니다!!

2020-10-18 14:23 UTC, hyejineee commented on src/Item.jsx
> +}
주소를 장소라고 착각하고 있었네요ㅎㅎㅅㅎ. 그럼 restaurantInfo라고 하면 어떨까요???

2020-10-18 14:23 UTC, hyejineee commented on src/ListContainer.test.jsx
> +        }));
넵 알겠습니다!!

2020-10-18 14:28 UTC, hyejineee commented on src/ListContainer.test.jsx
> +    });
그러면 `doesn't work`대신에 `dosen't show the list`로 바꾸면 어떨까요???? 위에서 container로 텍스트를 찾는 것과 같은 방법으로 통일 시켜주는 것은 잘 읽히는 테스트를 작성하는 것과 상관이 없을까요???

2020-10-18 14:35 UTC, hyejineee commented on src/App.test.jsx
> +    ],
오호... 한 번 해보겠습니다!!

2020-10-18 14:37 UTC, hyejineee commented on src/InputContainer.jsx
> +  }
자꾸 계산기 사칙연산 버튼 만들었던 방법이 생각나네요,,,ㅎㅎㅎ 한 번 해보겠습니다!!

2020-10-18 14:40 UTC, hannut91 commented on src/Item.jsx
> +}
`info`는 어떤 의미를 드러내나요?

2020-10-18 14:42 UTC, hannut91 commented on src/ListContainer.test.jsx
> +    });
주어진 텍스트가 안보여야 하는 것보다 비어있다는게 좀 더 명확할 것 같아요

2020-10-18 14:44 UTC, hyejineee commented on src/Item.jsx
> +}
레스토랑정보여.......😅  props로 따로따로 보내는 것 보다 레스토랑 정보로 묶은 다음 내려주고 뽑아서 사용하는게  좋다고 생각했는데 아닐까여...??

2020-10-18 14:46 UTC, hyejineee commented on src/ListContainer.test.jsx
> +    });
오.. 그런 것 같아요.. 다른 내용들도 보이면 안되는 거니까.. 역시👍🏻👍🏻👍🏻👍🏻

2020-10-18 14:50 UTC, hannut91 commented on src/Item.jsx
> +}
`restaurant`으로 해도 충분할 것 같아요 ㅎㅎ

2020-10-18 14:56 UTC, hyejineee commented on src/Item.jsx
> +}
넵넵ㅎㅅㅎ 알겠습니다ㅏㅎㅎㅎㅎㅎ

2020-10-20 04:27 UTC, hyejineee commented on src/ListContainer.test.jsx
> +        }));
이렇게 수정해봤는데 컴포넌트가 moking한 selector를 인식???을 못하는 것 같아요!! it 안에 작성해주니 제대로 동작합니다!

2020-10-20 13:52 UTC, hannut91 commented
슬랙 채널에 회고를 남겨주셔서 머지합니다 ㅎㅎ 바쁜데도 과제를 열심히 잘 수행해주셨어요. 고생하셨습니다 ㅎㅎ

2020-10-20 13:52 UTC, merged