[4주차 과제2] 레스토랑 정보 확인 및 예약 시스템 구축하기
CodeSoom/react-week4-assignment-2 pull request #33
Opened 2020-10-17 13:43 UTC by juunini

# 과제 목표
- [x] TDD로 기능 구현
- [x] 레스토랑 목록 보기 기능
- [x] 레스토랑 추가 기능

2020-10-17 13:48 UTC, juunini commented
# 작업내용
- 과제 목표 달성

# 알게된 것
- 과제의 의도와 맞지 않다고 하셔서 전부 날리고 하려고 git reset 후 force push를 했더니 PR이 자동으로 close 되어버렸다.
  - force push는 신중하게 사용하자.

# 느낀 점
- 그냥 해볼 땐 RED - GREEN - REFACTORING 으로 하고있는줄 알았는데 실제로 해보니 뒤죽박죽으로 되어버렸습니다.
- RED - GREEN 까지는 되는데 REFACTORING이 안되는걸 보니 너무 처음부터 테스트를 상세하게 작성했나 싶습니다.
- redux가 아직 익숙하지 않아서인지 개념이 완벽히 이해되지 않아서인지(아마도 둘 다) 아직 잘 사용할 수 없었습니다.

2020-10-17 23:53 UTC, Kihyun92 requested changes
충분히 `RED - GREEN - REFACTORING`를 잘하고 계신 것 같아요~ `REFACTORING`은 한번에 완벽하게 할 수 없다고 생각해요. 말씀하신대로 처음부터 너무 상세한 테스트를 작성하는 것도 `RED - GREEN - REFACTORING` 사이클을 빠르게 가져가지 못하는 이유가 될 것 같네요 :)

`Redux`가 처음이라 어려우실 수 있지만, 결국 우리가 이걸 왜 쓰게 됐는지(첫주 과제부터 지금까지의 과정이 담겨있다고 생각합니다) 한번 떠올려보시고 구현에 필요한 기술들을 공부해보시면 금방 적응하실거에요~! 👍

2020-10-17 23:53 UTC, Kihyun92 commented on src/containers/InputReservationContainer.jsx
> +  }
이 세개의 함수들은 레스토랑 정보를 input에서 받아 `dispatch`해주는 비슷한 역할을 하는데 한개의 함수로 처리할 수 없을까요?

2020-10-17 23:53 UTC, Kihyun92 commented on src/containers/InputReservationContainer.jsx
> +
props가 굉장히 많아졌네요. 레스토랑 정보라는 공통된 관심사를 가지는 `name, category, address`는 객체로 묶어 관리하면 어떨까요?

2020-10-17 23:53 UTC, Kihyun92 commented on src/modules/reducer.js
> +};
```suggestion
const initialReservation = {
  name: '',
  category: '',
  address: '',
};

const initailState = {
  newId: 1,
  reservations: [],
  reservation: initialReservation,
}
```

이렇게 한번 더 추상화 해준다면 코드 전반적으로 중복 로직이 제거될 것 같아요~

2020-10-18 03:43 UTC, juunini commented
# 작업 내용
- reducer의 initialState 변경 (reservationName, ... 하던 것들을 reservation: {name, ...} 으로 변경)
- reducer와 actions의 updateReservation... 하던 부분들을 통합
- InputReservation component의 props 통합 (values, onchange)

# 알게된 것
- 남이 한걸 보면 잘 훈수 두는데 내가 한건 왜 안보이는건지...

# 느낀 점
- 리펙토링도 테스트 코드가 작성된 가운데 하니 굉장히 수월했습니다.
  - TDD를 하기 전에는 한 부분 고치면 연관된 부분들이 오작동해서 찾아다니느라 고생했는데
     테스트 코드가 잘못된 부분을 알려주니 수정하기 용이했습니다.
  - 테스트 코드도 같이 수정해야 했지만 전에 했던 고생들에 비한다면 기꺼히 받아들일 수 있었습니다.
  - 리듀서 단계부터 통합을 진행하니 컴포넌트에서 아래 같은 일을 하는것이 맞는가 하는 고민을 하게 되었습니다.
     onChange에 저렇게 component인데 값을 넣어줘도 괜찮은가 하는 고민입니다.
     `src/components/InputReservation.jsx` line 12 ~ 18

```javascript
<input
  type="text"
  name="name"
  value={name}
  placeholder="이름"
  onChange={(event) => onChange({ target: 'name', event })}
/>
```

2020-10-18 05:44 UTC, Kihyun92 requested changes
내가 만든 코드를 보고 개선점을 찾는게 가장 어려운것 같아요😂

말씀하신대로 TDD를 적극 활용하여 리펙토링 해보면 좋겠습니다~ 👍

2020-10-18 05:44 UTC, Kihyun92 commented on src/components/InputReservation.jsx
> +        onChange={(event) => onChange({ target: 'name', event })}
target을 각각의 input의 name 속성으로 지정해주는 것 외에는 같은 기능을 하는 것 같아요~ 함수로 따로 빼서 처리해 주는건 어떨까요?
```
function handleChange (event) {
  const { target: { name, value }} = event;
  onChange({ name, value });
}
```

2020-10-18 05:44 UTC, Kihyun92 commented on src/containers/InputReservationContainer.jsx
> +  }
`Object Literal Lookup`을 사용해서 처리해보신것 같아요~ 예외처리가 필요한 경우에는 매우 유용할 수 있지만, 이 경우에는 바로 ditpatch에서 action을 호출하는게 좋아보여요.

```suggestion
  function handleChange({ event, target }) {
    const { value } = event.target;
    dispatch(updateReservation({target, value}));
  }
```

2020-10-18 05:44 UTC, Kihyun92 commented on src/modules/reducer.js
> +      return targets[target];
공통 코드가 많아보여요~ 조금 더 단순화할 순 없을까요?
`Object literal lookup` 방식이 경우에 따라서 예외처리를 제거하고 코드를 명확히 하는 용도로는 좋지만, 자칫 중복 코드가 많아지는 문제가 발생할 것 같아요.

2020-10-18 06:22 UTC, juunini commented on src/components/InputReservation.jsx
> +        onChange={(event) => onChange({ target: 'name', event })}
아, event.target.name을 하면 name속성을 받는다는걸 처음 알았습니다 ㅠㅠ
덕분에 코드가 많이 줄었어요

2020-10-18 06:23 UTC, juunini commented on src/containers/InputReservationContainer.jsx
> +  }
그러고보니 if문이 필요 없이 그냥 넣으면 되는 부분이었군요 ㅠㅠ

2020-10-18 06:34 UTC, juunini commented on src/modules/reducer.js
> +      return targets[target];
덕분에 저 부분 전체를

```javascript
      return {
        ...state,
        reservation: {
          ...reservation,
          [target]: value,
        },
      };
```

이렇게 바꿀 수 있었습니다.
대괄호 넣고 변수 넣어서 필드명을 맞추는 그런 코드를 어디서 본 적이 있는 것 같아서 시도해봤는데
잘 되더군요 ㅠㅠ 덕분에 중복 다 없애버리고 간결하게 표시할 수 있었습니다. 감사합니다.

2020-10-18 14:24 UTC, Kihyun92 approved these changes
고생하셨습니다~ Redux에 TDD를 접목하는데에 익숙치않다고 하셨는데, 충분히 잘해주신 것 같아요 👍  
과제풀이 영상을 통해서 `Red-Green-Refactoring` 사이클을 어떤식으로 반복하는지 봐보시면 좋을 것 같아요~
이번 과제를 통해서 무엇을 배우셨나요? 아쉬웠던 부분이나 더 시도해보고 싶은게 있나요? :)

2020-10-18 20:49 UTC, juunini commented
다른 책이나 블로그들을 보면서 redux를 익힐 땐 뭔지 제대로 알 수도 없는데 따라해봐도 모르겠고 이해도 안갔었는데
이번 과제를 통해 그런 책이나 블로그에서는 보지 못했던 더 기본적인 형태의 redux를 접하게 되어서 잘 이해할 수 있었습니다 ㅠㅠ

사실 redux하면 잘 모르겠다는 생각 때문에 막연히 어려울거다 생각했는데
생각보다 쉽게 잘 써져서 좀 놀랐어요.

---

풀이를 보고나니 RED - GREEN 두 단계에서 너무 자세히 써버려서 그렇구나 라는걸 깨달았습니다.
앞으로도 계속 TDD를 수련해서 생활화 시키고 싶어요.
뭐 하나 고치고 나면 에러를 찾으러 떠나는 길고 긴 여정보다 훨씬 낫네요 ㅠㅠ

2020-10-19 13:27 UTC, merged