즐거운 TDD 레스토랑 🍔🍕🍟
CodeSoom/react-week4-assignment-2 pull request #35
Opened 2021-02-17 07:58 UTC by dodoongtak

2021-02-17 15:30 UTC, Kihyun92 commented
오 시작에 앞서 유저 스토리를 잡아보신 것 좋네요! 👍🏼 

미리 고민하고 작업하는게 확실히 더 도움이 되는 것 같습니다 ㅎㅎ

2021-02-18 12:00 UTC, dodoongtak commented
## TDD 진행 계획 순서
UI -> Reducer -> Container

### UI
- 무엇을 그려 놓을지 test 기반으로 화면 작성

### Reducer
- 무엇이 작동 될 것인지 test 기반으로 Feature 작성

### Container 
- UI를 관심사를 두지않는 Component에 Feature를 주입

## 질문
### 1. Red -> Green 이 끝나고 Refactoring이 종종 막힙니다. 
TDD 사이클 중 리팩토링을 어는 부분을 건드려야될지 감이 잡히다가도 안잡힙니다. 

간단한 테스트 경우, 기반대로 작성하면 끝이라, 종종 🔵는 무엇을 할지 모르겠습니다.

막혀서 리팩토링 커밋을 못 남긴 부분들 https://github.com/CodeSoom/react-week4-assignment-2/pull/35/commits/2c640194e9e92789b07f330f95a6a5a1e21e4b15 https://github.com/CodeSoom/react-week4-assignment-2/pull/35/commits/3a5dad663c510483549ae159bc6d95f1efa262bc  

### 2. Reducer를 사용한다고 생각하니, 이전에 기능을 따로 안만들고 Reducer부터 만들려 하게됩니다. 

더구나 Reduce를 사용할것이니, App에는 따로 state를 처리 안하고, reducer 완성 후 container를 만들어 웹사이트가 작동되게 만드는  Flow로 이어지는데... 

뭔가 길을 잘 못 걷는거 같습니다.

2021-02-18 15:50 UTC, Kihyun92 requested changes
> 1. Red -> Green 이 끝나고 Refactoring이 종종 막힙니다.
TDD 사이클 중 리팩토링을 어는 부분을 건드려야될지 감이 잡히다가도 안잡힙니다.
간단한 테스트 경우, 기반대로 작성하면 끝이라, 종종 🔵는 무엇을 할지 모르겠습니다.
막혀서 리팩토링 커밋을 못 남긴 부분들 2c64019 3a5dad6

위에 적어주신 두 커밋은 테스트를 성공시키기 위해 만든 부분이 아닌가요? 이 과정은 리팩터링은 아닌 것 같아요.
리팩터링 과정은 예를 들면 위 커밋에서 `handleChange`, `handleClick`을 위한 props를 추가하고, 상위 컴포넌트에도 `function handleChange() { ... }`과 같이 대충 비어있는 함수를 만들어요. 일단 성공시키기 위해서요(`Green`) 그럼 이 핸들러 함수를 실제로 구현하는 과정이 `refactoring`이 될거에요.
이해하시는데 조금 도움이 됐을까요? 😊

> 2. Reducer를 사용한다고 생각하니, 이전에 기능을 따로 안만들고 Reducer부터 만들려 하게됩니다.
더구나 Reduce를 사용할것이니, App에는 따로 state를 처리 안하고, reducer 완성 후 container를 만들어 웹사이트가 작동되게 만드는 Flow로 이어지는데...
뭔가 길을 잘 못 걷는거 같습니다.

한번 작게 시작해보는건 어떤가요? 예를 들면 당장 컴포넌트를 `render`하는 것부터 테스트를 만들어가는거죠. 그러다보면 상태를 변경해야할때가 오고 자연스레 `reducer`를 구현해야하는 단계가 오지 않을까요?

2021-02-18 15:50 UTC, Kihyun92 commented on src/RestaurantForm.test.jsx
> +  const restaurantInformation = {
레스토랑 정보를 담고 있는 객체이기 때문에 `restaurant` 라고만 해도 되지 않을까요?

2021-02-18 15:50 UTC, Kihyun92 commented on src/RestaurantForm.test.jsx
> +  const informations = Object.values(restaurantInformation);
`restaurants`는 어떤가요? :)

2021-02-18 15:50 UTC, Kihyun92 commented on src/RestaurantForm.test.jsx
> +    expect(handleChange).toBeCalled();
어떤 값과 함께 호출이 됐는지 확인해봐도 좋을 것 같아요~

2021-02-18 15:57 UTC, dodoongtak commented on src/RestaurantForm.test.jsx
> +    expect(handleChange).toBeCalled();
고것은.... 나중에 컨테이너에서 할 계획이였습니다 ㅎㅎㅎㅎ 등록 버튼이 눌려서 함수가 호출되는지만 확인하고 싶었어요.

2021-02-18 18:22 UTC, dodoongtak commented on src/RestaurantForm.test.jsx
> +  const informations = Object.values(restaurantInformation);
restaurants는 여러 개의 레스또랑으로 해석 될 수도 있으니
레스또랑의 데이터니까 restaurantData로 변경해봤습니다!

2021-02-19 11:47 UTC, dodoongtak commented on src/RestaurantFormContainer.jsx
> +  const ids = {
이쪽만을 커버를 못했습니다 ㅠㅠㅠㅠㅠㅠㅠ

어떻게 테스트코드를 작성 할 지 방도를 못 찾았습니다.

빛을...내려주실 수 있을까요?

2021-02-19 11:58 UTC, dodoongtak commented
![image](https://user-images.githubusercontent.com/77006427/108501525-c5bcbf00-72f4-11eb-9738-a9c441c3a4a3.png)

https://github.com/CodeSoom/react-week4-assignment-2/pull/35#discussion_r579127800 이 객체에 함수들에 대해 테스트를 작성하지 못하였습니다... 방도를... 방도를... 모르겠습니다 :( 

UI 완성 후 Reducer에 하나 Feature 완성해서 Container로 뿌리고 필요한 Reducer 작성하고 Container 작성하는 형식으로 
TDD를 진행해봤습니다. 

🔵 하는 방도를 피드로 알려주셨지만... 🟢를 빨리 시키고 🔵리팩토링 해야되는데, 리팩토링으로 바로 달려 구현해서 🔵를 찍기 어려웠습니다 ㅎㅎㅎ....

2021-02-19 13:25 UTC, dodoongtak commented on src/RestaurantFormContainer.jsx
> +  const ids = {
해결 완료.... 굳이 이렇게 ids 안만들어도 됐었네요 ㅎㅎㅎㅎ

2021-02-19 17:02 UTC, Kihyun92 requested changes
리팩터링에 너무 스트레스 안받으셨으면 좋겠어요 ㅎㅎ 충분히 잘 진행하고 계십니다 👍🏼 

가능하면 `Red-Green-Refactoring`의 사이클이 짧게 반복되는게 좋은 거지, `Red-Green-Refactoring-Refactoring-Refac..`의 사이클로 진행해도 문제되지 않으니까요 :)

2021-02-19 17:02 UTC, Kihyun92 commented on src/RestaurantForm.test.jsx
> +  it('renders input elemetns', () => {
오타가 있네요 ㅎㅎ

2021-02-19 17:02 UTC, Kihyun92 commented on src/reducer.js
> +    if (restaurantData.includes('')) { return state; }
이 처리는 왜 필요하게 된 걸까요? 레스토랑 인풋 폼에 데이터가 없는 경우를 위해 처리한건가요? 🤔

그렇다면 reducer 이전에 form 영역에서 처리해주는건 어떨까요? 예를들면 버튼을 disabled 시키는 방법이 있을 것 같아요.

2021-02-19 17:02 UTC, Kihyun92 commented on src/reducer.js
> +      },
`initialState` 에서도 초기화를 위해 비슷한 코드가 사용되는 것 같아요.

초기 레스토랑 정보를 객체로 만들어서 공통으로 사용하면 어떨까요? 변경되는 id 외의 값들은 전개 문법(...) 으로 처리할 수 있을 것 같아요 ㅎㅎ

2021-02-20 09:42 UTC, dodoongtak commented on src/RestaurantForm.test.jsx
> +  it('renders input elemetns', () => {
![image](https://user-images.githubusercontent.com/77006427/108591287-52c24f80-73ab-11eb-9d35-d84cf56001b5.png)

감사합니다!

2021-02-20 09:47 UTC, dodoongtak commented on src/reducer.js
> +      },
아 initalState에 있는 값을 ... 풀어서 id+1 과 object merge 해서 넘기도록 조치할꼐요.

이미 있는 코드인데 활용을 못했네요 ㅎㅎ

2021-02-20 10:22 UTC, dodoongtak commented on src/reducer.js
> +    if (restaurantData.includes('')) { return state; }
4-1 에서 reducer에서 taskTitle이 없을 경우에는 state를 그대로 return 하는 방식을 택해서, 같은 방식을 적용해봤었습니다. 

reducer에서도 test 할 수 있는걸 formContainer에서 처리를 하라고 하셨을까 의도를 생각해봤는데, 
이것도 어떻게 보면 관심사의 분리가 이유가 아닐까 생각해봤습니다. 

reducer는 들어온 값 그대로 또 다른 if문 없이 받은 state 그대로 돌려주는게 주된 관심이고, 
FormContainer는 handleClick을 통해 dispatch 함수를 실행하는게 주된 관심이니, 

"굳이 필요없는 정보를 필터링해서 dispatch 함수 실행을 최소화 하자"는 함수 실행의 관심사에 속해 있다 라 이해하고

변경시켜봤습니다 :)

2021-02-20 13:22 UTC, Kihyun92 commented on src/reducer.js
> +    if (restaurantData.includes('')) { return state; }
저희 팀에서는 여러 input에 대한 관리를 편하게 하기 위해 [React-Hook-Form](https://react-hook-form.com/kr/)을 사용하기도 합니다 ㅎㅎ

2021-02-20 13:26 UTC, Kihyun92 approved these changes
고생하셨습니다~ TDD cycle을 직접 다뤄보는 쉽지 않은 한주였는데 잘해주신 것 같아요 👍🏼 

강의 풀이 영상도 잘 봐보신 것 같아요 😊  

이번 과제를 통해 무엇을 배우셨나요? 더 해보고 싶은게 있나요?

슬랙 채널에 회고 작성해주시면 머지하도록 하겠습니다 :)

2021-02-23 14:52 UTC, merged