Feature/restaurant tdd
CodeSoom/react-week4-assignment-2 pull request #38
Opened 2021-02-18 06:35 UTC by bluel00

선 PR 후작업

1. 테스트파일 만들기
2. 하드코딩으로 통과시키기
3. 리펙터링

- 린트가 에러를 뱉어서 test파일을 jsx로 수정했습니다.

## TODO
- 관심사의 분리
- Input 
- List

2021-02-18 16:03 UTC, Kihyun92 requested changes
작업하신 커밋들을 보니 TDD Cycle을 잘 지키면서 하고 계신 것 같아요! 👍🏼

2021-02-18 16:03 UTC, Kihyun92 commented on src/App.jsx
> +  const tasks = [
수정하실 예정이셨겠지만, `restaurants`가 좋겠네요 ㅎㅎ

2021-02-18 16:03 UTC, Kihyun92 commented on src/App.jsx
> +      title: '마녀주방 | 한식 | 서울시 강남구',
레스토랑의 정보들인 것 같아요. 객체로 처리해도 좋겠네요~

2021-02-18 16:03 UTC, Kihyun92 commented on src/App.test.jsx
> +    getByText(/등록/);
`getBy*`는 해당 요소를 찾지 못하면 에러가 발생해서 충분히 테스트 가능하지만, `assert` 문으로 작성한다면 의도를 더 분명히 할 수 있을 것 같아요~

`expect(getByText('등록')).not.toBeNull();`

2021-02-18 16:03 UTC, Kihyun92 commented on src/App.test.jsx
> +    ));
App 컴포넌트를 랜더해주는 부분이 중복되는 것 같아요~ 

중복되는 코드는 항상 리팩터링의 대상입니다 ㅎㅎ

2021-02-19 07:36 UTC, bluel00 commented on src/App.jsx
> +  const tasks = [
허.. 이런 실수를;
수정했습니다.

2021-02-19 07:37 UTC, bluel00 commented on src/App.jsx
> +      title: '마녀주방 | 한식 | 서울시 강남구',
네 수정했습니다.

2021-02-19 07:38 UTC, bluel00 commented on src/App.test.jsx
> +    getByText(/등록/);
의도를 알기 쉽도록 
assert문으로 수정했습니다.

2021-02-19 07:39 UTC, bluel00 commented on src/App.test.jsx
> +    ));
네 describe 내부에 함수로 추출했습니다. 🐱‍👤

2021-02-19 17:09 UTC, Kihyun92 requested changes
TDD cycle을 잘 지키면서 차근차근 잘 하고 계신 것 같아요 👍🏼  

가능하면 테스트는 항상 성공한 상태로 유지해주세요~

2021-02-19 17:09 UTC, Kihyun92 commented on src/AddForm.jsx
> +export default function AddForm() {
레스토랑 정보를 받는 부분들을 form 컴포넌트로 만들어보셨군요 ㅎㅎ

컴포넌트 네이밍을 `AddForm` 보다는 `RestaurantForm`은 어떤가요? 🤔

2021-02-20 15:09 UTC, Kihyun92 requested changes
커밋 메시지에 `테스트 생성, 테스트 수정, 테스트 통과` 와 같은 메시지도 좋지만, 추가로 어떤 것을 위한 테스트인지에 대한 부분도 작성해주면 좋을 것 같아요~ 

동료들이 커밋 메시지만 보고도 어떤 작업을 했는지 유추가능해야합니다.

2021-02-20 15:09 UTC, Kihyun92 commented on src/RestaurantForm.test.jsx
> +    const input = getByPlaceholderText('이름');
placeholder 값으로 인풋 요소를 가져와서 테스트해보셨네요. placeholder 값은 추후 변경이 될 가능성이 있는 속성같아요.

input에 name 속성으로 고유한 네이밍을 해주는건 어떨까요?

2021-02-21 13:18 UTC, Kihyun92 commented
@bluel00 님~ 어떻게 진행되고 있나요? 😊 

![image](https://user-images.githubusercontent.com/35797540/108626301-c55a2a80-7492-11eb-80ea-7800c86fa082.png)

현재 테스트들이 실패한 상태인 것 같아요~ 항상 성공한 상태로 작업해보시면 좋을 것 같습니다.

그리고 과제 풀이 영상을 꼭 보시면 좋을 것 같습니다~ 직접 나머지 부분도 해보셔도 좋구요 ㅎㅎ

2021-02-21 23:53 UTC, bluel00 commented
이번 과제는 시간안에 못마쳤습니다.😡
나머지 부분 꼭 정리하고 넘어가겠습니다!!

2021-05-16 09:34 UTC, merged