Implement restaurant app
CodeSoom/react-week4-assignment-2 pull request #4
Opened 2020-06-27 08:52 UTC by naraekn

우선 진행된데까지만이라도 푸시해놓고 덧붙이겠습니다~!!

2020-06-27 12:24 UTC, wholemann requested changes
역시 잘해주셨군요ㅎㅎ

남겨드린 comment 바탕으로 좀 더 고민해보시면 좋겠습니다.

질문은 언제든 DM 환영합니다!

2020-06-27 12:24 UTC, wholemann commented on src/App.jsx
> +  address: '',
이 3개는 하나로 묶는게 맞을 듯 합니다. restaurant 한 곳에 관련된 정보니까요.

2020-06-27 12:24 UTC, wholemann commented on src/App.jsx
> +}
그렇다면 이 action creator는 하나로 합칠 수 있겠죠?

2020-06-27 12:24 UTC, wholemann commented on src/App.test.jsx
> +  expect(getByText(`${name} | ${category} | ${address}`)).not.toBeNull();
좋네요!

2020-06-27 12:24 UTC, wholemann commented on src/List.jsx
> +          </li>
```suggestion
        <li key={restaurant.id}>
          {restaurant.name}
          {' '}
          |
          {' '}
          {restaurant.category}
          {' '}
          |
          {' '}
          {restaurant.address}
        </li>
```

2020-06-27 12:24 UTC, wholemann commented on src/ListContainer.jsx
> +export default function ListContainer() {
RestaurantsContainer가 좀 더 명확할 거 같아요.

단순히 List로는 어떤 목록인지 표현되지 않습니다.

2020-06-27 12:24 UTC, wholemann commented on src/actions.js
> +}
하나로 합칠 수 있겠네요.

2020-06-27 12:24 UTC, wholemann commented on src/actions.js
> +  };
clickSubmit은 액션을 일으키기 위한 행위이지

action 자체를 나타내진 않습니다.

이 부분은 무엇을 위한 action인지 생각해보면 좋겠군요:)

2020-06-27 12:24 UTC, wholemann commented on src/reducer.js
> +}
위의 피드백을 바탕으로 이 부분도 많은 개선이 가능할 겁니다.

더불어 if문을 안 쓰려면 어떻게 해야할까요? 계산기 과제를 돌이켜 보시면 답이 있습니다:)

2020-06-27 12:39 UTC, naraekn commented on src/List.jsx
> +          </li>
오 이렇게도 표현이 가능하겠네요ㅎㅎㅎ

2020-06-27 18:31 UTC, naraekn commented
정말..ㅎㅎ 최선을 다하고 있는데 쉽지 않군요 흑흑..

위에서 말씀해주신 피드백을 대부분 반영했습니다. ```if```없이 코드를 작성하는 부분에 대해서는 우선 홀딩했습니다 ```reducer```에 대한 테스트에서 action type이 없는 경우, initial execution인 경우도 테스트를 하고 있는데, if 없이 하려니까 처리가 쉽지가 않더라고요ㅠㅠ.. 우선 완성까지 해보고, 시간이 된다면 더 고민해보겠습니다.

내일은,
1) 오전피드백 내용 반영
2) ```useEffect```사용
3) 리팩터링 (특히, 현재 테스트 코드에 중복 많음)

작업을 할듯합니다ㅎㅎ 
해볼수있는데까지 해볼게요😭😭

2020-06-28 05:50 UTC, wholemann requested changes
네 기다리고 있겠습니다. 지금은 좋네요ㅎㅎ 말씀하신대로 중복이 좀 있어서 그 부분만 제거하면 좋겠습니다.

useEffect는 초기값 설정 때문에 App에서 사용하셔야 합니다ㅎㅎ

2020-06-28 05:50 UTC, wholemann commented on src/App.test.jsx
> +import { changeRestaurant, saveNewRestaurant } from './actions';
한 줄 띄우면 좋겠네요.

2020-06-28 05:50 UTC, wholemann commented on src/App.test.jsx
> +      expect(dispatch).toBeCalledWith(changeRestaurant('name', name));
```suggestion
      fireEvent.change(getByPlaceholderText(/이름/), { target: { value: name } });
      
      expect(dispatch).toBeCalledWith(changeRestaurant('name', name));
```

한 줄 씩 공백 넣어주세요~

2020-06-28 12:35 UTC, naraekn commented
```useEffect```는  제가 만들어놓은 state구조에 맞게(?) 사용해봤어요!
그리고 테스트코드에 있는 중복들을 최대한 제거하고 말씀해주신 띄어쓰기도 반영했습니다

2020-06-28 13:55 UTC, wholemann approved these changes
이정도면 merge해도 충분하겠습니다. 고생하셨어요.

반드시 아샬님 피드백 강의를 보시고 어떤 부분에서 어떻게 다르게 했는지를

꼭 복습해보시고 다음주 과정에 임하시면 좋겠습니다:)

이번주도 정말 고생하셨어요:)

2020-06-28 13:55 UTC, wholemann commented on fixture/test-data.js
> +};
이 부분은 필요가 없을 것 같네요.

그냥 테스트 안에서 하나 잡아주는 게 오히려 파악하기 쉬울 것 같아요.

2020-06-28 13:55 UTC, merged