Book restaurant
CodeSoom/react-week4-assignment-2 pull request #40
Opened 2021-02-18 10:24 UTC by datalater

4주차 2번 과제 제출합니다.

## 진행상황

### 2020.02.18(목)

* App에 레스토랑 타이틀이 나오는지 TDD
* 레스토랑 추가를 위한 입력이 있는지 TDD
* 레스토랑 목록이 있는지 TDD

## TODO

* App의 상태관리 코드를 reducer로 분리한다.
* redux 아키텍처를 적용한다.
* container 컴포넌트와 presentational 컴포넌트로 책임을 분리한다.

## 궁금한 점

## 요청 받은 코드 리뷰 목록

## 메타인지

### 내가 모르는 것은 무엇인가

### 내가 알게 된 것은 무엇인가

### 어떻게 하면 더 나을까
 
## 주간회고

2021-02-18 10:25 UTC, datalater commented
커버리지 결과를 첨부합니다.

![image](https://user-images.githubusercontent.com/8105528/108343223-0c3fea00-721f-11eb-9762-1add7362c92f.png)

2021-02-18 10:28 UTC, datalater commented on src/List.test.jsx
> +  });
"레스토랑 목록이 없을 경우 아무 정보도 표시하지 않는다"를 테스트하려고 합니다.

일단 레스토랑 목록을 추가하면 반드시 파이프(|) 문자가 들어가므로 파이프 문자가 없는지 확인하도록 테스트를 작성했는데, 뭔가 올바르지 않은 느낌입니다. 🤔

어떻게 접근해보면 될까요?

2021-02-18 16:14 UTC, Kihyun92 commented on src/List.test.jsx
> +  });
`restaurants`가 빈 배열인 경우에 대한 처리를 해주면 되지 않을까요? ☺️

```javascript
if (restaurants.length === 0) {
  return (
    <p>입력된 레스토랑 정보가 없습니다.</p>
  )
}
```

2021-02-18 16:28 UTC, Kihyun92 requested changes
작업하신 커밋들을 보니 TDD Cycle을 잘 지키면서 하고 계신 것 같네요 ㅎㅎ

그런데 커밋 메시지가 뭔가 `~~를 했어요.` 라고 동료에게 알려주는게 아니라 `~~를 해라!` 라고 하는 것 같은 느낌이 드네요 😂

그리고 App 컴포넌트에서 우선 상태 관리를 해보신 것 같아요. 
앞서 Redux로 상태관리를 할 것을 알기 때문에 기능들을 하나씩 구현할때마다 `reducer`를 통해 관리하는 과정으로 이어가는 방법도 있을 것 같아요 ㅎㅎ

물론 지금 방법도 괜찮습니다 ㅎㅎ 우선은 익숙하신대로 해보시는게 좋은 것 같아요 👍🏼

2021-02-18 16:28 UTC, Kihyun92 commented on src/Input.jsx
> +      />
각각의 인풋 영역들을 컴포넌트로 나눠보셨군요! 

각 컴포넌트들이 name만 다르지 같은 기능을 하는 것 같아요. 혹시 하나의 컴포넌트로 처리할 수는 없을까요?

2021-02-18 16:28 UTC, Kihyun92 commented on src/App.jsx
> +        },
이 부분도 이렇게 처리해줄 수 있을 것 같아요~
```suggestion
        {
          ...state
        },
```

2021-02-18 16:28 UTC, Kihyun92 commented on src/App.jsx
> +    const { name: targetName, value } = event.target;
`targetName`으로 한번 더 맵핑하신 이유가 있나요?

```suggestion
    const { name, value } = event.target;
```
이렇게만 해줘도 target의 name 정보인걸 알 수 있을 것 같아요.

2021-02-19 11:42 UTC, datalater commented on src/List.test.jsx
> +  });
아하 ㅋㅋ 예제를 무조건 똑같이 구현한다고 생각해서 메시지를 새로 추가할 생각을 못했네요 ㅎㅎ  반영하겠습니다.

2021-02-19 11:48 UTC, datalater commented
> 그런데 커밋 메시지가 뭔가 `~~를 했어요.` 라고 동료에게 알려주는게 아니라 `~~를 해라!` 라고 하는 것 같은 느낌이 드네요 😂

아, 그렇게 느낄 수도 있겠네요 ㅎㅎ 다만 git commit message guide에서 imperative 형태로 쓰라는 것을 한글로 적용해서 명령문 형태로 작성했습니다. 물론, 말씀하신 것처럼 명령문이 불친절하게 느껴진다면 "리팩토링 하라"를 "리팩토링 한다"라고 써도 상관은 없겠네요. 개인적으로 쓰던 버릇이라 팀 컨벤션이 있다면 그걸 따르도록 하겠습니다ㅎㅎ

> 그리고 App 컴포넌트에서 우선 상태 관리를 해보신 것 같아요.
> 앞서 Redux로 상태관리를 할 것을 알기 때문에 기능들을 하나씩 구현할때마다 `reducer`를 통해 관리하는 과정으로 이어가는 방법도 있을 것 같아요 ㅎㅎ
> 물론 지금 방법도 괜찮습니다 ㅎㅎ 우선은 익숙하신대로 해보시는게 좋은 것 같아요 👍🏼

넵 좋은 의견 감사합니다. 참고하겠습니다!

2021-02-19 12:02 UTC, datalater commented on src/Input.jsx
> +      />
오호 그렇네요. 처리해서 반영하겠습니다.

2021-02-19 12:22 UTC, datalater commented on src/Input.jsx
> +      />
아 그런데 다시 생각해보니 공통 컴포넌트로 처리하면 
placeholder text를 일일이 파라미터로 전달해줘야 하는 불편함이 생길 것 같습니다.
그렇게 되면 각각 인풋 컴포넌트를 랩핑하는 컴포넌트에서 굳이 알지 않아도 될 placeholder text를 알아야 하니 관심사 분리에서도 좀 부적절하지 않을까요?

2021-02-19 12:22 UTC, datalater commented on src/App.jsx
> +        },
엇 그렇네요 리팩토링하다가 놓쳤던 것 같습니다. 감사합니다!

2021-02-19 12:27 UTC, datalater commented on src/App.jsx
> +    const { name: targetName, value } = event.target;
넵 이유가 있습니다.

윗 줄에서 상태를 구조분해할 때

```jsx
const { name, category, address, restaurants} = state;
```
이미 name이라는 키워드를 사용해서 eslint에서 잡아냈기 때문입니다.

![image](https://user-images.githubusercontent.com/8105528/108504477-467dba00-72f9-11eb-9654-42579131b40f.png)

2021-02-19 17:12 UTC, Kihyun92 commented on src/Input.jsx
> +      />
그렇네요 ㅎㅎ 그렇다면 컴포넌트로 처리하지 않는건 어떤가요? 

현재 각 인풋 컴포넌트의 역할은 단순히 props로 넘겨준 것을 input 엘리먼트를 통해 화면에 그려주고만 있어요.

각기 다른 컴포넌트로 분리할 이유가 있는지 한번 점검해봐도 좋을 것 같아요 ㅎㅎ

2021-02-19 17:23 UTC, Kihyun92 requested changes
커밋 메시지를 보니 차근차근 TDD cycle을 지키면서 잘 진행하고 계신 것 같아요~  👍🏼

2021-02-19 17:23 UTC, Kihyun92 commented on src/List.jsx
> +  const isEmpty = (arr) => arr.length === 0;
List 컴포넌트 바깥 쪽으로 추출해도 좋을 것 같네요~

2021-02-19 17:23 UTC, Kihyun92 commented on src/actions.js
> +});
비슷한 역할을 하는 action들 인 것 같아요. 하나의 action으로 처리할 수 없을까요? 🤔

2021-02-19 17:23 UTC, Kihyun92 commented on src/reducer.js
> +  }),
이 부분도 마찬가지로 공통적으로 처리할 수 없을까요?

2021-02-19 17:23 UTC, Kihyun92 commented on src/reducer.test.jsx
> +    it('does nothing', () => {
`doesn't change state`와 같이 조금 더 명확하게 전달하면 좋을 것 같아요~

2021-02-20 01:37 UTC, datalater commented on src/List.jsx
> +  const isEmpty = (arr) => arr.length === 0;
그렇네요 List 컴포넌트 안에 있을 필요가 없네요 ㅎㅎ 감사합니다!

2021-02-20 01:38 UTC, datalater commented on src/actions.js
> +});
음.. 아이디어가 떠오르긴 하는데, 일단 지금 리덕스 아키텍처를 먼저 적용해보고 리팩토링으로 처리해볼게요!

TODO

2021-02-20 01:39 UTC, datalater commented on src/reducer.js
> +  }),
음.. 아이디어가 떠오르긴 하는데, 일단 지금 리덕스 아키텍처를 먼저 적용해보고 리팩토링으로 처리해볼게요!

TODO

2021-02-20 01:40 UTC, datalater commented on src/reducer.test.jsx
> +    it('does nothing', () => {
강의 영상에서 아샬님은 `it doesn't work`라고 하셨는데, state가 변하지 않는다는 구체적인 사항으로 쓰는 게 더 나은 걸까요?

2021-02-20 02:07 UTC, datalater commented on src/App.jsx
> +        },
고쳐 놓고 알았는데, 이럴 경우 state.restaurants가 restaurants에 다시 네스트되어서 안되겠네요

2021-02-20 08:23 UTC, datalater commented on src/List.jsx
> +  const isEmpty = (arr) => arr.length === 0;
3a61a1f

2021-02-20 08:23 UTC, datalater commented on src/actions.js
> +});
956495c

2021-02-20 08:23 UTC, datalater commented on src/reducer.js
> +  }),
956495c

2021-02-20 08:27 UTC, datalater commented
과제 목표에 나오는 움짤대로 작동하도록 만들었는데 `useEffect`를 사용하라는 힌트를 사용하지 않았습니다.

왜 `useEffect`를 사용해야 하는지 설명해주실 수 있나요?

![image](https://user-images.githubusercontent.com/8105528/108589259-f3f7d880-73a0-11eb-80bc-81f06baed40d.png)

2021-02-20 08:33 UTC, datalater commented
리덕스 아키텍처 적용 후 테스트 커버리지 결과를 첨부합니다.

![image](https://user-images.githubusercontent.com/8105528/108589454-adef4480-73a1-11eb-9b3e-15e0f6e98bf9.png)

2021-02-20 14:36 UTC, Kihyun92 commented
> 과제 목표에 나오는 움짤대로 작동하도록 만들었는데 `useEffect`를 사용하라는 힌트를 사용하지 않았습니다.
> 
> 초기 데이터를 렌더링하라고 하는데 미리 restaurant 정보를 입력해두고 그 정보들이 렌더링 되어야 하는걸까요?
> 음... 잘 모르겠네요 ㅎㅎ 왜 `useEffect`를 사용해야 하는지 설명 부탁드립니다 😢
> 
> ![image](https://user-images.githubusercontent.com/8105528/108589259-f3f7d880-73a0-11eb-80bc-81f06baed40d.png)

https://codesoom-group.slack.com/archives/C01JEHR319T/p1613551088004100
관련해서 이전에 논의됐던 슬랙 메시지에요~

이번 과제에서는 API를 이용하여 초기 데이터를 가져오지 않고 있지만, 그걸 고려해 가짜로 데이터를 세팅해주는데 사용해보라는 의미에요. 
미리 레스토랑 정보를 입력해서 노출해보셔도 좋고, 빈 정보로 초기화해주셔도 좋지만, 중요한건 상태값을 초기 데이터로 업데이트 해주기 위해 사용해보라는 의도였습니다.

2021-02-20 15:00 UTC, Kihyun92 requested changes

2021-02-20 15:00 UTC, Kihyun92 commented on src/Input.jsx
> +export default function Input({
인풋들과 버튼이 있어서 Input 이라고만 네이밍하는건 어색해보이는 것 같아요~

2021-02-20 15:00 UTC, Kihyun92 commented on src/InputContainer.jsx
> +    restaurants: state.restaurants,
`restaurants`는 이 컴포넌트에서 사용되지 않는 것 같은데 제거해도 되지 않을까요?

2021-02-20 15:00 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +    }));
`toBeCalledWith` 안에 소괄호가 한번 더 감싸진 이유가 있나요?

2021-02-20 15:00 UTC, Kihyun92 commented on src/List.jsx
> +export default function List({ restaurants }) {
`List`라는 컴포넌트 명보다는 `Restaurants`는 어떨까요?

2021-02-20 15:00 UTC, Kihyun92 commented on src/reducer.js
> +  return !(name !== '' && category !== '' && address !== '');
부정문들으로 처리를 해보셨네요. 부정문으로 예외처리를 하는건 보는이로 하여금 한번 더 생각을 해봐야하기 때문에 가능하면 사용하지 않는게 좋을 것 같아요. 

조금 더 단순하게 처리할 순 없을까요? 🤔

근본적으로 이 예외처리가 필요한 원인이 무엇인가요? reducer에서 처리해줘야하는 부분인가요?

2021-02-20 15:00 UTC, Kihyun92 commented on src/reducer.test.jsx
> +    it('does nothing', () => {
개인적으로는 조금 더 명확했으면 좋을 것 같아서 커맨트 드렸던 부분같아요 ㅎㅎ 본인이 생각하기에 해당 의도를 명확히 드러냈다고 생각되면 지금도 괜찮습니다~

2021-02-21 01:45 UTC, datalater commented on src/InputContainer.jsx
> +    restaurants: state.restaurants,
그러네요. 복사하면서 제거하지 않았군요 😢

2021-02-21 01:46 UTC, datalater commented on src/Input.jsx
> +export default function Input({
`Form`이 낫겠네요 ㅎㅎ

2021-02-21 01:47 UTC, datalater commented on src/InputContainer.test.jsx
> +    }));
오타네요 😢

2021-02-21 01:47 UTC, datalater commented on src/List.jsx
> +export default function List({ restaurants }) {
네 Restaurants가 더 낫네요ㅎㅎ

2021-02-21 01:49 UTC, datalater commented on src/reducer.js
> +  return !(name !== '' && category !== '' && address !== '');
그러네요ㅎㅎ 부정문이 아니라 긍정문으로 처리할 수 있네요. 반영하겠습니다.

음.. 🤔 reducer에서 처리해줘야 하지 않나요? 잘 모르겠네요

2021-02-21 02:02 UTC, datalater commented on src/reducer.js
> +  return !(name !== '' && category !== '' && address !== '');
말씀해주신 걸로 미루어 보면 reducer가 아니라 `Container` 컴포넌트에서 처리할 수 있겠군요!

reducer가 아니라 dispatch 단계에서 막아주는 게 더 옳은 것 같네요. 어떤 기준으로 어떻게 판단해볼 수 있을까, 생각해봤는데 사용자가 세 입력 칸 중 하나라도 비어있는 채로 버튼을 클릭했을 때 '필수 입력 칸이 비어있습니다'와 같은 워닝 메시지를 띄워줄 것 같아요. 그러면 결국 리듀서에 오기 전에 컨테이너 단에서 처리해주는 게 더 맞을 것 같습니다.

이렇게 생각해봤는데 어떤가요? 👀

2021-02-21 02:29 UTC, datalater commented on src/reducer.js
> +  return !(name !== '' && category !== '' && address !== '');
bba229a -레스토랑 입력칸이 비어있을 경우 등록하지 않는지 테스트하라

49811e2 - 레스토랑 입력칸이 비어있을 경우 등록하지 않도록 구현하라

1161cbd - 입력칸이 비어있을 경우 등록하지 않는 책임을 리듀서에서 제거하라

2021-02-21 02:29 UTC, datalater commented on src/List.jsx
> +export default function List({ restaurants }) {
23368ff

2021-02-21 02:29 UTC, datalater commented on src/InputContainer.test.jsx
> +    }));
0d39301

2021-02-21 02:29 UTC, datalater commented on src/InputContainer.jsx
> +    restaurants: state.restaurants,
d142b27

2021-02-21 02:30 UTC, datalater commented on src/Input.jsx
> +export default function Input({
07ed7fc

2021-02-21 02:30 UTC, datalater commented
컴포넌트 이름 변경 후 커버리지 결과를 첨부합니다.

![image](https://user-images.githubusercontent.com/8105528/108613763-3caea080-7438-11eb-9a33-f7e78ac81814.png)

2021-02-21 02:33 UTC, datalater commented
[진행상황](https://github.com/CodeSoom/react-week4-assignment-2/pull/40#issue-575567464) 업데이트

2021-02-21 13:08 UTC, Kihyun92 commented on src/reducer.js
> +  return !(name !== '' && category !== '' && address !== '');
> reducer가 아니라 dispatch 단계에서 막아주는 게 더 옳은 것 같네요. 어떤 기준으로 어떻게 판단해볼 수 있을까, 생각해봤는데 사용자가 세 입력 칸 중 하나라도 비어있는 채로 버튼을 클릭했을 때 '필수 입력 칸이 비어있습니다'와 같은 워닝 메시지를 띄워줄 것 같아요. 그러면 결국 리듀서에 오기 전에 컨테이너 단에서 처리해주는 게 더 맞을 것 같습니다.

좋아요 ㅎㅎ 실제로 저희 팀에서는 이런 처리를 [React-Hook-Form](https://react-hook-form.com/kr/)과 같은 form 라이브러리를 통해 form validation과 같은 처리를 간편하게 하고 있어요.

2021-02-21 13:15 UTC, Kihyun92 approved these changes
고생하셨습니다~ TDD cycle을 익혀보는 쉽지 않은 한주 였는데 잘 해주신 것 같아요~ 💯 

고민을 많이 해보면서 과제를 하시는게 특히 좋았습니다 :) 

과제 풀이 영상도 꼭 보셨으면 좋겠습니다~

과제를 통해 무엇을 배우셨나요? 그리고 무엇을 더 배우고 싶으신가요?

슬랙 채널에 회고 남겨주시면 머지하도록 하겠습니다~

2021-03-03 09:17 UTC, datalater commented
너무 늦었네요. 죄송합니다 😢

[4주차 회고](https://www.notion.so/jayday/4-587e8fcffea34f428c33a509860e5b64)

2021-03-03 15:51 UTC, merged