레스토랑 만들기
CodeSoom/react-week4-assignment-2 pull request #46
Opened 2021-02-19 12:56 UTC by gyeongwon1275

일단 한데 까지만 PR 합니다!

2021-02-19 17:57 UTC, Kihyun92 requested changes
좋습니다 ㅎㅎ 앞으로도 한줄의 코드라도 일단 작업했다면 빠르게 PR을 만들어주세요~ 👍🏼 

TDD cycle에 맞춰 잘 진행하고 계신것 같네요. 진행하다가 의논이 필요하다면 편하게 말씀주세요!

2021-02-19 17:57 UTC, Kihyun92 commented on src/InputContainer.jsx
> +import RestaurantInput from './RestaurantInput';
각 모듈의 역할에 따라 공백을 통해 구분 지어주면 좋을 것 같아요~ 

```suggestion
import React from 'react';

import { useDispatch } from 'react-redux';

import { updateRestaurantInfo, addRestaurant } from './actions';

import RestaurantInput from './RestaurantInput';
```

2021-02-19 17:57 UTC, Kihyun92 commented on src/InputContainer.jsx
> +  }
구조분해할당을 해줄 수 있을 것 같아요~

```suggestion
  function handleChange(event) {
    const { target: { name, value } } = event;
    dispatch(updateRestaurantInfo({ [name]: value }));
  }
```

2021-02-19 17:57 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +    expect(getByRole('button')).toBeInTheDocument();
다른 버튼이 추가된다면 우리의 의도대로 테스트 되지 않을 수 있을 것 같아요.

조금 더 명확하게 해주는 건 어떨까요?

2021-02-19 17:57 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +    fireEvent.change(getByPlaceholderText('이름'), { target: { name: 'name', value: '선정릉역 깐부치킨' } });
인자가 만은 경우엔 가독성을 위해 줄바꿈 처리해주는게 좋을 것 같아요~

```suggestion
    fireEvent.change(getByPlaceholderText('이름'), {
      target: {
        name: 'name',
        value: '선정릉역 깐부치킨'
      }
    });
```

2021-02-19 17:57 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +    const { getByRole } = render(<InputContainer />);
각 테스트마다 반복되는 부분들이 있는 것 같아요. 반복 코드는 리팩터링 해주는게 좋을 것 같습니다 ㅎㅎ

2021-02-19 17:57 UTC, Kihyun92 commented on src/ListContainer.test.jsx
> +  context('when there is no list', () => {
`context`는 `when has no list` <-> `when has list` 와 같이 같은 맥락에서 반대되는 경우를 테스트할 때 사용합니다.

지금은 대응하는 테스트가 없는 것 같아요. 지금처럼 계층을 나누고 싶다면 `describe`로 처리하는게 더 좋을 것 같네요.

2021-02-19 17:57 UTC, Kihyun92 commented on src/reducer.js
> +  }
이번 과제도 마찬가지로 `if` 를 사용하지 않고 해결해보세요 :)

2021-02-20 06:13 UTC, gyeongwon1275 commented on src/InputContainer.jsx
> +  }
구조분해 할당 할까 말까 했었는데 하는게 낳았네요 ㅎ

2021-02-20 15:25 UTC, Kihyun92 requested changes

2021-02-20 15:25 UTC, Kihyun92 commented on src/RestaurantsContainer.jsx
> +function RestaurantsContainer() {
RestaurantsContainer로 한번 더 감싸준 이유가 있나요?

2021-02-20 15:25 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +  });
```suggestion
  beforeEach(() => {
    jest.clearAllMocks();
    
    useDispatch.mockImplementationOnce(() => dispatch);
  });
```

이렇게 beforeEach에서 처리해주면 어떨까요? 

개인적으로는 테스트를 시작하기 전에 기존에 mocking된 것들을 클리어해주는게 좋아보이기도 하고, 매 테스트의 시작과 종료 이후에 어떤일이 발생할지를 염두해두는 것 보다, 이 경우엔 시작전에 어떤 처리를 해야할지 만 알아도 될 것 같아서요 ㅎㅎ

2021-02-20 15:25 UTC, Kihyun92 commented on src/Item.jsx
> +      <span>{address}</span>
`template literal`을 이용해서 한줄로 처리해줘도 좋겠네요~

- https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Template_literals

2021-02-20 15:25 UTC, Kihyun92 commented on src/RestaurantList.jsx
> +function RestaurantList({ restaurantList }) {
`RestaurantList` 보다는 `Restaurants`는 어떤가요? 

List라는 의미는 여러가지로 해석이 가능할 것 같아요

배열이나 복수의 자료형을 표현할때는 **List 보다는 **s 를 통해 처리해줘도 의미가 전달이 됩니다.

2021-02-20 15:25 UTC, Kihyun92 commented on src/reducer.js
> +}
예외처리가 상당히 복잡하네요. 부정문으로 예외처리하는 부분은 보는 사람이 한번 더 생각하게 만들어서 권장하지 않습니다.

예외처리가 생긴 원인은 무엇인가요? 따로 함수로 추출해야하는 로직일지 한번 더 점검해보셔도 좋을 것 같습니다.

2021-02-20 15:25 UTC, Kihyun92 commented on src/actions.js
> +export const ADD_RESTAURANT = 'ADD_RESTAURANT';
action 타입을 따로 관리하는 이유가 있을까요?

2021-02-23 14:34 UTC, merged