4주차 2번째 과제
CodeSoom/react-week4-assignment-2 pull request #50
Opened 2021-05-24 10:18 UTC by yujong-lee

아직 진행 중입니다.
막히는 부분은 아직까지는 없는데 하나 궁금한 것이, 과제1번을 할 때도 느꼈는데
`reducer`에서 매개변수 기본값을 주는 부분같은 것 때문에 커버리지가 100이 안뜨는 경우가 있는데요.

당연히 테스트를 작성하는 기준은 스스로 느끼는 안정성이니까 이걸 테스트하는 것이 맞냐 아니냐를 따지는 것은 둘째로 하고, 그것을 어떤 식으로 테스트 하는 것이 좋을까요? 저는 일단 기본값만을 테스트하는 테스트를 짜지는 않고 다른 것을 테스트할 때 `undefined`를 끼워넣어주는 식으로 하긴했는데.

아무래도 따로 기본값만을 테스트하는 코드를 작성하는 것이 좋겠죠?

2021-05-24 15:35 UTC, Kihyun92 requested changes
TDD cycle을 잘 지키면서 과제를 진행해주시는 것 같아요! 👍🏼 👍🏼 

추후 관심사에 따라 container-presentation을 적용해보셔도 좋을 것 같네요~

-----

## 질문 답변
> 아무래도 따로 기본값만을 테스트하는 코드를 작성하는 것이 좋겠죠?

설명서 측면에서 보면 인자가 없는 경우에 기본값으로 처리된다는걸 알 수 있으면 좋을 것 같아요ㅎㅎ

2021-05-24 15:35 UTC, Kihyun92 commented on src/App.jsx
> +import List from './List';
외부와 내부 모듈 간에 공백을 추가해주세요~

2021-05-24 15:35 UTC, Kihyun92 commented on src/List.jsx
> +      })}
```suggestion
      {restaurants.map(({ id, name, category, address }) => (
          <li key={id}>
            {`${name} | ${category} | ${address}`}
          </li>
      ))}
```
위와 같이 표현하는건 어떨까요?

2021-05-25 04:01 UTC, yujong-lee commented on src/App.jsx
> +import List from './List';
수정했습니다~

2021-05-25 04:03 UTC, yujong-lee commented on src/List.jsx
> +      })}
그게 더 좋겠네요. 수정했습니다.

2021-05-26 11:56 UTC, yujong-lee commented
과제 완료했습니다. 모든 테스트를 통과합니다.

훅을 이용해서 관심사를 분리해줬습니다. 원래라면 렌더링과 관련된 테스트는 프리젠테이셔널 테스트에서, 상태관리 등은 컨테이너 테스트에서 해줬겠지만, 여기서는 컴포넌트를 나누지 않았으므로 훅에 대한 테스트를 따로 작성하지 않았습니다.

2021-05-26 15:45 UTC, Kihyun92 requested changes
> 훅을 이용해서 관심사를 분리해줬습니다. 원래라면 렌더링과 관련된 테스트는 프리젠테이셔널 테스트에서, 상태관리 등은 컨테이너 테스트에서 해줬겠지만, 여기서는 컴포넌트를 나누지 않았으므로 훅에 대한 테스트를 따로 작성하지 않았습니다.  이렇게 하는 것이 맞을까요?

`React hook testing library`를 사용해서 각 훅에 대한 테스트를 해주는 건 어떨까요?
- https://react-hooks-testing-library.com/

> `reducer.test.jsx`를 개선해야합니다.  현재 리듀서를 테스트할 때 입력값을 주지 않고 `undefined`를 넘겨 기본값을 이용해서 테스트하고 있는데, 명시적으로 입력값을 명시하고, 기본값을 이용하는 테스트는 따로 빼야합니다.
**-->** 이건 방금 수정했습니다.  여러 테스트들이 한 픽스쳐를 공유하지 않도록 `beforeEach`와 `let`을 사용했는데 저번에 `mockClear`같은 해법이 있는지 고민중입니다.

이 부분은 각 테스트마다 초기 값을 다르게 주는 방법 밖에 없을 것 같아요. 🤔

> 또 현재 훅과 관련된 네이밍이 별로 마음에 들지 않아 좀 더 알아보고 생각해봐야 할 것 같습니다.
특히 액션생성함수와 훅이 이름만 보고 구별이 되지 않는 것도 문제라고 생각됩니다. 트레이너님이 보시기에는 어떠신지요.

이 부분은 저도 느꼈는데, 액션의 네이밍을 조금 더 명확하게 해주면 어떨까요?

예를 들면 `updateField` -> `updateRestaurantField`로 하고, 관련된 훅은 `useUpdateRestaurant` 과 같이요. 이 부분은 조금 더 고민이 필요할 것 같네요 😭

> - 상태 구조
```js
// 아래와 같이?
const initialState = {
  info: {
    id: 1,
    name: '',
    category: '',
    address: '',
  },
  restaurants: [],
};
```
> 이런식으로 상태를 바꿔줄지 고민 중입니다.

훨씬 좋은 것 같네요 👍🏼  다만 `info` 보다 조금 더 명확한 네이밍을 해주면 좋을 것 같아요.

> - 리듀서 테스트
의도를 드러내는 것은 `name만` 바뀐걸 확인하는 것이 맞을 것 같은데 `리듀서` 테스트의 목적을 생각하면 `객체 전체`를 비교하는 것이 맞을 것 같아서 헷갈립니다.

테스트를 통해 어떤 의도를 드러내고 싶은지를 고민해보시면 좋을 것 같아요. `name`만 변경된다면 그걸 알려주는거죠. 😊   

답변을 남겨봤는데, 혹시 잘못됐거나 의논이 더 필요한 부분이 있다면 말씀해주세요~

2021-05-26 15:45 UTC, Kihyun92 commented on src/App.test.jsx
> +});
`describe`를 사용해서 무엇이 render를 하는지 나타내주는게 좋을 것 같아요~

2021-05-26 15:45 UTC, Kihyun92 commented on src/components/DataInput.jsx
> +export default function DataInput() {
`Data` 라는 걸 표현해줄 필요가 있을까요? 좀 더 간단하게 `Form`이나 `RestaurantForm`과 같이 표현하는건 어떨까요?

2021-05-26 18:43 UTC, yujong-lee commented on src/App.test.jsx
> +});
말씀을 듣고 생각해보니 테스트가 1개만 있는 경우도 `describe`로 감싸주는것이 더 나은 것 같아요. 수정했습니다.

2021-05-27 01:49 UTC, yujong-lee commented on src/components/DataInput.jsx
> +export default function DataInput() {
`RestaurantForm`으로 하는 것이 훨씬 낫겠네요. 수정했습니다.

2021-05-27 05:56 UTC, yujong-lee commented
리액트 훅 테스트를 작성하고 그 외 자잘한 변경을 했습니다.

> When not to use this library
> - Your hook is defined alongside a component and is only used there
> - Your hook is easy to test by just testing the components using it
공식문서를 봤을 때는 여기서는 굳이 이 라이브러리를 사용할 필요까진 없을 것 같기는 한데 한번 사용해보면서 연습이 되어서 좋았습니다. 이걸 설치하는 과정에서 `vulnerabilities high`가 뜨면서 `npm audit fix --force`를 하라고 해서 했는데 이후에 `npm start`가 안돼서 `package.json`을 초기 상태로 돌렸는데요, 이제 보니 `webpack-dev-server`의 버전이 내려간게 문제였네요.

리덕스 툴킷을 사용할까도 생각을 했는데 여기서는  앱의 크기가 작다보니까 굳이 사용할 필요는 없을 것 같아 안했습니다. 전에 사용해봤을 때는 코드 양이 꽤 줄기는 하는데 기존보다 코드를 이해하기가 어렵더라고요.

네이밍도 많이 수정하고 훅 리턴값도 변경하면서 가독성면에서 개선하려고 신경을 많이 썼습니다.

2021-05-27 16:01 UTC, kimkhyun requested changes
커스텀 훅을 잘 적용해주셨어요 👍🏼  과제를 하면서 커스텀 훅을 직접 적용해보신 분은 없었는데, 유종님 덕분에 저도 고민해보며 많은 걸 배운 것 같습니다. 😄

관련해서 트레이너들끼리도 `hooks`가 `Container/Presentational 패턴`을 대체할 수 있을지에 대해 이야기를 나눠 봤어요.

 다른 분들께선 `custom hook`이 관심사의 분리를 위해서라기 보단 코드 재사용을 위한 함수를 분리하는 의미가 더 강하다는 느낌이 든다는 말씀을 주셨어요. 
 그리고 분리한 커스텀 훅 코드를 보면 함수를 분리해서 사용했을 때 결국 비슷한 이름으로 또 감싸주려다 보니 중복을 피하려고 이름도 의도에 맞지 않게 짓는 경우도 발생하기 때문에 `의미를 더 드러내는가?`라는 관점에서 봤을땐 `Container/Presentational 패턴`이 상태관리를 어떻게 하고있는지 코드상으로도 더 잘 구분되고, 파일명으로도 구조 파악이 더 용이한 것 같다고 말씀해주셨어요ㅎㅎ

저도 현업에서 커스텀 훅을 주로 중복되는 이펙트 훅이나 함수들을 제어하기 위해 주로 사용했는데요, 사실 `커스텀 훅`과 `Container/Presentational 패턴`이 서로를 대체하는 개념은 아니기 때문에 상황에 맞게 사용하는게 좋겠다는 생각이 들었습니다.(가장 어려운 부분...😅)

아 그리고 아샬님과 다른 트레이너분들도 커스텀 훅 관련된 실험을 해보는게 정말 좋다는 말씀을 해주셨습니다 💯 

관련해서 유종님께서 직접 작업해보시면서 적용 이전과 이후에 든 생각도 궁금해요! 추후에 동료들에게 공유해주셔도 좋을 것 같습니다~ㅎㅎ

-----

그리고 `리덕스 툴킷`의 경우엔 8강에서 잠깐 다뤄볼 거에요. 리덕스 툴킷을 사용하지 않다가 사용하게 됨으로써 얻게되는 장점들을 느껴보실 수 있을 것 같아요 😊  물론 그 전에 사용해보셔도 좋습니다 ㅎㅎ

2021-05-27 16:01 UTC, kimkhyun commented on src/components/InputBox.test.jsx
> +    box.blur();
`box`라는 네이밍은 조금 많은 내용으로 해석이 될 것 같아요. 조금 더 명확한 네이밍이면 좋을 것 같습니다ㅎㅎ

그리고 `focus, blur` 처리를 해주신 의도가 궁금해요~

2021-05-27 16:01 UTC, kimkhyun commented on src/hooks/useRestaurants.test.js
> +    };
이 부분은 `beforeEach` 밖에 있어도 되지 않을까요?

2021-05-28 02:03 UTC, yujong-lee commented on src/components/InputBox.test.jsx
> +    box.blur();
`input`을 받을 때 `onChange`에 `dispatch`를 해서 `state`를 바꾸면 연속해서 `dispatch`를 해야해요. 그런데 이것은 [바람직하지 않다고 해서](https://redux.js.org/style-guide/style-guide#avoid-dispatching-many-actions-sequentially)(`input`에 대해서만 다룬 글도 있었던것 같은데 못찾겠네요),  유저의 입력이 완료되었을 때 `dispatch`를 하는 것으로 해봤어요.

그 완료되는 시점을 저는 `onBlur`로 잡아봤구요, 테스트를 할 때도 똑같이 `blur`가 되어야 `dispatch`가 되니까 그걸 해준 거에요. 그 전에 `focus`를 해준 이유는 저도 몰랐는데 저렇게 안하면 `blur`가 작동을 안하는 것 같더라고요. 실제로 유저가 사용할 때는 `focus`를 먼저 한 뒤에 `blur`가 되니까요. 사실 이렇게 유저가 사용하는대로 똑같이 해주는게 `user-event`라이브러리라서, `userEvent.type`하나로 될 줄 알았는데 안되네요. ㅋㅋ

2021-05-28 02:05 UTC, yujong-lee commented on src/components/InputBox.test.jsx
> +    box.blur();
`box`는 `inputControl`로 바꿔봤습니다~

2021-05-28 02:09 UTC, yujong-lee commented on src/hooks/useRestaurants.test.js
> +    };
수정했습니다.

2021-05-28 07:59 UTC, yujong-lee commented on src/components/InputBox.test.jsx
> +    box.blur();
말씀해주신 내용을 바탕으로 여러 생각을 해보고 실험도 해보고 나서 글 하나를 작성해서 슬랙에 공유했습니다. 의견 한번 부탁드려요~ ㅎㅎ
https://yujonglee.com/wiki/socwithhooks/

2021-05-28 16:39 UTC, Kihyun92 commented on src/components/InputBox.test.jsx
> +    box.blur();
크 너무 좋습니다!! 👍🏼  특히 각각을 비교하고 통합해주신 부분이 좋네요 😊

말씀하신대로 중요한건 필요할때 적절하게 사용하는거죠ㅎㅎ 

글을 잘 정리하시는 것 같아요. 다른 글도 기대가 됩니다~

(추가로 블로그에 댓글을 달기위해 sign in 버튼을 누르면 404 페이지로 이동하네요)

2021-05-28 16:41 UTC, Kihyun92 approved these changes
이번주 과제는 이정도로 마무리하면 될 것 같군요. 혹시 의논이 필요한 부분이 있다면 말씀해주세요~

과제 풀이 영상을 보시고 아샬님은 어떤 방식으로 접근하는지 보시면 좋을 것 같습니다!

이번주도 고생하셨습니다~ 슬랙 채널에 회고 남겨주세요 😁

2021-05-31 15:51 UTC, merged