4주차 과제1 (레스토랑 정보 확인 및 예약 시스템 구축)
CodeSoom/react-week4-assignment-2 pull request #52
Opened 2021-05-27 02:46 UTC by seong-dodo

안녕하세요.

드디어 `과제2` 시작하였습니다.
`과제1`에만 너무 매달려있었나봅니다 ㅜㅜ
이틀남았지만 최대한 많이 과제 수행에 몰두하겠습니다~~~~~

2021-05-27 16:18 UTC, Kihyun92 requested changes
`TDD cycle`에 맞게 `RED-GREEN-REFACTORING`에 맞춰 작업해보려 노력하신 것 같아요 👍🏼 

App 컴포넌트가 굉장히 복잡해졌네요. 앞으로 기능이 추가될수록 더 복잡해질 것 같군요.

컴포넌트들을 관심사에 따라 `Container-Presentaional 패턴`을 적용해보셔도 좋을 것 같습니다~ 😄

- https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0

2021-05-27 16:18 UTC, Kihyun92 commented on src/App.jsx
> +function slector(restaurant) {
오타가 있네요. `selector`

2021-05-27 16:18 UTC, Kihyun92 commented on src/App.test.jsx
> +  it('App 화면', () => {
설명서처럼 다른 동료가 테스트 코드만 보고 이해할 수 있도록 해당 테스트의 의도를 나타내주는건 어떨까요?

간단하게 예를 들어보면 `renders form`과 같이 하면, `App은 form을 그려줍니다.`와 같이 해석 될 것 같아요.

2021-05-27 16:18 UTC, Kihyun92 commented on src/reducer.js
> +      }],
```suggestion
      restaurants: [
        ...restaurants, 
        {
          id: newId, 
          name, 
          category, 
          address,
        }
      ],
```
인자가 많은 경우에는 줄바꿈과 간격을 줌으로써 더 읽게 쉽게 해주는게 좋을 것 같아요~

2021-05-27 16:18 UTC, Kihyun92 commented on src/reducer.test.js
> +      // given
주석 없이도 해당 의도가 느껴지도록 하는게 좋을 것 같아요~

2021-05-28 14:24 UTC, seong-dodo commented on src/App.jsx
> +function slector(restaurant) {
감사합니다 😃

2021-05-28 14:25 UTC, seong-dodo commented on src/App.test.jsx
> +  it('App 화면', () => {
피드백 반영해서 테스트 코드만 보고도 이해할 수 있도록 해보겠습니다~~~

2021-05-28 14:25 UTC, seong-dodo commented on src/reducer.test.js
> +      // given
넵!!! 주석도 제거할게요~~~ 👍

2021-05-28 15:48 UTC, Kihyun92 requested changes
계속 해서 서술이 반복되는 느낌이 있는데 테스트의 목적 대해 좀 더 명확하게 설명하면 좋을 것 같아요😊

2021-05-28 15:48 UTC, Kihyun92 commented on src/App.test.jsx
> +  it('render로 App 화면을 그려지는 모습 확인 ', () => {
테스트를 자세하게 작성해주셨군요ㅎㅎ 조금만 더 간결하게 작성해줘도 좋을 것 같아요~ 😅

이게 테스트인건 파일 네임을 통해 알 수 있죠.
```suggestion
describe('App', () => {
  it('레스토랑 정보를 입력하는 폼을 그린다 ', () => {
```
위와 같이 작성해주는건 어떤가요? 사용 설명서 측면에서 어떤걸 알려주고 싶은지 고민해보시면 좋을 것 같습니다. 😄

2021-05-28 15:48 UTC, Kihyun92 commented on src/reducer.test.js
> +  context('입력값을 입력하면 상태가 변하는 테스트', () => {
`context`는 주로 대칭되는 경우에 사용합니다. 예를 들면, `할일이 있는 경우 <-> 할일이 없는 경우` 와 같이요.

이외의 경우엔 `describe`를 사용하는게 적절해보여요 ㅎㅎ

2021-05-30 15:13 UTC, Kihyun92 approved these changes
TDD cycle을 잘 지키며 개발하려고 노력하신 부분이 너무 좋네요 👍🏼 

과제 풀이 영상을 보시고 아샬님은 어떤 방식으로 풀어나가시는지 확인해보시면 좋을 것 같습니다~

슬랙 채널에 회고 남겨주세요 😊

2021-05-30 15:13 UTC, Kihyun92 commented on src/InputContainer.test.jsx
> +    const { getByPlaceholderText } = render(<InputContainer />);
중복되는 테스트 코드들은 함수로 추출해주고, 함수 mocking의 경우에는 beforeEach를 사용해주면 좋습니다!

이렇게 하면 각 테스트가 독립적으로 실행되도록 mock함수를 clear 해줄 수도 있어요.

- https://jestjs.io/docs/mock-function-api#mockfnmockclear
- https://jestjs.io/docs/jest-object#jestclearallmocks

2021-06-01 02:32 UTC, seong-dodo commented on src/App.test.jsx
> +  it('render로 App 화면을 그려지는 모습 확인 ', () => {
넵 감사합니다.
사용 설명서 측면에서 고민해보도록 해보겠습니다 🔥

2021-06-08 06:20 UTC, seong-dodo commented
안녕하세요. 
여기도 마찬가지로 코드숨 `main` 브랜치로 PR을 보내게 되어  `seong-dodo` 브랜치로 변경하였고, 피드백 반영하지 못한 부분 추가로 반영하였습니다 😀

2021-08-08 07:49 UTC, merged