레스토랑 정보 확인 및 예약 시스템 구축하기
CodeSoom/react-week4-assignment-2 pull request #7
Opened 2020-06-27 14:22 UTC by kwonmory

따로 다시 해보고 있는데, 전에 했던 부분 리뷰 받으려고 올립니다.

과제 풀이 영상을 보기전과 본 후 비교를 해봐야겠어요 ㅋㅋㅋ;;

하다보니깐 깃 커밋 이력도 많이 왔다리갔다리하고..

하면서 테스트 케이스 작성하는데 이렇게 이렇게 해야지 하고 시작했다가 구현하다가 테스트코드를 많이 수정하게 되더라구요. 이래도 되는건가요.;;

이러니깐 테스트케이스를 가지고 구현하는게 아니라 구현에 따라 테스트코드를 바꾸게 되는 듯한 기분이랄까요..

2020-06-28 06:15 UTC, wholemann requested changes
아쉬운 부분들에 대해 comment 남겨드렸으니 과제 진행에 참고하시면 되겠습니다.

그리고 TDD는 테스트 위주로 돌아가는 개발 방법론이 아니라

빠른 피드백을 통해 설계의 오류를 최대한 빨리 발견하고 끝없이 개선하는 게 핵심입니다.

당연히 개발을 하다보면 수정사항이 생기고 그에 대한 신호를 자동화된 테스트를 통해 알려주죠.

A 부분에 대한 테스트를 구현하다 보면 전혀 상관 없을 것 같은 B 부분의 테스트 코드를 수정해야 될 수도 있습니다.

자연스러운 현상이니 너무 강박을 갖지 않으셔도 좋습니다.

2020-06-28 06:15 UTC, wholemann commented on src/InputContainer.jsx
> +    address: selector.input.address,
이부분은 restaurant 이라는 하나의 object로 묶을 수 있겠네요.

2020-06-28 06:15 UTC, wholemann commented on src/InputContainer.jsx
> +      address: e.target[2] ? e.target[2].value : '',
이미 inputChange를 통해 현재 form에 있는 상태를 redux에 전달했는데

addRestaurant에 input을 전달할 필요가 있을까요?

2020-06-28 06:15 UTC, wholemann commented on src/Input.jsx
> +export default function Input({
Input 보단 RestaurantForm이 명확한 역할을 표현해줄 것 같네요.

2020-06-28 06:15 UTC, wholemann commented on src/InputContainer.jsx
> +export default function InputContainer() {
RestaurantFormContainer 는 어떨까요

2020-06-28 06:15 UTC, wholemann commented on src/ListContainer.jsx
> +export default function ListContainer() {
어떤 목록인지 의미가 불명확합니다.
리스트 형태의 컴포넌트가 늘어나면 어떻게 될까요?

이건 배열을 array라고 이름 붙이는 것과 같습니다.

RestaurantsContainer는 어떨까요?

2020-06-28 06:15 UTC, wholemann commented on src/reducer.js
> +    const { name, category, address } = action.payload.input;
이 부분은 state에서 받아올 수 있을 겁니다.

이미 updateInput이라는 액션이 있기 때문이죠.

2020-06-28 16:35 UTC, kwonmory commented on src/Input.jsx
> +export default function Input({
넵넵 컴포넌트 이름도 역할에 맞게 표현해야겠어요!

2020-06-28 16:36 UTC, kwonmory commented on src/InputContainer.jsx
> +      address: e.target[2] ? e.target[2].value : '',
아...? 헐.. 그렇네요!! 충격이네요...

2020-06-28 16:37 UTC, kwonmory commented on src/ListContainer.jsx
> +export default function ListContainer() {
지금보니.. 공감합니다...명명에 신경을 좀 더 써볼께요!

2020-06-28 16:39 UTC, kwonmory commented on src/reducer.js
> +    const { name, category, address } = action.payload.input;
이것도 액션 보낼 때.. 충격입니다!!... 데이터 흐름을 좀 더 생각해보고 코드 작성을 해야겠어요.

2020-06-29 14:14 UTC, wholemann commented
@kwonmory 통과되도록 마무리해서 보내주시면 Merge할게요:)

2020-06-30 23:33 UTC, wholemann approved these changes
고생하셨습니다:)

Merge할게요! 다음 과제도 화이팅입니다:)

2020-06-30 23:33 UTC, merged