[4주차|과제2] 레스토랑 정보 확인 및 예약 시스템 구축하기 코드리뷰 부탁드립니다.
CodeSoom/react-week4-assignment-2 pull request #8
Opened 2020-06-27 21:45 UTC by jiunkoo

기본적인 예약 시스템만 완성했습니다. 일단 PR한 후에 나머지 작업 마저 하도록 하겠습니다.

2020-06-28 03:03 UTC, hannut91 requested changes
단계별로 잘 적용하고 계신 것 같아요 ㅎㅎ 리덕스로 리팩터링하는 것도 잘 마무리 해주세요!

2020-06-28 03:03 UTC, hannut91 commented on src/App.jsx
> +  }
같은 일을 하는 함수가 여러개 있는 것 같아요. event.target.name을 활용하여 하나의 함수로 만들어보세요

See also
  - https://reactjs.org/docs/forms.html

2020-06-28 03:03 UTC, hannut91 commented on src/App.jsx
> +        reservations={reservations}
레스토랑 예약 앱이라고 해서 `reservations`라고 하신 것 같아요. 지금 예약하는 앱은 아니니까 `restaurants`가 더 적절할 것 같아요

2020-06-28 03:03 UTC, hannut91 commented on src/App.jsx
>  export default function App() {
`App`이 상태를 관리하게 만드셨군요 ㅎㅎRedux Store가 상태를 관리하도록 리팩터링 해주세요!

2020-06-28 03:03 UTC, hannut91 commented on src/List.test.jsx
> +  ];
반복적으로 사용되는 데이터는 `fixture`로 분리해주면 좋을 것 같아요

2020-06-28 06:10 UTC, jiunkoo commented
완성했습니다. 코드 리뷰 부탁드립니다.

질문) useEffect로 추가한 초기값 테스트가 잘 안되어서 해당 부분은 제외했습니다. 도와주세요ㅠㅠ

2020-06-28 15:42 UTC, hannut91 approved these changes
고생하셨습니다! 꼼꼼하게 테스트를 잘 작성해주셨네요 ㅎㅎ 코드를 작성할 때 분명히 이전에도 작성한 것 같은데? 라는 느낌이 들거나 모양이 비슷해 보이거나 할 때 중복을 제거해야 할 신호를 받아들여서 중복을 제거하는 연습을 하면 좋을 것 같아요.

2020-06-28 15:42 UTC, hannut91 commented on src/App.test.jsx
> +    useDispatch.mockImplementation(() => dispatch);
`const dispatch = jest.fn();`와 `useDispatch.mockImplementation(() => dispatch);`는 서로 연관이 있으니 서로 가까운 곳에 위치하는게 좋을 것 같아요

2020-06-28 15:42 UTC, hannut91 commented on src/App.test.jsx
> +    useDispatch.mockImplementation(() => dispatch);
계속 중복되어 사용하는 것이 보이네요. 계속 반복되는 패턴을 발견하면 중복을 제거하는 연습을 하시면 좋을 것 같아요

2020-06-28 15:42 UTC, hannut91 commented on src/InputContainer.jsx
> +  }
계속 반복되는 모양이 있네요. 어떻게 하면 중복을 제거할 수 있을까요?

See also
  - https://reactjs.org/docs/forms.html#handling-multiple-inputs

2020-06-28 15:42 UTC, hannut91 commented on src/reducer.test.js
> +  });
`describe-context-it`을 사용해서 표현력을 더 좋게하면 좋을 것 같아요. 

```js
describe('reducer', () => {
  context('when previous state is undefined', () => {
    it('returns initialState', () => {
      ...
    });
  });

  context('with not existing action', () => {
    it('returns previous state', () => {
      ...
    });
  });
});
```

See also
  - http://www.betterspecs.org/#contexts

2020-06-28 15:42 UTC, hannut91 commented on src/reducer.test.js
> +        },
여기도 계속 반복되는 곳이 보이네요.

2020-06-28 15:42 UTC, hannut91 commented
`useEffect`에 대한 것은 DM으로 메시지 드릴게요 ㅎㅎ

2020-06-28 15:43 UTC, hannut91 commented
추가로 이번 과제를 진행하면서 어떤 것을 배우셨나요? 배운 것을 다음 과제에서 적용해보고 싶은 것이 있으신가요?

2020-06-29 04:17 UTC, merged

2020-06-29 05:55 UTC, jiunkoo commented
한 일 
- TDD로 redux 적용해서 todo-list 개발
- TDD로 redux 적용해서 레스토랑 예약 시스템 개발

느낀점
4주차 과제1 : todo-list 개발에만 거의 6일이 걸렸습니다. 참고할 영상이 있음에도 불구하고, 그 과정을 거꾸로 실현하기는 정말 어려웠습니다. 익숙한 '구현 후 테스트' 습관을 고치기 위해서 부단히 노력해야 했습니다. todolist 작성 중간에 테스트 없이 redux를 적용 후 Container 작업을 시작했을 때 정말 되돌리기 싫었습니다. 하지만 결국 커밋을 되돌렸고 저는 강사님의 도움으로 test 100% 통과 후 과제를 제출할 수 있었습니다.

4주차 과제2 : 첫 번째 과제를 마무리하고 보니 토요일 밤이어서 일요일 하루를 꼬박 할애해도 제출하기 쉽지 않을 거라는 생각이 들었습니다. 일단 첫 번째 과제를 하며 배운 방식 그대로 진행하기로 마음먹었습니다. 첫 번째 과제보다 훨씬 빠르게 개발이 이루어졌습니다. 일단 시간 내에 제출하는 걸 목표로 삼았기 때문에 반복되는 코드 리팩토링 없이 진행했습니다. 급했기 때문에 PR을 열어놓고 작업하는 대로 push를 했는데 다행히 밤을 새서 오후 즈음에 마무리가 되었습니다. 강사님께서 코드 리뷰를 해주셨지만, 피곤해서 그 부분은 제대로 반영하지 못했습니다.

2주차 과제2 : 2주차 과제의 PR이 줄곧 열려 있었는데, 4주차 과제를 끝내고 다시 보니 정말 쉽게 todo list를 작성할 수 있었습니다. 리팩토링 후 강사님께 slack으로 메세지를 드렸고, 해당 과제는 merge가 되었습니다. 시간이 지나고 다시 4주차 과제를 보면 그 때의 저는 '왜 이런 걸 고민했지?' 같은 생각을 하고 있을지도 모르겠습니다.

배운점
git reset HEAD^ 명령어를 확실하게 외웠습니다.
잘게 나누어서 커밋하니 작성할 때는 불편해도 작업이 완전히 분리되어 되돌아보기 좋았습니다.
꼭 코드 리뷰를 받기 위해서 PR을 열기보다 일단 PR을 열어놓고 중간 중간 점검받으며 과제를 완성하는게 학습에 더 좋았습니다.

어떻게 할지
- PR 열고 과제 진행하기
- 커밋 잘게 쪼개기
- 반복되는 코드 리팩토링 해보기
- test 코드 작성 시 describe(), context(), it() 사용해보기